"""
Test suite: Envoy agent-ergonomics surface (get_guidance, write-effect
footer, get_focus).

Covers the three additions that make Envoy self-explaining to agents that
never see .claude/:

- get_guidance -- worker-side, filesystem-only doctrine server. Topic
  normalization and fuzzy matching, front-matter/heading description
  extraction, directory scanning, the response-size cap, and the
  actionable error when no rules/skills are deployed anywhere.
- The '_effects' footer -- the newly-appeared-errors diff and the
  frame-rate regression test, both pure, plus the guards that keep the
  attach helper from ever breaking a response.
- get_focus -- the pane/selection reader, checked against the live UI
  (its headless branch is the only path this box cannot exercise).

Everything except the get_focus/live-attach cases is pure Python: no
operators are created and no TD state is mutated.
"""

import inspect
import os
import sys
import tempfile

runner_mod = op.unit_tests.op('TestRunnerExt').module
EmbodyTestCase = runner_mod.EmbodyTestCase

_envoy_mod = op.Embody.op('EnvoyExt').module
_read_mod = op.Embody.op('envoy_read').module


RULE_DOC = """<!-- Generated by Embody/Envoy - Do not remove this comment -->
# Network Layout Conventions

Signal flows left to right.
"""

SKILL_DOC = """---
name: create-operator
description: "MUST READ before creating or moving any operator."
---
<!-- Generated by Embody/Envoy - Do not remove this comment -->

# Create Operator Workflow

Step one.
"""


def _bare_worker():
    """EnvoyMCPServer carrying only the guidance state, skipping __init__
    (which imports the MCP SDK and registers every tool)."""
    W = _envoy_mod.EnvoyMCPServer
    w = W.__new__(W)
    w._guidance_state = {'ts': 0.0, 'root': None, 'index': None,
                         'searched': []}
    return w


def _make_claude_tree(base, rules=None, skills=None):
    """Write a .claude/rules + .claude/skills tree under `base`; return the
    .claude directory."""
    claude = os.path.join(base, '.claude')
    rules_dir = os.path.join(claude, 'rules')
    skills_dir = os.path.join(claude, 'skills')
    os.makedirs(rules_dir)
    os.makedirs(skills_dir)
    for name, text in (rules or {}).items():
        with open(os.path.join(rules_dir, name + '.md'), 'w',
                  encoding='utf-8') as f:
            f.write(text)
    for slug, text in (skills or {}).items():
        slug_dir = os.path.join(skills_dir, slug)
        os.makedirs(slug_dir)
        with open(os.path.join(slug_dir, 'SKILL.md'), 'w',
                  encoding='utf-8') as f:
            f.write(text)
    return claude


# =====================================================================
# get_guidance: pure helpers
# =====================================================================

class TestGuidanceHelpers(EmbodyTestCase):

    def test_key_collapses_case_and_punctuation(self):
        key = _envoy_mod._guidance_key
        self.assertEqual(key('create-operator'), 'createoperator')
        self.assertEqual(key('create_operator'), 'createoperator')
        self.assertEqual(key('CreateOperator'), 'createoperator')
        self.assertEqual(key('/create-operator'), 'createoperator')
        self.assertEqual(key(''), '')
        self.assertEqual(key(None), '')

    def test_description_prefers_front_matter(self):
        desc = _envoy_mod._guidance_description(SKILL_DOC)
        self.assertEqual(
            desc, 'MUST READ before creating or moving any operator.')

    def test_description_falls_back_to_first_heading(self):
        desc = _envoy_mod._guidance_description(RULE_DOC)
        self.assertEqual(desc, 'Network Layout Conventions')

    def test_description_skips_front_matter_body(self):
        doc = '---\nname: x\n---\n# Real Heading\n\ntext\n'
        self.assertEqual(_envoy_mod._guidance_description(doc),
                         'Real Heading')

    def test_description_falls_back_to_first_line(self):
        self.assertEqual(_envoy_mod._guidance_description('just prose\n'),
                         'just prose')

    def test_description_empty_document(self):
        self.assertEqual(_envoy_mod._guidance_description(''), '')
        self.assertEqual(_envoy_mod._guidance_description(None), '')

    def test_description_unquotes_single_quoted_value(self):
        doc = "---\ndescription: 'quoted value'\n---\n# H\n"
        self.assertEqual(_envoy_mod._guidance_description(doc),
                         'quoted value')


class TestGuidanceTopicMatching(EmbodyTestCase):

    IDS = ['create-operator', 'network-layout', 'td-python',
           'parameter-design', 'manage-annotations']

    def _match(self, query):
        return _envoy_mod._match_guidance_topic(query, self.IDS)

    def test_exact_match(self):
        matched, suggestions = self._match('create-operator')
        self.assertEqual(matched, 'create-operator')
        self.assertEqual(suggestions, [])

    def test_underscore_and_bare_variants_match(self):
        self.assertEqual(self._match('create_operator')[0], 'create-operator')
        self.assertEqual(self._match('createoperator')[0], 'create-operator')
        self.assertEqual(self._match('CREATE-OPERATOR')[0], 'create-operator')

    def test_prefix_match_when_unambiguous(self):
        self.assertEqual(self._match('network')[0], 'network-layout')

    def test_slash_prefixed_skill_name_matches(self):
        self.assertEqual(self._match('/td-python')[0], 'td-python')

    def test_miss_returns_suggestions(self):
        matched, suggestions = self._match('creat-operatr')
        self.assertIsNone(matched)
        self.assertIn('create-operator', suggestions)

    def test_miss_with_no_close_match_still_returns_list(self):
        matched, suggestions = self._match('zzzzzzzz')
        self.assertIsNone(matched)
        self.assertIsInstance(suggestions, list)

    def test_empty_query_never_matches(self):
        matched, suggestions = self._match('')
        self.assertIsNone(matched)
        self.assertIsInstance(suggestions, list)

    def test_empty_id_list(self):
        matched, suggestions = _envoy_mod._match_guidance_topic('x', [])
        self.assertIsNone(matched)
        self.assertEqual(suggestions, [])


# =====================================================================
# get_guidance: scanning and the tool body
# =====================================================================

class TestGuidanceScanAndBody(EmbodyTestCase):

    def _worker_on(self, claude_dir):
        w = _bare_worker()
        # Shadow the search so the test never picks up this repo's real
        # .claude via the cwd fallback.
        w._guidanceSearchDirs = lambda: [claude_dir]
        return w

    def test_scan_indexes_rules_and_skills(self):
        with tempfile.TemporaryDirectory() as td:
            claude = _make_claude_tree(
                td, rules={'network-layout': RULE_DOC},
                skills={'create-operator': SKILL_DOC})
            index = _envoy_mod.EnvoyMCPServer._guidanceScanDir(claude)
            self.assertIn('network-layout', index)
            self.assertIn('create-operator', index)
            self.assertEqual(index['network-layout']['kind'], 'rule')
            self.assertEqual(index['create-operator']['kind'], 'skill')
            self.assertEqual(index['network-layout']['description'],
                             'Network Layout Conventions')

    def test_scan_missing_directory_is_empty_not_raising(self):
        with tempfile.TemporaryDirectory() as td:
            index = _envoy_mod.EnvoyMCPServer._guidanceScanDir(
                os.path.join(td, 'nope', '.claude'))
            self.assertEqual(index, {})

    def test_scan_skips_empty_and_non_markdown(self):
        with tempfile.TemporaryDirectory() as td:
            claude = _make_claude_tree(td, rules={'good': RULE_DOC})
            rules_dir = os.path.join(claude, 'rules')
            with open(os.path.join(rules_dir, 'blank.md'), 'w',
                      encoding='utf-8') as f:
                f.write('   \n')
            with open(os.path.join(rules_dir, 'notes.txt'), 'w',
                      encoding='utf-8') as f:
                f.write('# ignored')
            index = _envoy_mod.EnvoyMCPServer._guidanceScanDir(claude)
            self.assertEqual(sorted(index), ['good'])

    def test_scan_disambiguates_rule_skill_slug_collision(self):
        with tempfile.TemporaryDirectory() as td:
            claude = _make_claude_tree(
                td, rules={'parameters': RULE_DOC},
                skills={'parameters': SKILL_DOC})
            index = _envoy_mod.EnvoyMCPServer._guidanceScanDir(claude)
            self.assertEqual(len(index), 2,
                             'a slug collision must keep both documents')
            self.assertIn('parameters', index)

    def test_bare_call_lists_topics(self):
        with tempfile.TemporaryDirectory() as td:
            claude = _make_claude_tree(
                td, rules={'network-layout': RULE_DOC},
                skills={'create-operator': SKILL_DOC})
            result = self._worker_on(claude)._get_guidance()
            self.assertEqual(result['count'], 2)
            self.assertNotIn('error', result)
            topics = {t['topic']: t for t in result['topics']}
            self.assertEqual(topics['network-layout']['kind'], 'rule')
            self.assertEqual(topics['create-operator']['kind'], 'skill')
            self.assertTrue(result['usage'])

    def test_topic_call_returns_content(self):
        with tempfile.TemporaryDirectory() as td:
            claude = _make_claude_tree(
                td, skills={'create-operator': SKILL_DOC})
            result = self._worker_on(claude)._get_guidance('create_operator')
            self.assertEqual(result['topic'], 'create-operator')
            self.assertEqual(result['kind'], 'skill')
            self.assertIn('Create Operator Workflow', result['content'])
            self.assertNotIn('truncated', result)

    def test_long_document_is_truncated_and_says_so(self):
        with tempfile.TemporaryDirectory() as td:
            long_doc = '# Big\n\n' + ('x' * (_envoy_mod._GUIDANCE_MAX_CHARS + 500))
            claude = _make_claude_tree(td, rules={'big': long_doc})
            result = self._worker_on(claude)._get_guidance('big')
            self.assertTrue(result['truncated'])
            self.assertLen(result['content'], _envoy_mod._GUIDANCE_MAX_CHARS)
            self.assertIn('truncated', result['note'].lower())

    def test_unknown_topic_returns_list_and_did_you_mean(self):
        with tempfile.TemporaryDirectory() as td:
            claude = _make_claude_tree(
                td, skills={'create-operator': SKILL_DOC})
            result = self._worker_on(claude)._get_guidance('creat-operatr')
            self.assertIn('error', result)
            self.assertIn('create-operator', result['did_you_mean'])
            self.assertEqual(result['count'], 1)

    def test_no_docs_anywhere_returns_actionable_error(self):
        with tempfile.TemporaryDirectory() as td:
            missing = os.path.join(td, '.claude')
            result = self._worker_on(missing)._get_guidance()
            self.assertIn('error', result)
            self.assertIn('InitEnvoy', result['action'])
            self.assertEqual(result['searched'], [missing])

    def test_index_is_cached_within_ttl(self):
        with tempfile.TemporaryDirectory() as td:
            claude = _make_claude_tree(td, rules={'one': RULE_DOC})
            w = self._worker_on(claude)
            self.assertEqual(w._get_guidance()['count'], 1)
            with open(os.path.join(claude, 'rules', 'two.md'), 'w',
                      encoding='utf-8') as f:
                f.write(RULE_DOC)
            self.assertEqual(w._get_guidance()['count'], 1,
                             'index must be served from cache inside the TTL')
            w._guidance_state['ts'] = 0.0  # force expiry
            self.assertEqual(w._get_guidance()['count'], 2)

    def test_search_dirs_lead_with_the_repo_root(self):
        w = _bare_worker()
        sentinel = os.path.join(tempfile.gettempdir(), '_tc_guidance_root')
        had = hasattr(sys, '_envoy_repo_root')
        previous = getattr(sys, '_envoy_repo_root', None)
        try:
            sys._envoy_repo_root = sentinel
            dirs = w._guidanceSearchDirs()
        finally:
            if had:
                sys._envoy_repo_root = previous
            else:
                try:
                    del sys._envoy_repo_root
                except AttributeError:
                    pass
        self.assertEqual(dirs[0], os.path.join(sentinel, '.claude'))
        self.assertGreater(len(dirs), 1, 'ancestors/cwd fallbacks missing')


# =====================================================================
# Write-effect footer: pure diff + regression helpers
# =====================================================================

class TestNewErrorDiff(EmbodyTestCase):

    def _entries(self, *paths):
        return [{'nodePath': p, 'message': 'boom at ' + p} for p in paths]

    def test_first_write_establishes_baseline_only(self):
        listed, total, paths = _envoy_mod._new_error_entries(
            None, self._entries('/a', '/b'), 3)
        self.assertEqual(listed, [])
        self.assertEqual(total, 0)
        self.assertEqual(paths, {'/a', '/b'})

    def test_only_additions_reported(self):
        listed, total, paths = _envoy_mod._new_error_entries(
            {'/a'}, self._entries('/a', '/b'), 3)
        self.assertEqual(total, 1)
        self.assertEqual(listed[0]['path'], '/b')
        self.assertEqual(paths, {'/a', '/b'})

    def test_disappearing_errors_are_not_reported(self):
        listed, total, paths = _envoy_mod._new_error_entries(
            {'/a', '/b'}, self._entries('/a'), 3)
        self.assertEqual(listed, [])
        self.assertEqual(total, 0)
        self.assertEqual(paths, {'/a'})

    def test_cap_limits_list_but_not_the_count(self):
        listed, total, _paths = _envoy_mod._new_error_entries(
            set(), self._entries('/a', '/b', '/c', '/d', '/e'), 3)
        self.assertLen(listed, 3)
        self.assertEqual(total, 5)

    def test_repeated_messages_on_one_op_collapse(self):
        entries = [{'nodePath': '/a', 'message': 'one'},
                   {'nodePath': '/a', 'message': 'two'}]
        listed, total, _paths = _envoy_mod._new_error_entries(
            set(), entries, 3)
        self.assertLen(listed, 1)
        self.assertEqual(total, 1)

    def test_malformed_entries_are_skipped(self):
        entries = [None, 'nonsense', {}, {'nodePath': ''},
                   {'nodePath': '/ok', 'message': 'm'}]
        listed, total, paths = _envoy_mod._new_error_entries(
            set(), entries, 3)
        self.assertEqual(paths, {'/ok'})
        self.assertEqual(total, 1)
        self.assertEqual(listed[0]['path'], '/ok')

    def test_none_input_is_empty(self):
        listed, total, paths = _envoy_mod._new_error_entries(set(), None, 3)
        self.assertEqual((listed, total, paths), ([], 0, set()))

    def test_message_is_length_capped(self):
        entries = [{'nodePath': '/a', 'message': 'x' * 500}]
        listed, _total, _paths = _envoy_mod._new_error_entries(
            set(), entries, 3)
        self.assertLen(listed[0]['message'], 200)


class TestFpsRegression(EmbodyTestCase):

    def test_meaningful_drop_reported(self):
        drop = _envoy_mod._fps_regression(60.0, 20.0)
        self.assertEqual(drop['was'], 60.0)
        self.assertEqual(drop['now'], 20.0)
        self.assertEqual(drop['drop_pct'], 67)

    def test_jitter_is_silent(self):
        self.assertEqual(_envoy_mod._fps_regression(60.0, 59.0), {})
        self.assertEqual(_envoy_mod._fps_regression(60.0, 58.0), {})

    def test_proportional_but_tiny_absolute_drop_is_silent(self):
        # 10 -> 8 is a 20% drop but only 2 fps: below the absolute floor.
        self.assertEqual(_envoy_mod._fps_regression(10.0, 8.0), {})

    def test_improvement_is_silent(self):
        self.assertEqual(_envoy_mod._fps_regression(20.0, 60.0), {})

    def test_missing_or_bogus_samples_are_silent(self):
        self.assertEqual(_envoy_mod._fps_regression(None, 30.0), {})
        self.assertEqual(_envoy_mod._fps_regression(60.0, None), {})
        self.assertEqual(_envoy_mod._fps_regression('x', 30.0), {})
        self.assertEqual(_envoy_mod._fps_regression(0.0, 30.0), {})
        self.assertEqual(_envoy_mod._fps_regression(60.0, 0.0), {})


# =====================================================================
# Write-effect footer: the attach helper must never break a response
# =====================================================================

class _BrokenExt:
    """Stand-in ext with no _effects_state -- _attachEffects must degrade
    silently rather than raise through the response chokepoint."""
    ownerComp = None


class TestEffectsAttachGuards(EmbodyTestCase):

    SID = '_tc_effects_sid'

    def setUp(self):
        super().setUp()
        self.envoy = self.embody.ext.Envoy
        self.assertTrue(hasattr(self.envoy, '_effects_state'),
                        'running EnvoyExt predates the write-effect footer')
        self.envoy._effects_state.pop(self.SID, None)
        self._scan_ok = getattr(self.envoy, '_effects_error_scan_ok', True)
        self.envoy._effects_error_scan_ok = True

    def tearDown(self):
        self.envoy._effects_state.pop(self.SID, None)
        self.envoy._effects_error_scan_ok = self._scan_ok
        super().tearDown()

    def test_read_operations_never_get_a_footer(self):
        result = {'ok': True}
        self.envoy._attachEffects(result, 'get_op', self.SID)
        self.assertEqual(result, {'ok': True})
        self.assertNotIn(self.SID, self.envoy._effects_state)

    def test_missing_operation_never_gets_a_footer(self):
        result = {'ok': True}
        self.envoy._attachEffects(result, None, self.SID)
        self.assertNotIn('_effects', result)

    def test_non_dict_result_does_not_raise(self):
        self.envoy._attachEffects('not a dict', 'create_op', self.SID)
        self.envoy._attachEffects(None, 'create_op', self.SID)

    def test_existing_effects_key_is_not_clobbered(self):
        result = {'_effects': {'mine': 1}}
        self.envoy._attachEffects(result, 'create_op', self.SID)
        self.assertEqual(result['_effects'], {'mine': 1})

    def test_broken_ext_degrades_silently(self):
        result = {'ok': True}
        type(self.envoy)._attachEffects(
            _BrokenExt(), result, 'create_op', self.SID)
        self.assertNotIn('_effects', result)

    def test_first_write_only_baselines(self):
        # A session's first write must never report the project's
        # PRE-EXISTING errors as newly introduced.
        result = {'ok': True}
        self.envoy._attachEffects(result, 'create_op', self.SID)
        self.assertNotIn('_effects', result)
        self.assertIn(self.SID, self.envoy._effects_state)
        state = self.envoy._effects_state[self.SID]
        self.assertIsInstance(state.get('errors'), set)

    def test_disabled_error_scan_is_skipped_not_fatal(self):
        # The budget valve: once the project-wide scan is disabled for the
        # session, writes still respond -- just without the error half.
        self.envoy._effects_error_scan_ok = False
        result = {'ok': True}
        self.envoy._attachEffects(result, 'create_op', self.SID)
        self.assertNotIn('_effects', result)
        state = self.envoy._effects_state.get(self.SID, {})
        self.assertNotIn('errors', state)

    def test_fps_sample_never_creates_an_operator(self):
        # get_project_performance may create its monitor on first call;
        # the footer must only READ an existing one.
        before = [c.name for c in self.embody.children]
        self.envoy._sampleProjectFps()
        self.assertEqual([c.name for c in self.embody.children], before)


class TestResponseChokepointContract(EmbodyTestCase):

    def setUp(self):
        super().setUp()
        self.envoy = self.embody.ext.Envoy

    def test_send_response_takes_an_optional_operation(self):
        sig = inspect.signature(type(self.envoy)._send_response)
        param = sig.parameters.get('operation')
        self.assertIsNotNone(
            param, '_send_response must accept the operation name')
        self.assertIsNone(param.default,
                          'operation must default to None so existing '
                          'call sites keep working')

    def test_write_operations_set_is_the_footer_gate(self):
        self.assertIn('create_op', _envoy_mod._WRITE_OPERATIONS)
        self.assertNotIn('get_op', _envoy_mod._WRITE_OPERATIONS)


# =====================================================================
# get_focus
# =====================================================================

class TestFocusTargetRule(EmbodyTestCase):
    """The disambiguation rule, pure: "this operator" is the selected /
    current op, NEVER the rollover."""

    def test_single_selection_wins(self):
        self.assertEqual(_read_mod.focus_target(['/a/x'], '/a/y'),
                         ('/a/x', 'selection'))

    def test_current_used_when_selection_is_ambiguous(self):
        self.assertEqual(_read_mod.focus_target(['/a/x', '/a/y'], '/a/y'),
                         ('/a/y', 'current'))

    def test_current_used_when_nothing_selected(self):
        self.assertEqual(_read_mod.focus_target([], '/a/y'),
                         ('/a/y', 'current'))

    def test_ambiguous_multi_selection_without_current(self):
        self.assertEqual(_read_mod.focus_target(['/a/x', '/a/y'], None),
                         (None, None))

    def test_nothing_at_all(self):
        self.assertEqual(_read_mod.focus_target([], None), (None, None))
        self.assertEqual(_read_mod.focus_target(None, None), (None, None))


class TestGetFocus(EmbodyTestCase):

    def setUp(self):
        super().setUp()
        self.envoy = self.embody.ext.Envoy

    def _focus(self):
        return self.envoy._get_focus()

    def test_returns_the_documented_shape(self):
        result = self._focus()
        self.assertNotIn('error', result)
        for key in ('network', 'selected', 'selectedCount', 'current',
                    'rollover', 'target', 'targetSource', 'note'):
            self.assertDictHasKey(result, key)
        self.assertIsInstance(result['selected'], list)

    def test_never_targets_the_rollover_op(self):
        result = self._focus()
        target = result.get('target')
        if target is None:
            return
        self.assertTrue(
            target == result.get('current') or target in result['selected'],
            'target must come from the selection/current op, never rollover')

    def test_target_is_consistent_with_the_reported_selection(self):
        result = self._focus()
        target, source = _read_mod.focus_target(
            result.get('selected'), result.get('current'))
        self.assertEqual(result.get('target'), target)
        self.assertEqual(result.get('targetSource'), source)

    def test_dispatches_through_the_operation_router(self):
        result = self.envoy._execute_operation('get_focus', {})
        self.assertIsInstance(result, dict)
        self.assertNotIn('Unknown operation', str(result.get('error', '')))
