"""
Test suite: AI config generation pipeline in EmbodyExt.

Tests _TEMPLATE_MAP_RULES / _TEMPLATE_MAP_SKILLS integrity, _writeTemplate,
_writeClaudeMd, _writeAgentsMd, _writeClaudeCodeConfig, _writeCursorRules,
_writeCopilotInstructions, _writeWindsurfRules, _writeGeminiConfig,
_clientFilesMissing, and _upgradeEnvoy condition logic.
"""

import tempfile
import shutil
from pathlib import Path

runner_mod = op.unit_tests.op('TestRunnerExt').module
EmbodyTestCase = runner_mod.EmbodyTestCase


class TestClaudeConfig(EmbodyTestCase):

	MARKER = '<!-- Generated by Embody/Envoy'

	def setUp(self):
		super().setUp()
		self._temp_dir = Path(tempfile.mkdtemp(prefix='ai_config_test_'))

	def tearDown(self):
		try:
			shutil.rmtree(self._temp_dir)
		except Exception:
			pass
		super().tearDown()

	# ------------------------------------------------------------------
	# Group A: Template DAT integrity
	# ------------------------------------------------------------------

	def unstamped(self, text):
		"""Generated content with the marker's hash removed.

		Generated files now carry sha:<hash> in their marker line so
		they can prove on their own whether they are still Embody's --
		the sidecar that used to do that never survived a clone.
		Content assertions compare against the template, so they
		strip the stamp first."""
		return op.Embody.op('embody_git').module.strip_stamp(
			self.embody_ext, text)

	def test_A00_no_absolute_paths_in_panel_watchers(self):
		"""No panelexecuteDAT inside Embody may watch ABSOLUTE op paths.

		Absolute paths only resolve at the dev project's install location
		(/embody/Embody); in a user project the tox lands at /Embody and the
		watcher silently resolves to nothing -- every wizard/UI click dies
		with no error. This shipped broken in v6.0.74-87 (the setup wizard's
		Next button did nothing in user projects) because the dev project
		masked it. Parameter op-paths must be relative, per rules/td-python.md.
		"""
		offenders = []
		for d in self.embody_ext.my.findChildren(type=panelexecuteDAT, maxDepth=8):
			raw = d.par.panels.val
			if any(tok.startswith('/') for tok in raw.split()):
				offenders.append(d.path)
		self.assertListEqual(offenders, [])

	def test_A01_rules_map_has_expected_entries(self):
		"""_TEMPLATE_MAP_RULES should have at least 3 rule entries."""
		self.assertGreaterEqual(len(self.embody_ext._TEMPLATE_MAP_RULES), 3)

	def test_A02_skills_map_has_15_entries(self):
		"""_TEMPLATE_MAP_SKILLS should have exactly 15 skill entries.

		The count is deliberately in the name: this is a tripwire, so
		shipping a new skill to user projects has to be a conscious act
		rather than a silent addition. 14 -> 15 when merge-divergent-tox
		was wired into the template system (3d2d2c3), which landed
		WITHOUT updating this number -- the suite has been red on dev
		since that commit.
		"""
		self.assertLen(self.embody_ext._TEMPLATE_MAP_SKILLS, 15)

	def test_A03_templates_comp_exists(self):
		"""The templates COMP should exist inside Embody."""
		templates_comp = self.embody_ext.my.op('templates')
		self.assertIsNotNone(templates_comp,
			'templates COMP not found inside Embody')

	def test_A04_all_rule_dats_exist(self):
		"""Every DAT named in _TEMPLATE_MAP_RULES should exist in templates COMP."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP_RULES:
			dat = templates_comp.op(dat_name)
			self.assertIsNotNone(dat,
				f'Rule DAT {dat_name!r} missing from templates COMP')

	def test_A05_all_skill_dats_exist(self):
		"""Every DAT named in _TEMPLATE_MAP_SKILLS should exist in templates COMP."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP_SKILLS:
			dat = templates_comp.op(dat_name)
			self.assertIsNotNone(dat,
				f'Skill DAT {dat_name!r} missing from templates COMP')

	def test_A06_all_rule_dats_have_content(self):
		"""Every rule template DAT should have non-empty text content."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP_RULES:
			dat = templates_comp.op(dat_name)
			self.assertTrue(dat.text,
				f'Rule DAT {dat_name!r} has empty .text')

	def test_A07_all_skill_dats_have_content(self):
		"""Every skill template DAT should have non-empty text content."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP_SKILLS:
			dat = templates_comp.op(dat_name)
			self.assertTrue(dat.text,
				f'Skill DAT {dat_name!r} has empty .text')

	def test_A08_all_rule_dats_have_marker(self):
		"""Every rule template DAT should contain the Embody/Envoy marker."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP_RULES:
			dat = templates_comp.op(dat_name)
			self.assertIn(self.MARKER, dat.text,
				f'Rule DAT {dat_name!r} missing marker')

	def test_A09_all_skill_dats_have_marker(self):
		"""Every skill template DAT should contain the Embody/Envoy marker."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP_SKILLS:
			dat = templates_comp.op(dat_name)
			self.assertIn(self.MARKER, dat.text,
				f'Skill DAT {dat_name!r} missing marker')

	def test_A10_text_claude_dat_exists(self):
		"""The text_claude DAT should exist in the templates COMP."""
		dat = self.embody_ext.my.op('templates/text_claude')
		self.assertIsNotNone(dat, 'text_claude DAT not found')

	def test_A11_text_claude_dat_has_marker(self):
		"""text_claude DAT content should contain the Embody/Envoy marker."""
		dat = self.embody_ext.my.op('templates/text_claude')
		self.assertIn(self.MARKER, dat.text,
			'text_claude DAT missing marker')

	def test_A12_text_agents_md_dat_exists(self):
		"""The text_agents_md DAT should exist in the templates COMP."""
		templates_comp = self.embody_ext.my.op('templates')
		dat = templates_comp.op('text_agents_md')
		self.assertIsNotNone(dat, 'text_agents_md DAT not found in templates COMP')

	def test_A13_text_agents_md_has_content(self):
		"""text_agents_md DAT should have non-empty content."""
		templates_comp = self.embody_ext.my.op('templates')
		dat = templates_comp.op('text_agents_md')
		self.assertTrue(dat.text, 'text_agents_md DAT has empty .text')

	def test_A14_text_agents_md_has_marker(self):
		"""text_agents_md DAT content should contain the Embody/Envoy marker."""
		templates_comp = self.embody_ext.my.op('templates')
		dat = templates_comp.op('text_agents_md')
		self.assertIn(self.MARKER, dat.text,
			'text_agents_md DAT missing marker')

	def test_A15_rule_slugs_are_simple_strings(self):
		"""_TEMPLATE_MAP_RULES values should be simple slugs (no path separators)."""
		for dat_name, slug in self.embody_ext._TEMPLATE_MAP_RULES.items():
			self.assertNotIn('/', slug,
				f'{dat_name}: slug {slug!r} should not contain slashes')
			self.assertNotIn('\\', slug,
				f'{dat_name}: slug {slug!r} should not contain backslashes')

	def test_A16_skill_slugs_are_simple_strings(self):
		"""_TEMPLATE_MAP_SKILLS values should be simple slugs (no path separators)."""
		for dat_name, slug in self.embody_ext._TEMPLATE_MAP_SKILLS.items():
			self.assertNotIn('/', slug,
				f'{dat_name}: slug {slug!r} should not contain slashes')

	# ------------------------------------------------------------------
	# Group B: _writeTemplate() behavior
	# ------------------------------------------------------------------

	def test_B01_creates_file_when_missing(self):
		"""_writeTemplate should create the file and return True when missing."""
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'test/new.md', 'content here')
		self.assertTrue(result)
		self.assertTrue((self._temp_dir / 'test' / 'new.md').exists())

	def test_B02_created_content_matches_input(self):
		"""Written file content should match the input exactly."""
		content = '# Title\n\nSome content with unicode: \u00e9\u00e8\u00ea\n'
		self.embody_ext._writeTemplate(
			self._temp_dir, 'exact.md', content)
		written = (self._temp_dir / 'exact.md').read_text(encoding='utf-8')
		self.assertEqual(written, content)

	def test_B03_overwrites_file_with_marker(self):
		"""_writeTemplate should overwrite a file that contains the marker."""
		target = self._temp_dir / 'marked.md'
		target.write_text(self.MARKER + ' old content', encoding='utf-8')
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'marked.md', 'new content')
		self.assertTrue(result)
		self.assertEqual(
			target.read_text(encoding='utf-8'), 'new content')

	def test_B04_skips_file_without_marker(self):
		"""_writeTemplate should skip a file that lacks the marker."""
		target = self._temp_dir / 'user.md'
		target.write_text('User wrote this', encoding='utf-8')
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'user.md', 'attempted overwrite')
		self.assertFalse(result)
		self.assertEqual(
			target.read_text(encoding='utf-8'), 'User wrote this')

	def test_B05_creates_parent_directories(self):
		"""_writeTemplate should create parent directories as needed."""
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'a/b/c/deep.md', 'deep content')
		self.assertTrue(result)
		self.assertTrue((self._temp_dir / 'a' / 'b' / 'c' / 'deep.md').exists())

	def test_B06_returns_true_on_overwrite(self):
		"""_writeTemplate return value should be True when overwriting."""
		target = self._temp_dir / 'retval.md'
		target.write_text(self.MARKER + ' v1', encoding='utf-8')
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'retval.md', self.MARKER + ' v2')
		self.assertTrue(result)

	def test_B07_empty_content_still_writes(self):
		"""_writeTemplate should write even when content is empty string."""
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'empty.md', '')
		self.assertTrue(result)
		self.assertTrue((self._temp_dir / 'empty.md').exists())
		self.assertEqual(
			(self._temp_dir / 'empty.md').read_text(encoding='utf-8'), '')

	def test_B08_preserves_user_edits_to_generated_file(self):
		"""A generated file edited by the user (marker kept) is preserved on rewrite."""
		# First generation records the file's hash in the sidecar manifest.
		self.embody_ext._writeTemplate(
			self._temp_dir, 'gen.md', self.MARKER + ' v1 -->\nbody\n')
		target = self._temp_dir / 'gen.md'
		# User edits the body but leaves the marker in place.
		target.write_text(self.MARKER + ' v1 -->\nbody EDITED\n', encoding='utf-8')
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'gen.md', self.MARKER + ' v2 -->\nnew body\n')
		self.assertFalse(result, 'should skip a user-edited generated file')
		self.assertIn('EDITED', target.read_text(encoding='utf-8'),
			'user edit should be preserved')

	def test_B09_regenerates_untouched_generated_file(self):
		"""A generated file untouched since generation is regenerated on rewrite."""
		self.embody_ext._writeTemplate(
			self._temp_dir, 'gen.md', self.MARKER + ' v1 -->\nbody\n')
		new = self.MARKER + ' v2 -->\nnew body\n'
		result = self.embody_ext._writeTemplate(self._temp_dir, 'gen.md', new)
		self.assertTrue(result, 'should regenerate an untouched generated file')
		self.assertEqual(
			self.unstamped(
				(self._temp_dir / 'gen.md').read_text(encoding='utf-8')),
			new)

	def test_B10_legacy_marker_without_tracked_hash_regenerates(self):
		"""A pre-existing marker file with no tracked hash (legacy) is regenerated."""
		target = self._temp_dir / 'legacy.md'
		target.write_text(self.MARKER + ' v5 legacy -->\nold\n', encoding='utf-8')
		# No manifest entry exists (simulates a file from before hash tracking).
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'legacy.md', self.MARKER + ' v6 -->\nnew\n')
		self.assertTrue(result,
			'legacy marker file with no tracked hash should regenerate')

	def test_B11_generated_content_differs_only_by_its_stamp(self):
		"""Generated files now carry their own hash, by design.

		This test previously asserted the opposite -- that generated
		content is byte-identical to its template, with the hash kept
		in a sidecar. That sidecar lives in gitignored .embody/, so it
		never reached a second machine: a clone saw a marker with no
		record, read it as legacy, and regenerated over edits a
		teammate had committed. The stamp travels inside the file.
		What still holds: the marker line is the ONLY thing that
		differs, so the body is byte-exact."""
		content = self.MARKER + ' v1 -->\n# Rules\nexact body\n'
		self.embody_ext._writeTemplate(self._temp_dir, 'exact2.md', content)
		written = (self._temp_dir / 'exact2.md').read_text(encoding='utf-8')
		self.assertNotEqual(written, content, 'the file should be stamped')
		self.assertEqual(self.unstamped(written), content,
			'the stamp must be the only difference from the template')
		self.assertEqual(written.split('\n')[1:], content.split('\n')[1:],
			'the body below the marker must be byte-exact')

	def test_B12_manifest_records_generated_file(self):
		"""Generating a file records its hash in the sidecar manifest."""
		self.embody_ext._writeTemplate(
			self._temp_dir, 'gen.md', self.MARKER + ' v1 -->\nbody\n')
		manifest = self._temp_dir / '.embody' / 'generated-hashes.json'
		self.assertTrue(manifest.exists(), 'hash manifest should be written')
		import json as _json
		data = _json.loads(manifest.read_text(encoding='utf-8'))
		self.assertIn('gen.md', data, 'manifest should record the generated file')

	# ------------------------------------------------------------------
	# Group C: _writeClaudeMd() behavior
	# ------------------------------------------------------------------

	def test_C01_creates_claude_md_when_missing(self):
		"""_writeClaudeMd should create CLAUDE.md when it does not exist."""
		result = self.embody_ext._writeClaudeMd(self._temp_dir)
		self.assertIsNotNone(result)
		self.assertTrue((self._temp_dir / 'CLAUDE.md').exists())

	def test_C02_created_claude_md_has_template_content(self):
		"""Created CLAUDE.md should contain the text_claude DAT content."""
		self.embody_ext._writeClaudeMd(self._temp_dir)
		expected = self.embody_ext.my.op('templates/text_claude').text
		actual = (self._temp_dir / 'CLAUDE.md').read_text(encoding='utf-8')
		self.assertEqual(self.unstamped(actual), expected)

	def test_C03_overwrites_claude_md_with_marker(self):
		"""_writeClaudeMd should overwrite CLAUDE.md when it has the marker."""
		existing = self._temp_dir / 'CLAUDE.md'
		existing.write_text(self.MARKER + ' old version', encoding='utf-8')
		result = self.embody_ext._writeClaudeMd(self._temp_dir)
		self.assertEqual(result, existing)
		updated = existing.read_text(encoding='utf-8')
		expected = self.embody_ext.my.op('templates/text_claude').text
		self.assertEqual(self.unstamped(updated), expected)

	def test_C04_merges_into_a_user_authored_claude_md(self):
		"""A CLAUDE.md the user wrote gets Embody's block merged in.

		It used to divert to an ENVOY.md sidecar, which preserved the file but
		delivered the guidance nowhere -- nothing imports ENVOY.md and Claude
		Code does not auto-load it."""
		user_claude = self._temp_dir / 'CLAUDE.md'
		user_claude.write_text('My own claude config\n', encoding='utf-8')
		result = self.embody_ext._writeClaudeMd(self._temp_dir)
		self.assertEqual(result, user_claude,
			'the guidance belongs in the file Claude Code actually loads')
		body = user_claude.read_text(encoding='utf-8')
		self.assertIn('My own claude config', body,
			'their content must survive the merge')
		git = op.Embody.op('embody_git').module
		self.assertIn(git.AGENTS_BEGIN, body)
		self.assertEqual(body.count(git.AGENTS_BEGIN), 1)
		self.assertFalse((self._temp_dir / 'ENVOY.md').exists(),
			'the dead-end sidecar must no longer be written')

	def test_C05_the_merged_block_carries_the_template(self):
		"""Merging must deliver the same content the whole-file path does."""
		(self._temp_dir / 'CLAUDE.md').write_text('user content\n', encoding='utf-8')
		self.embody_ext._writeClaudeMd(self._temp_dir)
		body = (self._temp_dir / 'CLAUDE.md').read_text(encoding='utf-8')
		expected = self.embody_ext.my.op('templates/text_claude').text
		self.assertIn(expected.strip().split('\n')[-1].strip(), body,
			'the tail of the template must be inside the merged block')

	def test_C05b_merged_file_carries_a_human_readable_label(self):
		"""The BEGIN/END delimiters are HTML comments -- invisible in every
		rendered view. A reader needs prose telling them which half is theirs
		and where their own edits belong."""
		(self._temp_dir / 'CLAUDE.md').write_text('mine\n', encoding='utf-8')
		self.embody_ext._writeClaudeMd(self._temp_dir)
		body = (self._temp_dir / 'CLAUDE.md').read_text(encoding='utf-8')
		self.assertIn('## Embody / Envoy', body,
			'the section needs a VISIBLE heading, not just a comment')
		self.assertIn('OUTSIDE this section', body,
			'it must say where the user should put their own edits')
		admin = op.Embody.op('embody_admin').module
		self.assertEqual(
			admin.strip_md_section(self.embody_ext, body).strip(),
			'mine',
			'the label rides INSIDE the block, so uninstall takes it back too')

	def test_C06_returns_claude_md_path_on_create(self):
		"""_writeClaudeMd should return the CLAUDE.md path on fresh create."""
		result = self.embody_ext._writeClaudeMd(self._temp_dir)
		self.assertEqual(result, self._temp_dir / 'CLAUDE.md')

	# ------------------------------------------------------------------
	# Group D: _writeClaudeCodeConfig() end-to-end
	# ------------------------------------------------------------------

	def _run_claude_pipeline(self):
		"""Helper: run the Claude Code config pipeline against self._temp_dir."""
		self.embody_ext._writeClaudeCodeConfig(self._temp_dir)

	def test_D01_all_template_files_created(self):
		"""Claude pipeline should create CLAUDE.md + all rules + all skills."""
		self._run_claude_pipeline()
		self.assertTrue((self._temp_dir / 'CLAUDE.md').exists())
		for slug in self.embody_ext._TEMPLATE_MAP_RULES.values():
			full = self._temp_dir / '.claude' / 'rules' / f'{slug}.md'
			self.assertTrue(full.exists(), f'Rule file missing: {slug}.md')
		for slug in self.embody_ext._TEMPLATE_MAP_SKILLS.values():
			full = self._temp_dir / '.claude' / 'skills' / slug / 'SKILL.md'
			self.assertTrue(full.exists(), f'Skill file missing: {slug}/SKILL.md')

	def test_D02_file_content_matches_dats(self):
		"""Each rule file content should match its source DAT (frontmatter stripped for CC)."""
		self._run_claude_pipeline()
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name, slug in self.embody_ext._TEMPLATE_MAP_RULES.items():
			dat = templates_comp.op(dat_name)
			full = self._temp_dir / '.claude' / 'rules' / f'{slug}.md'
			actual = self.unstamped(full.read_text(encoding='utf-8'))
			# Claude Code rules have YAML frontmatter stripped by _writeClaudeCodeConfig
			expected = self.embody_ext._stripFrontmatter(dat.text)
			self.assertEqual(actual, expected,
				f'Content mismatch for rules/{slug}.md')

	def test_D03_directory_structure_correct(self):
		"""Claude pipeline should create .claude/rules/ and .claude/skills/ subdirs."""
		self._run_claude_pipeline()
		self.assertTrue((self._temp_dir / '.claude' / 'rules').is_dir())
		self.assertTrue((self._temp_dir / '.claude' / 'skills').is_dir())

	def test_D04_rules_files_count(self):
		"""Rule files count should match _TEMPLATE_MAP_RULES."""
		self._run_claude_pipeline()
		rules_dir = self._temp_dir / '.claude' / 'rules'
		rule_files = list(rules_dir.glob('*.md'))
		self.assertLen(rule_files, len(self.embody_ext._TEMPLATE_MAP_RULES))

	def test_D05_skills_directories_count(self):
		"""One skill directory per _TEMPLATE_MAP_SKILLS entry in .claude/skills/."""
		self._run_claude_pipeline()
		skills_dir = self._temp_dir / '.claude' / 'skills'
		skill_dirs = [d for d in skills_dir.iterdir() if d.is_dir()]
		self.assertLen(skill_dirs, len(self.embody_ext._TEMPLATE_MAP_SKILLS))

	def test_D06_idempotent_rerun(self):
		"""Running the Claude pipeline twice should produce identical files."""
		self._run_claude_pipeline()
		first_run = {}
		for slug in self.embody_ext._TEMPLATE_MAP_RULES.values():
			p = self._temp_dir / '.claude' / 'rules' / f'{slug}.md'
			first_run[slug] = p.read_text(encoding='utf-8')
		self._run_claude_pipeline()
		for slug in self.embody_ext._TEMPLATE_MAP_RULES.values():
			p = self._temp_dir / '.claude' / 'rules' / f'{slug}.md'
			self.assertEqual(first_run[slug], p.read_text(encoding='utf-8'),
				f'Content changed on second run for {slug}.md')

	# ------------------------------------------------------------------
	# Group Da: _writeAgentsMd()
	# ------------------------------------------------------------------

	def test_Da01_agents_md_created(self):
		"""_writeAgentsMd should create AGENTS.md."""
		self.embody_ext._writeAgentsMd(self._temp_dir)
		self.assertTrue((self._temp_dir / 'AGENTS.md').exists())

	def test_Da02_agents_md_has_marker(self):
		"""Generated AGENTS.md should contain the Embody/Envoy marker."""
		self.embody_ext._writeAgentsMd(self._temp_dir)
		content = (self._temp_dir / 'AGENTS.md').read_text(encoding='utf-8')
		self.assertIn(self.MARKER, content)

	def test_Da03_agents_md_has_content(self):
		"""Generated AGENTS.md should have substantial content (> 100 chars)."""
		self.embody_ext._writeAgentsMd(self._temp_dir)
		content = (self._temp_dir / 'AGENTS.md').read_text(encoding='utf-8')
		self.assertGreater(len(content), 100)

	def test_Da04_agents_md_idempotent(self):
		"""Running _writeAgentsMd twice should produce identical output."""
		self.embody_ext._writeAgentsMd(self._temp_dir)
		first = (self._temp_dir / 'AGENTS.md').read_text(encoding='utf-8')
		self.embody_ext._writeAgentsMd(self._temp_dir)
		second = (self._temp_dir / 'AGENTS.md').read_text(encoding='utf-8')
		self.assertEqual(first, second)

	# ------------------------------------------------------------------
	# Group Db: _writeCursorRules()
	# ------------------------------------------------------------------

	def test_Db01_cursor_rules_files_created(self):
		"""_writeCursorRules should create .mdc files for each rule."""
		self.embody_ext._writeCursorRules(self._temp_dir)
		cursor_dir = self._temp_dir / '.cursor' / 'rules'
		self.assertTrue(cursor_dir.is_dir())
		mdc_files = list(cursor_dir.glob('*.mdc'))
		self.assertLen(mdc_files, len(self.embody_ext._TEMPLATE_MAP_RULES))

	def test_Db02_cursor_files_have_yaml_frontmatter(self):
		"""Each .mdc file should start with YAML frontmatter (---)."""
		self.embody_ext._writeCursorRules(self._temp_dir)
		cursor_dir = self._temp_dir / '.cursor' / 'rules'
		for mdc_file in cursor_dir.glob('*.mdc'):
			content = mdc_file.read_text(encoding='utf-8')
			self.assertTrue(content.startswith('---\n'),
				f'{mdc_file.name}: missing YAML frontmatter')

	def test_Db03_cursor_files_have_always_apply(self):
		"""Each .mdc file should contain alwaysApply: true."""
		self.embody_ext._writeCursorRules(self._temp_dir)
		cursor_dir = self._temp_dir / '.cursor' / 'rules'
		for mdc_file in cursor_dir.glob('*.mdc'):
			content = mdc_file.read_text(encoding='utf-8')
			self.assertIn('alwaysApply: true', content,
				f'{mdc_file.name}: missing alwaysApply: true')

	def test_Db04_cursor_files_have_description(self):
		"""Each .mdc file should contain a description field."""
		self.embody_ext._writeCursorRules(self._temp_dir)
		cursor_dir = self._temp_dir / '.cursor' / 'rules'
		for mdc_file in cursor_dir.glob('*.mdc'):
			content = mdc_file.read_text(encoding='utf-8')
			self.assertIn('description:', content,
				f'{mdc_file.name}: missing description field')

	def test_Db05_cursor_files_have_marker(self):
		"""Each .mdc file should contain the Embody/Envoy marker."""
		self.embody_ext._writeCursorRules(self._temp_dir)
		cursor_dir = self._temp_dir / '.cursor' / 'rules'
		for mdc_file in cursor_dir.glob('*.mdc'):
			content = mdc_file.read_text(encoding='utf-8')
			self.assertIn(self.MARKER, content,
				f'{mdc_file.name}: missing generated-by marker')

	def test_Db06_cursor_files_have_single_frontmatter_block(self):
		"""Each .mdc file should have exactly one YAML frontmatter block (no doubling)."""
		self.embody_ext._writeCursorRules(self._temp_dir)
		cursor_dir = self._temp_dir / '.cursor' / 'rules'
		for mdc_file in cursor_dir.glob('*.mdc'):
			content = mdc_file.read_text(encoding='utf-8')
			# Count occurrences of '---' at line start
			fence_count = sum(1 for line in content.splitlines() if line.strip() == '---')
			self.assertEqual(fence_count, 2,
				f'{mdc_file.name}: expected exactly 2 --- fences, got {fence_count}')

	# ------------------------------------------------------------------
	# Group Dc: _writeCopilotInstructions()
	# ------------------------------------------------------------------

	def test_Dc01_copilot_combined_file_created(self):
		"""_writeCopilotInstructions should create .github/copilot-instructions.md."""
		self.embody_ext._writeCopilotInstructions(self._temp_dir)
		combined = self._temp_dir / '.github' / 'copilot-instructions.md'
		self.assertTrue(combined.exists())

	def test_Dc02_copilot_individual_files_created(self):
		"""_writeCopilotInstructions should create per-rule .instructions.md files."""
		self.embody_ext._writeCopilotInstructions(self._temp_dir)
		instructions_dir = self._temp_dir / '.github' / 'instructions'
		self.assertTrue(instructions_dir.is_dir())
		files = list(instructions_dir.glob('*.instructions.md'))
		self.assertLen(files, len(self.embody_ext._TEMPLATE_MAP_RULES))

	def test_Dc03_copilot_combined_has_marker(self):
		"""Combined copilot-instructions.md should have the generated-by marker."""
		self.embody_ext._writeCopilotInstructions(self._temp_dir)
		content = (self._temp_dir / '.github' / 'copilot-instructions.md').read_text(encoding='utf-8')
		self.assertIn(self.MARKER, content)

	def test_Dc04_copilot_individual_files_have_apply_to(self):
		"""Each .instructions.md should contain applyTo frontmatter."""
		self.embody_ext._writeCopilotInstructions(self._temp_dir)
		instructions_dir = self._temp_dir / '.github' / 'instructions'
		for f in instructions_dir.glob('*.instructions.md'):
			content = f.read_text(encoding='utf-8')
			self.assertIn('applyTo:', content,
				f'{f.name}: missing applyTo frontmatter')

	def test_Dc05_copilot_individual_files_have_marker(self):
		"""Each .instructions.md should have the generated-by marker."""
		self.embody_ext._writeCopilotInstructions(self._temp_dir)
		instructions_dir = self._temp_dir / '.github' / 'instructions'
		for f in instructions_dir.glob('*.instructions.md'):
			content = f.read_text(encoding='utf-8')
			self.assertIn(self.MARKER, content,
				f'{f.name}: missing generated-by marker')

	# ------------------------------------------------------------------
	# Group Dd: _writeWindsurfRules()
	# ------------------------------------------------------------------

	def test_Dd01_windsurf_rules_files_created(self):
		"""_writeWindsurfRules should create .windsurf/rules/*.md files."""
		self.embody_ext._writeWindsurfRules(self._temp_dir)
		windsurf_dir = self._temp_dir / '.windsurf' / 'rules'
		self.assertTrue(windsurf_dir.is_dir())
		md_files = list(windsurf_dir.glob('*.md'))
		self.assertLen(md_files, len(self.embody_ext._TEMPLATE_MAP_RULES))

	def test_Dd02_windsurf_files_have_no_cursor_or_copilot_metadata(self):
		"""Windsurf rule files should not contain alwaysApply or applyTo directives."""
		self.embody_ext._writeWindsurfRules(self._temp_dir)
		windsurf_dir = self._temp_dir / '.windsurf' / 'rules'
		for f in windsurf_dir.glob('*.md'):
			content = f.read_text(encoding='utf-8')
			self.assertNotIn('alwaysApply:', content,
				f'{f.name}: should not contain Cursor alwaysApply directive')
			self.assertNotIn('applyTo:', content,
				f'{f.name}: should not contain Copilot applyTo directive')

	def test_Dd03_windsurf_files_have_marker(self):
		"""Each Windsurf rule file should contain the Embody/Envoy marker."""
		self.embody_ext._writeWindsurfRules(self._temp_dir)
		windsurf_dir = self._temp_dir / '.windsurf' / 'rules'
		for f in windsurf_dir.glob('*.md'):
			content = f.read_text(encoding='utf-8')
			self.assertIn(self.MARKER, content,
				f'{f.name}: missing generated-by marker')

	def test_Dd04_windsurf_content_matches_rule_dats(self):
		"""Windsurf rule file content should match the source DAT content."""
		self.embody_ext._writeWindsurfRules(self._temp_dir)
		templates_comp = self.embody_ext.my.op('templates')
		windsurf_dir = self._temp_dir / '.windsurf' / 'rules'
		for dat_name, slug in self.embody_ext._TEMPLATE_MAP_RULES.items():
			dat = templates_comp.op(dat_name)
			f = windsurf_dir / f'{slug}.md'
			actual = self.unstamped(f.read_text(encoding='utf-8'))
			self.assertEqual(actual, dat.text,
				f'Content mismatch for {slug}.md')

	# ------------------------------------------------------------------
	# Group Dg: _writeGeminiConfig()
	# ------------------------------------------------------------------

	def test_Dg01_gemini_md_created(self):
		"""_writeGeminiConfig should create GEMINI.md."""
		self.embody_ext._writeGeminiConfig(self._temp_dir)
		self.assertTrue((self._temp_dir / 'GEMINI.md').exists())

	def test_Dg02_gemini_md_has_marker(self):
		"""Generated GEMINI.md should contain the Embody/Envoy marker."""
		self.embody_ext._writeGeminiConfig(self._temp_dir)
		content = (self._temp_dir / 'GEMINI.md').read_text(encoding='utf-8')
		self.assertIn(self.MARKER, content)

	def test_Dg03_gemini_md_imports_agents(self):
		"""GEMINI.md should import AGENTS.md via Gemini @import syntax (no duplication)."""
		self.embody_ext._writeGeminiConfig(self._temp_dir)
		content = (self._temp_dir / 'GEMINI.md').read_text(encoding='utf-8')
		self.assertIn('@AGENTS.md', content)

	def test_Dg04_gemini_md_idempotent(self):
		"""Running _writeGeminiConfig twice should produce identical output."""
		self.embody_ext._writeGeminiConfig(self._temp_dir)
		first = (self._temp_dir / 'GEMINI.md').read_text(encoding='utf-8')
		self.embody_ext._writeGeminiConfig(self._temp_dir)
		second = (self._temp_dir / 'GEMINI.md').read_text(encoding='utf-8')
		self.assertEqual(first, second)

	# ------------------------------------------------------------------
	# Group E: _clientFilesMissing() logic
	# ------------------------------------------------------------------

	def test_E01_claudecode_missing_when_no_files(self):
		"""claudecode: missing when neither CLAUDE.md nor .claude/rules exist."""
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'claudecode'))

	def test_E02_claudecode_not_missing_when_all_present(self):
		"""claudecode: not missing when CLAUDE.md and .claude/rules both exist."""
		(self._temp_dir / 'CLAUDE.md').write_text('content', encoding='utf-8')
		(self._temp_dir / '.claude' / 'rules').mkdir(parents=True)
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'claudecode'))

	def test_E03_claudecode_missing_when_rules_absent(self):
		"""claudecode: missing when .claude/rules absent even with CLAUDE.md."""
		(self._temp_dir / 'CLAUDE.md').write_text('content', encoding='utf-8')
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'claudecode'))

	def test_E04_claudecode_not_missing_with_envoy_md(self):
		"""claudecode: not missing when ENVOY.md and .claude/rules both exist."""
		(self._temp_dir / 'ENVOY.md').write_text('content', encoding='utf-8')
		(self._temp_dir / '.claude' / 'rules').mkdir(parents=True)
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'claudecode'))

	def test_E05_cursor_missing_when_no_files(self):
		"""cursor: missing when .cursor/rules does not exist."""
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'cursor'))

	def test_E06_cursor_not_missing_when_rules_and_mcp_exist(self):
		"""cursor: not missing once BOTH its rules and mcp.json exist."""
		(self._temp_dir / '.cursor' / 'rules').mkdir(parents=True)
		(self._temp_dir / '.cursor' / 'mcp.json').write_text(
			'{}', encoding='utf-8')
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'cursor'))

	def test_E06b_cursor_missing_when_only_rules_exist(self):
		"""cursor: rules alone are NOT enough -- Cursor reads its own
		MCP config, and without .cursor/mcp.json the client has rules
		but no Envoy connection at all."""
		(self._temp_dir / '.cursor' / 'rules').mkdir(parents=True)
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'cursor'))

	def test_E07_copilot_missing_when_no_files(self):
		"""copilot: missing when .github/copilot-instructions.md does not exist."""
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'copilot'))

	def test_E08_copilot_not_missing_when_file_exists(self):
		"""copilot: not missing when .github/copilot-instructions.md exists."""
		(self._temp_dir / '.github').mkdir(parents=True)
		(self._temp_dir / '.github' / 'copilot-instructions.md').write_text('x', encoding='utf-8')
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'copilot'))

	def test_E09_windsurf_missing_when_no_files(self):
		"""windsurf: missing when .windsurf/rules does not exist."""
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'windsurf'))

	def test_E10_windsurf_not_missing_when_rules_exist(self):
		"""windsurf: not missing when .windsurf/rules exists."""
		(self._temp_dir / '.windsurf' / 'rules').mkdir(parents=True)
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'windsurf'))

	def test_E11_none_never_missing(self):
		"""none client: _clientFilesMissing always returns False."""
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'none'))

	def test_E12_unknown_client_never_missing(self):
		"""Unknown client string: _clientFilesMissing returns False (safe default)."""
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'unknowntool'))

	def test_E13_gemini_missing_when_no_file(self):
		"""gemini: missing when GEMINI.md does not exist."""
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'gemini'))

	def test_E14_gemini_not_missing_when_doc_and_mcp_exist(self):
		"""gemini: needs GEMINI.md AND .gemini/settings.json."""
		(self._temp_dir / 'GEMINI.md').write_text('x', encoding='utf-8')
		(self._temp_dir / '.gemini').mkdir(parents=True)
		(self._temp_dir / '.gemini' / 'settings.json').write_text(
			'{}', encoding='utf-8')
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'gemini'))

	def test_E15_codex_missing_without_project_config(self):
		"""codex: reads a project-level .codex/config.toml, so it is
		'missing' without one -- it used to be absent from the probe
		table entirely and silently defaulted to "nothing missing"."""
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'codex'))

	def test_E15b_codex_not_missing_with_project_config(self):
		"""codex: satisfied once .codex/config.toml exists."""
		(self._temp_dir / '.codex').mkdir(parents=True)
		(self._temp_dir / '.codex' / 'config.toml').write_text(
			'', encoding='utf-8')
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'codex'))

	def test_E16_vscode_missing_without_mcp_json(self):
		"""vscode: has a probe at all now -- it was absent from the old
		table, so restore-on-open could never fire for it."""
		self.assertTrue(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'vscode'))

	def test_E17_windsurf_not_missing_on_rules_alone(self):
		"""windsurf: rules alone suffice -- its MCP config is user-global
		(~/.codeium/...), which Embody deliberately never writes, so it
		must not count toward "missing"."""
		(self._temp_dir / '.windsurf' / 'rules').mkdir(parents=True)
		self.assertFalse(
			self.embody_ext._clientFilesMissing(self._temp_dir, 'windsurf'))

	# ------------------------------------------------------------------
	# Group F: _findProjectRoot()
	# ------------------------------------------------------------------

	def test_F01_returns_path_object(self):
		"""_findProjectRoot should return a Path object."""
		result = self.embody_ext._findProjectRoot()
		self.assertIsInstance(result, Path)

	def test_F02_returned_path_exists(self):
		"""_findProjectRoot should return an existing directory."""
		result = self.embody_ext._findProjectRoot()
		self.assertTrue(result.exists())
		self.assertTrue(result.is_dir())

	def test_F03_returned_path_contains_git(self):
		"""_findProjectRoot should find the .git directory."""
		result = self.embody_ext._findProjectRoot()
		self.assertTrue((result / '.git').exists(),
			f'No .git found at {result}')

	def _deadDrive(self):
		"""A drive letter that does not exist on this machine, or skip."""
		for letter in 'QWXYZKJVUT':
			if not Path(f'{letter}:/').exists():
				return f'{letter}:/'
		self.skipTest('every probe drive letter exists on this machine')

	def test_F04_stale_stored_git_root_heals(self):
		"""A stored _git_root on a missing drive is dropped and recomputed.

		The stored value travels inside a saved .toe (pre-save scrub only
		runs when Embody's callbacks fire), so a cloned project can carry
		another machine's D:\\ root -- which made every .embody write fail
		with WinError 3 and kept Convoy off (field 2026-08-25).
		"""
		dead = self._deadDrive()
		comp = self.embody_ext.my
		orig = comp.fetch('_git_root', None, search=False)
		try:
			comp.store('_git_root', dead + 'ghost/repo')
			result = self.embody_ext._rootForMode('gitroot')
			self.assertTrue(result.exists(),
				f'healed root {result} should exist')
			self.assertIsNone(comp.fetch('_git_root', None, search=False),
				'stale stored _git_root should be unstored by the heal')
		finally:
			comp.unstore('_git_root')
			if orig is not None:
				comp.store('_git_root', str(orig))

	def test_F05_custom_root_on_missing_drive_falls_back(self):
		"""A custom root on a missing drive falls back to the project folder."""
		dead = self._deadDrive()
		result = self.embody_ext._rootForMode(
			'custom', custom_path=dead + 'nowhere')
		self.assertEqual(result, Path(project.folder).resolve())

	def test_F06_custom_root_nonexistent_folder_on_live_drive_kept(self):
		"""A not-yet-created custom folder on a live drive is honored --
		writers mkdir it; only a missing DRIVE triggers the fallback."""
		target = self._temp_dir / 'not_created_yet'
		result = self.embody_ext._rootForMode(
			'custom', custom_path=str(target))
		self.assertEqual(result, target.resolve())

	# ------------------------------------------------------------------
	# Group G: Template drift detection (Claude Code files vs repo)
	# ------------------------------------------------------------------

	# Templates that intentionally differ from repo .claude/ files.
	# mcp-safety: repo has detailed dev version, template has short user version.
	_DRIFT_EXCLUSIONS = {'text_rule_mcp_safety'}

	def test_G01_template_content_matches_repo(self):
		"""Rule template DAT content should match corresponding .claude/ repo files."""
		project_root = self.embody_ext._findProjectRoot()
		templates_comp = self.embody_ext.my.op('templates')
		drifted = []
		for dat_name, slug in self.embody_ext._TEMPLATE_MAP_RULES.items():
			if dat_name in self._DRIFT_EXCLUSIONS:
				continue
			dat = templates_comp.op(dat_name)
			if dat is None:
				continue
			# Strip BOM, frontmatter, and generated-by marker from template
			template_content = self.embody_ext._stripFrontmatter(dat.text).strip()
			# Also strip the generated-by marker line if present
			marker_line = '<!-- Generated by Embody/Envoy - Do not remove this comment -->'
			if template_content.startswith(marker_line):
				template_content = template_content[len(marker_line):].strip()
			repo_file = project_root / '.claude' / 'rules' / f'{slug}.md'
			if not repo_file.exists():
				drifted.append(f'{dat_name}: repo file not found at {repo_file}')
				continue
			repo_content = repo_file.read_text(encoding='utf-8-sig').strip()
			if template_content != repo_content:
				drifted.append(f'{dat_name}: template DAT and repo file differ for {slug}.md')
		self.assertEqual(drifted, [],
			'Template drift detected:\n' + '\n'.join(drifted))

	def test_G02_exclusions_are_valid(self):
		"""All drift exclusion names should exist in _TEMPLATE_MAP_RULES."""
		for name in self._DRIFT_EXCLUSIONS:
			self.assertIn(name, self.embody_ext._TEMPLATE_MAP_RULES,
				f'Drift exclusion {name!r} not in _TEMPLATE_MAP_RULES')


class TestAgentsMdMerge(EmbodyTestCase):
	"""AGENTS.md is MERGED into, never overwritten and never skipped.

	It is the one file every AI tool reads and the one a repo most likely
	already has, so dragging Embody into an existing project meets a
	user-authored AGENTS.md as the normal case. Overwriting it destroys
	work; silently skipping it (the behavior before this) left the project
	with no Embody instructions at all and said nothing. Field-reported.
	"""

	MARKER = '<!-- Generated by Embody/Envoy'
	OWN = ('# My Project\n\n## House rules\n\nAlways run make lint.\n\n'
		'## Notes\n\nThis section has blank lines in it.\n')

	def setUp(self):
		super().setUp()
		self._temp_dir = Path(tempfile.mkdtemp(prefix='agents_merge_'))
		self._git = op.Embody.op('embody_git').module
		self._admin = op.Embody.op('embody_admin').module

	def tearDown(self):
		try:
			shutil.rmtree(self._temp_dir)
		except Exception:
			pass
		super().tearDown()

	def _agents(self):
		return (self._temp_dir / 'AGENTS.md').read_text(encoding='utf-8')

	def _seed_user_file(self):
		(self._temp_dir / 'AGENTS.md').write_text(self.OWN, encoding='utf-8')

	def test_A01_user_content_survives_the_merge(self):
		self._seed_user_file()
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		body = self._agents()
		self.assertIn('Always run make lint.', body)
		self.assertIn('This section has blank lines in it.', body)

	def test_A02_embody_block_is_added(self):
		"""Skipping the file left the project with NO Embody guidance."""
		self._seed_user_file()
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		body = self._agents()
		self.assertIn(self._git.AGENTS_BEGIN, body)
		self.assertIn(self._git.AGENTS_END, body)

	def test_A03_redeploy_updates_in_place(self):
		"""A second deploy must not stack a second block."""
		self._seed_user_file()
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		first = self._agents()
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		second = self._agents()
		self.assertEqual(second.count(self._git.AGENTS_BEGIN), 1)
		self.assertEqual(first, second, 'unchanged redeploy rewrote the file')

	def test_A04_uninstall_takes_back_only_the_block(self):
		self._seed_user_file()
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		stripped = self._admin.strip_md_section(self.embody_ext, self._agents())
		self.assertNotIn(self._git.AGENTS_BEGIN, stripped)
		self.assertEqual(stripped.strip(), self.OWN.strip(),
			'uninstall must restore the user file exactly')

	def test_A05_absent_file_is_still_written_whole(self):
		"""The common case is unchanged: no file -> plain generated file."""
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		body = self._agents()
		self.assertIn(self.MARKER, body)
		self.assertNotIn(self._git.AGENTS_BEGIN, body,
			'a file we own needs no merge delimiters')

	def test_A06_our_own_file_keeps_the_whole_file_path(self):
		"""An Embody-generated AGENTS.md refreshes wholesale, as before."""
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		self.assertNotIn(self._git.AGENTS_BEGIN, self._agents())

	def test_A07_merge_is_pure_and_replaces_a_prior_block(self):
		merged = self._git.merge_agents_section(
			'top\n\n' + self._git.AGENTS_BEGIN + '\nOLD\n'
			+ self._git.AGENTS_END + '\n\nbottom\n',
			self._git.agents_block('NEW'))
		self.assertIn('top', merged)
		self.assertIn('bottom', merged)
		self.assertIn('NEW', merged)
		self.assertNotIn('OLD', merged)


class TestMergeableDocsCoverage(EmbodyTestCase):
	"""Every top-level instruction file a repo plausibly already has must
	MERGE, not silently skip and not overwrite.

	AGENTS.md was the reported one, but it was never alone: GEMINI.md and
	.github/copilot-instructions.md had the same silent-skip behavior, and
	the ENVOY.md fallback was worse still -- it wrote over a hand-authored
	ENVOY.md with no marker check at all, the one path in the whole
	generated-file set that destroyed a user file on FIRST contact.
	"""

	USER = ('# MY OWN FILE\n\nDo not lose this line.\n\n'
		'## Section\n\nWith blank lines.\n')

	def setUp(self):
		super().setUp()
		self._temp_dir = Path(tempfile.mkdtemp(prefix='mergeable_'))
		self._git = op.Embody.op('embody_git').module
		self._admin = op.Embody.op('embody_admin').module

	def tearDown(self):
		try:
			shutil.rmtree(self._temp_dir)
		except Exception:
			pass
		super().tearDown()

	def _seed(self, rel):
		p = self._temp_dir / rel
		p.parent.mkdir(parents=True, exist_ok=True)
		p.write_text(self.USER, encoding='utf-8')
		return p

	def _assert_merged(self, p):
		body = p.read_text(encoding='utf-8')
		self.assertIn('Do not lose this line.', body)
		self.assertIn('With blank lines.', body)
		self.assertIn(self._git.AGENTS_BEGIN, body)
		self.assertEqual(body.count(self._git.AGENTS_BEGIN), 1)
		self.assertEqual(
			self._admin.strip_md_section(self.embody_ext, body).strip(),
			self.USER.strip(),
			'uninstall must give the user their file back unchanged')

	def test_C01_gemini_md_merges(self):
		p = self._seed('GEMINI.md')
		self._git.write_gemini_doc(self.embody_ext, self._temp_dir)
		self._assert_merged(p)

	def test_C02_copilot_instructions_merges(self):
		p = self._seed('.github/copilot-instructions.md')
		self._git.write_copilot_combined(self.embody_ext, self._temp_dir)
		self._assert_merged(p)

	def test_C03_user_envoy_md_is_never_clobbered(self):
		"""A hand-written ENVOY.md used to be destroyed outright by the
		CLAUDE.md fallback. Now nothing writes ENVOY.md at all, so a user's
		own copy must come through completely untouched -- while their
		CLAUDE.md is the one that gains the block."""
		(self._temp_dir / 'CLAUDE.md').write_text(
			'# their CLAUDE.md\nkeep\n', encoding='utf-8')
		p = self._seed('ENVOY.md')
		before = p.read_text(encoding='utf-8')
		self._git.write_claude_md(self.embody_ext, self._temp_dir)
		self.assertEqual(p.read_text(encoding='utf-8'), before,
			'ENVOY.md is no longer written -- theirs must be byte-identical')
		claude = (self._temp_dir / 'CLAUDE.md').read_text(encoding='utf-8')
		self.assertIn('keep', claude,
			'their CLAUDE.md content must survive')
		self.assertIn(self._git.AGENTS_BEGIN, claude,
			'and it is the file that now carries the block')

	def test_C04_every_mergeable_doc_is_actually_wired(self):
		"""The registry of mergeable docs must not drift from the writers.

		A name listed here that no writer routes through write_or_merge is
		a file that still silently skips.
		"""
		writers = {
			'AGENTS.md': lambda d: self._git.write_agents_md(self.embody_ext, d),
			'GEMINI.md': lambda d: self._git.write_gemini_doc(self.embody_ext, d),
			'.github/copilot-instructions.md':
				lambda d: self._git.write_copilot_combined(self.embody_ext, d),
			'CLAUDE.md': lambda d: self._git.write_claude_md(self.embody_ext, d),
		}
		for rel in self._git.MERGEABLE_DOCS:
			self.assertIn(rel, writers,
				f'{rel} is declared mergeable but no writer is wired to it')

	def test_C05_per_rule_files_still_skip_rather_than_merge(self):
		"""Deliberate contrast: per-rule filenames are Embody-specific, a
		collision is a coincidence, and merging into one of many would be
		noise. They stay skip-and-preserve."""
		reg = op.Embody.op('ai_clients').module
		p = self._seed('.claude/rules/td-python.md')
		self._git.write_rules_files(
			self.embody_ext, self._temp_dir, reg.spec('claudecode')['rules'])
		body = p.read_text(encoding='utf-8')
		self.assertEqual(body, self.USER, 'user rule file must be untouched')
		self.assertNotIn(self._git.AGENTS_BEGIN, body)
		self.assertTrue(
			(self._temp_dir / '.claude' / 'rules' / 'mcp-safety.md').exists(),
			'the other rules must still be written')


class TestMergedFileIsNeverDeleted(EmbodyTestCase):
	"""A merged user file must survive every path that deletes "our" files.

	Merging put Embody's generated-by marker INSIDE a file the user owns,
	which silently broke the invariant two separate sweeps relied on --
	"contains the marker" no longer means "the whole file is ours". Three
	independent reviewers found this; both sweeps deleted a hand-written
	AGENTS.md outright, which is precisely what merging exists to prevent.
	"""

	USER = "# Their AGENTS.md\n\nHand written. Must survive.\n"

	def setUp(self):
		super().setUp()
		self._temp_dir = Path(tempfile.mkdtemp(prefix='never_del_'))
		self._git = op.Embody.op('embody_git').module
		self._admin = op.Embody.op('embody_admin').module

	def tearDown(self):
		try:
			shutil.rmtree(self._temp_dir)
		except Exception:
			pass
		super().tearDown()

	def _merged(self, name='AGENTS.md'):
		(self._temp_dir / name).write_text(self.USER, encoding='utf-8')
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		body = (self._temp_dir / name).read_text(encoding='utf-8')
		self.assertIn(self.embody_ext._EMBODY_MARKER, body,
			'precondition: the block carries the marker into the user file')
		return self._temp_dir / name

	def _drop_manifest(self):
		"""Simulate a clone: .embody/ is gitignored, so it never travels."""
		shutil.rmtree(self._temp_dir / '.embody', ignore_errors=True)

	def test_D01_root_move_keeps_the_users_file(self):
		"""Changing AI Project Root ran a marker sweep over the old root."""
		p = self._merged()
		self.embody_ext._cleanupOldRootFiles(self._temp_dir)
		self.assertTrue(p.exists(), 'the user file was deleted by the sweep')
		self.assertEqual(p.read_text(encoding='utf-8'), self.USER,
			'the sweep must take the block and leave the file byte-exact')

	def test_D02_uninstall_keeps_it_even_with_no_manifest(self):
		"""The fallback scan is what runs on a clone -- the manifest that
		would have said "appended, not created" is gitignored and gone."""
		p = self._merged()
		self._drop_manifest()
		plan = self._admin.compute_uninstall_plan(
			self.embody_ext, target_dir=str(self._temp_dir))
		self.assertNotIn('AGENTS.md', [e['path'] for e in plan['delete']],
			'a user file must never be PLANNED for deletion')
		self._admin.execute_uninstall_plan(self.embody_ext, plan)
		self.assertTrue(p.exists())
		self.assertEqual(p.read_text(encoding='utf-8'), self.USER)

	def test_D03_a_file_embody_owns_outright_is_still_deleted(self):
		"""The guard must not make Uninstall timid about its OWN files."""
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		self._drop_manifest()
		self.embody_ext._cleanupOldRootFiles(self._temp_dir)
		self.assertFalse((self._temp_dir / 'AGENTS.md').exists(),
			'an Embody-generated AGENTS.md should still be removed')

	def test_D04_classifier_reports_merged_not_delete(self):
		self._merged()
		self._drop_manifest()
		verdict = self.embody_ext._uninstallClassifyMarker(
			self._temp_dir / 'AGENTS.md', self._temp_dir,
			self.embody_ext._loadHashManifest(str(self._temp_dir)))
		self.assertEqual(verdict, 'merged')


class TestMergeToleratesMangledDelimiters(EmbodyTestCase):
	"""The block delimiters live in a file humans and git both edit.

	Matching the FIRST BEGIN against the FIRST following END destroyed
	user content: an orphan BEGIN above Embody's real block made the pair
	span everything between them, so the next deploy deleted the prose in
	the middle. Delimiters are line-anchored and the scanner is tolerant.
	"""

	KEEP = '## MY IMPORTANT NOTES\nkeep me\n'

	def setUp(self):
		super().setUp()
		self._git = op.Embody.op('embody_git').module
		self._admin = op.Embody.op('embody_admin').module
		self.B = self._git.AGENTS_BEGIN
		self.X = self._git.AGENTS_END

	def _converges(self, text):
		"""Three deploys, then assert one clean block and intact content."""
		out = text
		for n in range(3):
			out = self._git.merge_agents_section(
				out, self._git.agents_block(f'EMBODY v{n}'))
		return out

	def test_E01_orphan_begin_without_end(self):
		out = self._converges(f'# repo\n\n{self.B}\n(old)\n\n{self.KEEP}')
		self.assertIn('keep me', out)
		self.assertEqual(self._git.block_count(out), 1)

	def test_E02_stray_end_alone(self):
		out = self._converges(f'# repo\n\n{self.X}\n\n{self.KEEP}')
		self.assertIn('keep me', out)
		self.assertEqual(self._git.block_count(out), 1)

	def test_E03_duplicated_blocks_from_a_merge_conflict(self):
		out = self._converges(
			f'# repo\n\n{self.B}\nA\n{self.X}\n\n{self.KEEP}\n'
			f'{self.B}\nBB\n{self.X}\n')
		self.assertIn('keep me', out)
		self.assertEqual(self._git.block_count(out), 1)

	def test_E04_marker_quoted_in_the_users_own_prose(self):
		"""A delimiter only counts alone on its line. Quoted in a sentence
		it is the user's text, and taking it as real made the span swallow
		everything up to Embody's actual END."""
		out = self._converges(
			f'# repo\n\nI use `{self.B}` in my docs.\n\n{self.KEEP}\n'
			f'{self.B}\nreal\n{self.X}\n')
		self.assertIn('keep me', out)
		self.assertIn('I use `', out, 'the quoted mention is user prose')
		self.assertEqual(self._git.block_count(out), 1)

	def test_E05_redeploy_is_stable_for_every_shape(self):
		for name, text in (
				('orphan', f'# r\n\n{self.B}\nx\n\n{self.KEEP}'),
				('dupes', f'# r\n\n{self.B}\nA\n{self.X}\n{self.B}\nB\n{self.X}\n'),
				('clean', f'# r\n\n{self.B}\nA\n{self.X}\n\n{self.KEEP}')):
			once = self._git.merge_agents_section(
				text, self._git.agents_block('E'))
			twice = self._git.merge_agents_section(
				once, self._git.agents_block('E'))
			self.assertEqual(once, twice, f'{name}: redeploy was not stable')

	def test_E06_strip_removes_every_block_shape(self):
		out = self._converges(
			f'# repo\n\n{self.B}\nA\n{self.X}\n\n{self.KEEP}\n'
			f'{self.B}\nB\n{self.X}\n')
		stripped = self._admin.strip_md_section(self.embody_ext, out)
		self.assertEqual(self._git.block_count(stripped), 0)
		self.assertIn('keep me', stripped)


class TestEditProtectionIsConsistent(EmbodyTestCase):
	"""Editing a generated file must mean the same thing everywhere.

	Three code paths decide whether a generated file is Embody's to
	replace: write_template (redeploy), _uninstallClassifyMarker
	(Uninstall), and _cleanupOldRootFiles (AI-project-root change). They
	disagreed. A rule the user edited was kept on redeploy, kept by
	Uninstall as 'review' -- and deleted outright by a root change, which
	then wrote the pristine template at the new root. CLAUDE.md was worse:
	it bypassed write_template entirely, so it was never hash-tracked and
	was overwritten on EVERY deploy, manifest intact.
	"""

	MARKER = '<!-- Generated by Embody/Envoy'

	def setUp(self):
		super().setUp()
		self._temp_dir = Path(tempfile.mkdtemp(prefix='editprot_'))
		self._git = op.Embody.op('embody_git').module
		self._admin = op.Embody.op('embody_admin').module

	def tearDown(self):
		try:
			shutil.rmtree(self._temp_dir)
		except Exception:
			pass
		super().tearDown()

	def _edit(self, path):
		path.write_text(path.read_text(encoding='utf-8') + '\n## Mine\nKeep this.\n',
			encoding='utf-8')

	def _a_rule(self):
		return next((self._temp_dir / '.claude' / 'rules').glob('*.md'))

	def test_F01_claude_md_is_hash_tracked_like_everything_else(self):
		"""It was the ONLY generated markdown bypassing write_template."""
		self._git.write_claude_md(self.embody_ext, self._temp_dir)
		manifest = self.embody_ext._loadHashManifest(str(self._temp_dir))
		self.assertIn('CLAUDE.md', manifest,
			'CLAUDE.md must be recorded, or nothing can protect edits to it')

	def test_F02_an_edited_claude_md_survives_a_redeploy(self):
		self._git.write_claude_md(self.embody_ext, self._temp_dir)
		self._edit(self._temp_dir / 'CLAUDE.md')
		self._git.write_claude_md(self.embody_ext, self._temp_dir)
		self.assertIn('Keep this.',
			(self._temp_dir / 'CLAUDE.md').read_text(encoding='utf-8'))

	def test_F03_an_unedited_claude_md_still_refreshes(self):
		"""Protection must not freeze a file the user never touched."""
		self._git.write_claude_md(self.embody_ext, self._temp_dir)
		path = self._temp_dir / 'CLAUDE.md'
		# A sentinel that cannot occur in the template -- 'stale' does:
		# the template says "Cached refs go stale on reinit".
		sentinel = 'ZZ_OUTDATED_SENTINEL_ZZ'
		path.write_text(self.MARKER + ' -->\n' + sentinel + '\n',
			encoding='utf-8')
		(self._temp_dir / self.embody_ext._HASH_MANIFEST).unlink()
		self._git.write_claude_md(self.embody_ext, self._temp_dir)
		self.assertNotIn(sentinel, path.read_text(encoding='utf-8'))

	def test_F04_root_move_keeps_an_edited_generated_rule(self):
		"""write_template kept it; the root sweep deleted it anyway."""
		self._git.write_client_config(
			self.embody_ext, self._temp_dir, 'claudecode')
		rule = self._a_rule()
		self._edit(rule)
		self.embody_ext._cleanupOldRootFiles(self._temp_dir)
		self.assertTrue(rule.exists(), 'the root sweep deleted an edited file')
		self.assertIn('Keep this.', rule.read_text(encoding='utf-8'))

	def test_F05_root_move_still_removes_an_untouched_generated_rule(self):
		"""The guard must not make the sweep timid about pristine files."""
		self._git.write_client_config(
			self.embody_ext, self._temp_dir, 'claudecode')
		rule = self._a_rule()
		self.embody_ext._cleanupOldRootFiles(self._temp_dir)
		self.assertFalse(rule.exists())

	def test_F06_root_move_keeps_an_edited_claude_md(self):
		self._git.write_claude_md(self.embody_ext, self._temp_dir)
		self._edit(self._temp_dir / 'CLAUDE.md')
		self.embody_ext._cleanupOldRootFiles(self._temp_dir)
		self.assertTrue((self._temp_dir / 'CLAUDE.md').exists())
		self.assertIn('Keep this.',
			(self._temp_dir / 'CLAUDE.md').read_text(encoding='utf-8'))

	def test_F07_a_block_only_file_is_removed_not_left_empty(self):
		"""A placeholder AGENTS.md that only ever held Embody's block must
		go at Uninstall -- the root sweep already unlinks in this case, and
		leaving a 0-byte file is a different answer to the same question."""
		(self._temp_dir / 'AGENTS.md').write_text('   \n', encoding='utf-8')
		self._git.write_agents_md(self.embody_ext, self._temp_dir)
		plan = self._admin.compute_uninstall_plan(
			self.embody_ext, target_dir=str(self._temp_dir))
		self._admin.execute_uninstall_plan(self.embody_ext, plan)
		self.assertFalse((self._temp_dir / 'AGENTS.md').exists(),
			'a 0-byte AGENTS.md was left behind')


class TestMarkerOwnershipIsPositional(EmbodyTestCase):
	""""Contains our marker" is not the same as "we wrote it".

	Embody puts the marker at the TOP of what it writes. A substring test
	over the whole file also matched a user who merely QUOTED the marker
	while documenting Embody in their own AGENTS.md -- and that file then
	took the "ours, regenerate" path and was overwritten whole, on first
	contact, with no log. Position separates the two.
	"""

	def setUp(self):
		super().setUp()
		self._temp_dir = Path(tempfile.mkdtemp(prefix='marker_'))
		self._git = op.Embody.op('embody_git').module
		self.MARK = self.embody_ext._EMBODY_MARKER

	def tearDown(self):
		try:
			shutil.rmtree(self._temp_dir)
		except Exception:
			pass
		super().tearDown()

	def test_G01_a_user_quoting_the_marker_is_not_ours(self):
		body = ('# AGENTS.md\n\nEmbody files start with `' + self.MARK
			+ ' -->`.\n\n## Our rules\n- ask Priya\n')
		self.assertFalse(
			self._git.is_generated_by_embody(self.embody_ext, body))

	def test_G02_that_file_is_merged_not_overwritten(self):
		body = ('# AGENTS.md\n\nEmbody files start with `' + self.MARK
			+ ' -->`.\n\n## Our rules\n- ask Priya\n')
		(self._temp_dir / 'AGENTS.md').write_text(body, encoding='utf-8')
		self._git.write_or_merge(
			self.embody_ext, self._temp_dir, 'AGENTS.md', 'GENERATED\n')
		after = (self._temp_dir / 'AGENTS.md').read_text(encoding='utf-8')
		self.assertIn('ask Priya', after, 'the user file was overwritten')
		self.assertEqual(self._git.block_count(after), 1)

	def test_G03_frontmatter_first_generated_files_are_still_ours(self):
		"""Several dialects need YAML frontmatter ABOVE the marker --
		Cursor .mdc, Copilot .instructions.md, every SKILL.md. A strict
		first-line rule stopped recognising them, so they were skipped on
		redeploy and orphaned by Uninstall."""
		for token in ('cursor', 'copilot', 'claudecode', 'antigravity'):
			self._git.write_client_config(
				self.embody_ext, self._temp_dir, token)
		for label, pattern in (
				('cursor', '.cursor/rules/*.mdc'),
				('copilot', '.github/instructions/*.md'),
				('claude skill', '.claude/skills/*/SKILL.md'),
				('agents skill', '.agents/skills/*/SKILL.md'),
				('claude rule', '.claude/rules/*.md')):
			path = next(self._temp_dir.glob(pattern))
			self.assertTrue(
				self._git.is_generated_by_embody(
					self.embody_ext, path.read_text(encoding='utf-8')),
				f'{label} ({path.name}) is ours but was not recognised')

	def test_G04_frontmatter_does_not_let_a_user_file_pass(self):
		faux = ('---\ntitle: mine\n---\n\n# Mine\n\nI mention '
			+ self.MARK + ' here.\n')
		self.assertFalse(
			self._git.is_generated_by_embody(self.embody_ext, faux))

	def test_G05_an_indented_delimiter_example_is_not_a_delimiter(self):
		"""A numbered list documenting the block used to eat the lines
		between the example's own delimiters."""
		B, X = self._git.AGENTS_BEGIN, self._git.AGENTS_END
		doc = f'HEAD\n1. Example:\n\n    {B}\n    MY LINE\n    {X}\n\nTAIL\n'
		merged = self._git.merge_agents_section(
			doc, self._git.agents_block('EMBODY'))
		self.assertIn('MY LINE', merged)
		self.assertIn('TAIL', merged)

	def test_G06_a_bom_on_the_begin_line_does_not_orphan_the_block(self):
		"""'\ufeff' is not whitespace, so .strip() left it attached and
		the block stopped matching itself -- stale content stranded and a
		second block appended."""
		B, X = self._git.AGENTS_BEGIN, self._git.AGENTS_END
		bom = '﻿' + B + '\nOLD\n' + X + '\nUSER TAIL\n'
		merged = self._git.merge_agents_section(
			bom, self._git.agents_block('NEW'))
		self.assertEqual(self._git.block_count(merged), 1)
		self.assertNotIn('OLD', merged)
		self.assertIn('USER TAIL', merged)

	def test_G07_an_undecodable_file_is_left_alone_not_mangled(self):
		"""The root sweep read with errors='ignore' and wrote the result
		BACK, so every undecodable byte was dropped from the user's file
		while the log claimed the file was kept."""
		raw = ('# Caf' + chr(0xE9) + ' rules\n').encode('latin-1')
		(self._temp_dir / 'AGENTS.md').write_bytes(raw)
		self.embody_ext._cleanupOldRootFiles(self._temp_dir)
		self.assertEqual((self._temp_dir / 'AGENTS.md').read_bytes(), raw)


class TestGeneratedFilesCarryTheirOwnProof(EmbodyTestCase):
	"""A generated file must prove on its own whether it is still ours.

	Edit protection used to depend entirely on a hash sidecar in
	.embody/, which Embody itself gitignores -- so it never survived a
	clone. On any second machine a file with the marker and no record
	read as "written before hashing existed, regenerate", silently
	replacing edits a teammate had committed, and Uninstall called the
	same file "Embody-generated, unmodified" and deleted it. The hash now
	rides in the marker line, so the proof travels with the file.
	"""

	def setUp(self):
		super().setUp()
		self._tmp = Path(tempfile.mkdtemp(prefix='stamp_'))
		self._git = op.Embody.op('embody_git').module

	def tearDown(self):
		try:
			shutil.rmtree(self._tmp)
		except Exception:
			pass
		super().tearDown()

	def _generate(self, root=None):
		root = root or self._tmp
		self._git.write_client_config(self.embody_ext, root, 'claudecode')
		return root / '.claude' / 'rules' / 'td-python.md'

	def _clone_without_sidecar(self):
		"""What git actually delivers: the files, never .embody/."""
		dest = Path(tempfile.mkdtemp(prefix='stampclone_'))
		shutil.copytree(self._tmp, dest, dirs_exist_ok=True,
			ignore=shutil.ignore_patterns('.embody'))
		self.addCleanup(lambda: shutil.rmtree(dest, ignore_errors=True))
		return dest

	def test_H01_the_marker_line_carries_the_hash(self):
		rule = self._generate()
		first = rule.read_text(encoding='utf-8').split('\n')[0]
		self.assertIn('sha:', first)
		self.assertIsNotNone(
			self._git.read_stamp(self.embody_ext,
				rule.read_text(encoding='utf-8')))

	def test_H02_the_stamp_matches_a_freshly_written_file(self):
		rule = self._generate()
		body = rule.read_text(encoding='utf-8')
		self.assertEqual(
			self._git.content_hash(
				self.embody_ext, self._git.strip_stamp(self.embody_ext, body)),
			self._git.read_stamp(self.embody_ext, body))

	def test_H03_an_edit_is_detected_with_no_sidecar_at_all(self):
		"""The clone case, end to end."""
		rule = self._generate()
		rule.write_text(rule.read_text(encoding='utf-8')
			+ '\n## House rule\nNever force-push main.\n', encoding='utf-8')
		clone = self._clone_without_sidecar()
		self.assertFalse((clone / self.embody_ext._HASH_MANIFEST).exists(),
			'precondition: the sidecar must not have travelled')
		cloned_rule = clone / '.claude' / 'rules' / 'td-python.md'
		self._git.write_client_config(self.embody_ext, clone, 'claudecode')
		self.assertIn('Never force-push main.',
			cloned_rule.read_text(encoding='utf-8'),
			'a committed edit was overwritten on a clone')

	def test_H04_uninstall_on_a_clone_calls_an_edit_review_not_delete(self):
		rule = self._generate()
		rule.write_text(rule.read_text(encoding='utf-8')
			+ '\n## House rule\nkeep\n', encoding='utf-8')
		clone = self._clone_without_sidecar()
		verdict = self.embody_ext._uninstallClassifyMarker(
			clone / '.claude' / 'rules' / 'td-python.md', clone,
			self.embody_ext._loadHashManifest(str(clone)))
		self.assertEqual(verdict, 'review',
			'an edited file on a clone was still classed as ours to delete')

	def test_H05_an_untouched_file_on_a_clone_is_still_ours(self):
		"""The stamp must not make Embody timid about its own files."""
		self._generate()
		clone = self._clone_without_sidecar()
		verdict = self.embody_ext._uninstallClassifyMarker(
			clone / '.claude' / 'rules' / 'td-python.md', clone,
			self.embody_ext._loadHashManifest(str(clone)))
		self.assertEqual(verdict, 'delete')

	def test_H06_an_untouched_file_still_refreshes_on_a_clone(self):
		self._generate()
		clone = self._clone_without_sidecar()
		rule = clone / '.claude' / 'rules' / 'td-python.md'
		rule.write_text(
			self._git.strip_stamp(self.embody_ext,
				rule.read_text(encoding='utf-8')), encoding='utf-8')
		self._git.write_client_config(self.embody_ext, clone, 'claudecode')
		self.assertIn('sha:', rule.read_text(encoding='utf-8').split('\n')[0],
			'a stamp-less legacy file should be re-stamped, not frozen')

	def test_H07_a_pre_stamp_legacy_file_still_regenerates(self):
		"""Backward compatibility: files written before stamping have no
		stamp and no sidecar entry, and must keep their old behavior."""
		rule = self._generate()
		stripped = self._git.strip_stamp(
			self.embody_ext, rule.read_text(encoding='utf-8'))
		rule.write_text(stripped, encoding='utf-8')
		(self._tmp / self.embody_ext._HASH_MANIFEST).unlink()
		self.assertTrue(
			self._git.embody_owns_unmodified(
				self.embody_ext, stripped, {}, '.claude/rules/td-python.md'),
			'a legacy stamp-less file must still be treated as ours')

	def test_H08_stamping_survives_frontmatter_dialects(self):
		"""Cursor .mdc, Copilot instructions and SKILL.md put YAML above
		the marker; the stamp has to find it there."""
		for token in ('cursor', 'copilot', 'antigravity'):
			self._git.write_client_config(self.embody_ext, self._tmp, token)
		for pattern in ('.cursor/rules/*.mdc', '.github/instructions/*.md',
				'.agents/skills/*/SKILL.md'):
			path = next(self._tmp.glob(pattern))
			body = path.read_text(encoding='utf-8')
			self.assertIsNotNone(
				self._git.read_stamp(self.embody_ext, body),
				f'{path.name} carries frontmatter and lost its stamp')
			self.assertTrue(
				self._git.embody_owns_unmodified(
					self.embody_ext, body, {}, 'x'),
				f'{path.name} should verify against its own stamp')


class TestEmbodySourceTreeGuard(EmbodyTestCase):
	"""Dogfooding: Embody must not merge the USER-PROJECT template into its own
	repo's hand-written CLAUDE.md.

	That file is the DEVELOPER's instructions for working ON Embody; the block
	carries the template for projects that USE it. Merging one into the other
	gives a single file two contradictory rule lists, loaded into every dev
	session.
	"""

	def _git(self):
		return op.Embody.op('embody_git').module

	def test_the_repo_root_is_recognised_as_the_source_tree(self):
		root = Path(project.folder).parent
		self.assertTrue(
			self._git().is_embody_source_tree(self.embody_ext, root),
			'the repo that holds EmbodyExt.py must be recognised as the source tree')

	def test_an_ordinary_target_is_not_the_source_tree(self):
		"""Load-bearing. Keying this to isDevCheckout alone would fire for EVERY
		target while developing -- including the temp dirs the merge suite writes
		to -- so the tested behaviour would stop matching the shipped one."""
		d = Path(tempfile.mkdtemp(prefix='notsrc_'))
		try:
			self.assertFalse(
				self._git().is_embody_source_tree(self.embody_ext, d),
				'an ordinary project dir must merge normally')
		finally:
			shutil.rmtree(d, ignore_errors=True)

	def test_an_ordinary_target_still_merges(self):
		"""The guard must not have disabled the feature it is narrowing."""
		g = self._git()
		d = Path(tempfile.mkdtemp(prefix='stillmerges_'))
		try:
			(d / 'CLAUDE.md').write_text('# Mine\nkeep me\n', encoding='utf-8')
			g.write_claude_md(self.embody_ext, d)
			body = (d / 'CLAUDE.md').read_text(encoding='utf-8')
			self.assertIn(g.AGENTS_BEGIN, body)
			self.assertIn('keep me', body)
		finally:
			shutil.rmtree(d, ignore_errors=True)

	def test_the_repos_own_claude_md_is_left_alone(self):
		"""The end-to-end assertion, against the real repo root: a deploy into
		Embody's own tree must leave its CLAUDE.md byte-identical."""
		root = Path(project.folder).parent
		p = root / 'CLAUDE.md'
		if not p.exists():
			raise SkipTest('no CLAUDE.md at the repo root')
		before = p.read_text(encoding='utf-8')
		self._git().write_claude_md(self.embody_ext, root)
		self.assertEqual(
			p.read_text(encoding='utf-8'), before,
			"Embody's own repo CLAUDE.md must come through untouched")
		self.assertNotIn(
			self._git().AGENTS_BEGIN, before,
			'and it must never have gained a block')
