"""
Test suite: Claude config generation pipeline in EmbodyExt.

Tests _TEMPLATE_MAP integrity, _writeTemplate, _writeClaudeMd,
_extractClaudeConfig end-to-end, and _upgradeEnvoy condition logic.
"""

import tempfile
import shutil
from pathlib import Path

runner_mod = op.unit_tests.op('TestRunnerExt').module
EmbodyTestCase = runner_mod.EmbodyTestCase


class TestClaudeConfig(EmbodyTestCase):

	MARKER = '<!-- Generated by Embody/Envoy'

	def setUp(self):
		super().setUp()
		self._temp_dir = Path(tempfile.mkdtemp(prefix='claude_config_test_'))

	def tearDown(self):
		try:
			shutil.rmtree(self._temp_dir)
		except Exception:
			pass
		super().tearDown()

	# ------------------------------------------------------------------
	# Group A: Template DAT integrity
	# ------------------------------------------------------------------

	def test_A01_template_map_has_10_entries(self):
		"""_TEMPLATE_MAP should have exactly 10 template entries."""
		self.assertLen(self.embody_ext._TEMPLATE_MAP, 10)

	def test_A02_templates_comp_exists(self):
		"""The templates COMP should exist inside Embody."""
		templates_comp = self.embody_ext.my.op('templates')
		self.assertIsNotNone(templates_comp,
			'templates COMP not found inside Embody')

	def test_A03_all_template_dats_exist(self):
		"""Every DAT named in _TEMPLATE_MAP should exist in the templates COMP."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP:
			dat = templates_comp.op(dat_name)
			self.assertIsNotNone(dat,
				f'Template DAT {dat_name!r} missing from templates COMP')

	def test_A04_all_template_dats_have_content(self):
		"""Every template DAT should have non-empty text content."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP:
			dat = templates_comp.op(dat_name)
			self.assertTrue(dat.text,
				f'Template DAT {dat_name!r} has empty .text')

	def test_A05_all_template_dats_have_marker(self):
		"""Every template DAT should contain the Embody/Envoy marker."""
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name in self.embody_ext._TEMPLATE_MAP:
			dat = templates_comp.op(dat_name)
			self.assertIn(self.MARKER, dat.text,
				f'Template DAT {dat_name!r} missing marker')

	def test_A06_text_claude_dat_exists(self):
		"""The text_claude DAT should exist at the Embody COMP level."""
		dat = self.embody_ext.my.op('text_claude')
		self.assertIsNotNone(dat, 'text_claude DAT not found')

	def test_A07_text_claude_dat_has_marker(self):
		"""text_claude DAT content should contain the Embody/Envoy marker."""
		dat = self.embody_ext.my.op('text_claude')
		self.assertIn(self.MARKER, dat.text,
			'text_claude DAT missing marker')

	def test_A08_template_map_paths_are_relative(self):
		"""All _TEMPLATE_MAP paths should be relative and use forward slashes."""
		for dat_name, rel_path in self.embody_ext._TEMPLATE_MAP.items():
			self.assertFalse(rel_path.startswith('/'),
				f'{dat_name}: path {rel_path!r} should be relative')
			self.assertNotIn('\\', rel_path,
				f'{dat_name}: path {rel_path!r} has backslash')

	def test_A09_template_map_paths_under_dot_claude(self):
		"""All _TEMPLATE_MAP paths should be under .claude/."""
		for dat_name, rel_path in self.embody_ext._TEMPLATE_MAP.items():
			self.assertTrue(rel_path.startswith('.claude/'),
				f'{dat_name}: path {rel_path!r} not under .claude/')

	# ------------------------------------------------------------------
	# Group B: _writeTemplate() behavior
	# ------------------------------------------------------------------

	def test_B01_creates_file_when_missing(self):
		"""_writeTemplate should create the file and return True when missing."""
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'test/new.md', 'content here')
		self.assertTrue(result)
		self.assertTrue((self._temp_dir / 'test' / 'new.md').exists())

	def test_B02_created_content_matches_input(self):
		"""Written file content should match the input exactly."""
		content = '# Title\n\nSome content with unicode: \u00e9\u00e8\u00ea\n'
		self.embody_ext._writeTemplate(
			self._temp_dir, 'exact.md', content)
		written = (self._temp_dir / 'exact.md').read_text(encoding='utf-8')
		self.assertEqual(written, content)

	def test_B03_overwrites_file_with_marker(self):
		"""_writeTemplate should overwrite a file that contains the marker."""
		target = self._temp_dir / 'marked.md'
		target.write_text(self.MARKER + ' old content', encoding='utf-8')
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'marked.md', 'new content')
		self.assertTrue(result)
		self.assertEqual(
			target.read_text(encoding='utf-8'), 'new content')

	def test_B04_skips_file_without_marker(self):
		"""_writeTemplate should skip a file that lacks the marker."""
		target = self._temp_dir / 'user.md'
		target.write_text('User wrote this', encoding='utf-8')
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'user.md', 'attempted overwrite')
		self.assertFalse(result)
		self.assertEqual(
			target.read_text(encoding='utf-8'), 'User wrote this')

	def test_B05_creates_parent_directories(self):
		"""_writeTemplate should create parent directories as needed."""
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'a/b/c/deep.md', 'deep content')
		self.assertTrue(result)
		self.assertTrue((self._temp_dir / 'a' / 'b' / 'c' / 'deep.md').exists())

	def test_B06_returns_true_on_overwrite(self):
		"""_writeTemplate return value should be True when overwriting."""
		target = self._temp_dir / 'retval.md'
		target.write_text(self.MARKER + ' v1', encoding='utf-8')
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'retval.md', self.MARKER + ' v2')
		self.assertTrue(result)

	def test_B07_empty_content_still_writes(self):
		"""_writeTemplate should write even when content is empty string."""
		result = self.embody_ext._writeTemplate(
			self._temp_dir, 'empty.md', '')
		self.assertTrue(result)
		self.assertTrue((self._temp_dir / 'empty.md').exists())
		self.assertEqual(
			(self._temp_dir / 'empty.md').read_text(encoding='utf-8'), '')

	# ------------------------------------------------------------------
	# Group C: _writeClaudeMd() behavior
	# ------------------------------------------------------------------

	def test_C01_creates_claude_md_when_missing(self):
		"""_writeClaudeMd should create CLAUDE.md when it does not exist."""
		result = self.embody_ext._writeClaudeMd(self._temp_dir)
		self.assertIsNotNone(result)
		self.assertTrue((self._temp_dir / 'CLAUDE.md').exists())

	def test_C02_created_claude_md_has_template_content(self):
		"""Created CLAUDE.md should contain the text_claude DAT content."""
		self.embody_ext._writeClaudeMd(self._temp_dir)
		expected = self.embody_ext.my.op('text_claude').text
		actual = (self._temp_dir / 'CLAUDE.md').read_text(encoding='utf-8')
		self.assertEqual(actual, expected)

	def test_C03_overwrites_claude_md_with_marker(self):
		"""_writeClaudeMd should overwrite CLAUDE.md when it has the marker."""
		existing = self._temp_dir / 'CLAUDE.md'
		existing.write_text(self.MARKER + ' old version', encoding='utf-8')
		result = self.embody_ext._writeClaudeMd(self._temp_dir)
		self.assertEqual(result, existing)
		updated = existing.read_text(encoding='utf-8')
		expected = self.embody_ext.my.op('text_claude').text
		self.assertEqual(updated, expected)

	def test_C04_falls_back_to_envoy_md_without_marker(self):
		"""_writeClaudeMd should write to ENVOY.md if CLAUDE.md lacks marker."""
		user_claude = self._temp_dir / 'CLAUDE.md'
		user_claude.write_text('My own claude config', encoding='utf-8')
		result = self.embody_ext._writeClaudeMd(self._temp_dir)
		expected_fallback = self._temp_dir / 'ENVOY.md'
		self.assertEqual(result, expected_fallback)
		self.assertTrue(expected_fallback.exists())
		# Original CLAUDE.md should be untouched
		self.assertEqual(
			user_claude.read_text(encoding='utf-8'),
			'My own claude config')

	def test_C05_envoy_md_has_template_content(self):
		"""ENVOY.md fallback should contain the text_claude DAT content."""
		(self._temp_dir / 'CLAUDE.md').write_text('user content', encoding='utf-8')
		self.embody_ext._writeClaudeMd(self._temp_dir)
		expected = self.embody_ext.my.op('text_claude').text
		actual = (self._temp_dir / 'ENVOY.md').read_text(encoding='utf-8')
		self.assertEqual(actual, expected)

	def test_C06_returns_claude_md_path_on_create(self):
		"""_writeClaudeMd should return the CLAUDE.md path on fresh create."""
		result = self.embody_ext._writeClaudeMd(self._temp_dir)
		self.assertEqual(result, self._temp_dir / 'CLAUDE.md')

	# ------------------------------------------------------------------
	# Group D: _extractClaudeConfig() end-to-end
	# ------------------------------------------------------------------

	def _run_pipeline(self):
		"""Helper: run the full pipeline against self._temp_dir."""
		self.embody_ext._writeClaudeMd(self._temp_dir)
		templates_comp = self.embody_ext.my.op('templates')
		written = 0
		for dat_name, rel_path in self.embody_ext._TEMPLATE_MAP.items():
			dat = templates_comp.op(dat_name)
			if dat and dat.text:
				if self.embody_ext._writeTemplate(
						self._temp_dir, rel_path, dat.text):
					written += 1
		return written

	def test_D01_all_template_files_created(self):
		"""Full pipeline should create CLAUDE.md + all 10 template files."""
		self._run_pipeline()
		self.assertTrue((self._temp_dir / 'CLAUDE.md').exists())
		for rel_path in self.embody_ext._TEMPLATE_MAP.values():
			full = self._temp_dir / rel_path
			self.assertTrue(full.exists(),
				f'Expected file not created: {rel_path}')

	def test_D02_file_content_matches_dats(self):
		"""Each template file content should match its source DAT."""
		self._run_pipeline()
		templates_comp = self.embody_ext.my.op('templates')
		for dat_name, rel_path in self.embody_ext._TEMPLATE_MAP.items():
			dat = templates_comp.op(dat_name)
			full = self._temp_dir / rel_path
			actual = full.read_text(encoding='utf-8')
			self.assertEqual(actual, dat.text,
				f'Content mismatch for {rel_path}')

	def test_D03_directory_structure_correct(self):
		"""Pipeline should create .claude/rules/ and .claude/skills/ subdirs."""
		self._run_pipeline()
		self.assertTrue((self._temp_dir / '.claude' / 'rules').is_dir())
		self.assertTrue((self._temp_dir / '.claude' / 'skills').is_dir())

	def test_D04_rules_files_count(self):
		"""Three rule files should be created in .claude/rules/."""
		self._run_pipeline()
		rules_dir = self._temp_dir / '.claude' / 'rules'
		rule_files = list(rules_dir.glob('*.md'))
		self.assertLen(rule_files, 3)

	def test_D05_skills_directories_count(self):
		"""Seven skill directories should be created in .claude/skills/."""
		self._run_pipeline()
		skills_dir = self._temp_dir / '.claude' / 'skills'
		skill_dirs = [d for d in skills_dir.iterdir() if d.is_dir()]
		self.assertLen(skill_dirs, 7)

	def test_D06_idempotent_rerun(self):
		"""Running the pipeline twice should produce identical files."""
		self._run_pipeline()
		first_run = {}
		for rel_path in self.embody_ext._TEMPLATE_MAP.values():
			full = self._temp_dir / rel_path
			first_run[rel_path] = full.read_text(encoding='utf-8')
		# Second run
		self._run_pipeline()
		for rel_path in self.embody_ext._TEMPLATE_MAP.values():
			full = self._temp_dir / rel_path
			second = full.read_text(encoding='utf-8')
			self.assertEqual(first_run[rel_path], second,
				f'Content changed on second run for {rel_path}')

	# ------------------------------------------------------------------
	# Group E: _upgradeEnvoy() condition logic
	# ------------------------------------------------------------------

	def test_E01_upgrade_needed_when_no_files(self):
		"""Upgrade should be needed when both CLAUDE.md and ENVOY.md are missing."""
		d = self._temp_dir
		needs_extract = (
			not (d / 'CLAUDE.md').exists()
			and not (d / 'ENVOY.md').exists()
		) or not (d / '.claude' / 'rules').exists()
		self.assertTrue(needs_extract)

	def test_E02_upgrade_not_needed_when_all_present(self):
		"""Upgrade not needed when CLAUDE.md and .claude/rules/ both exist."""
		d = self._temp_dir
		(d / 'CLAUDE.md').write_text('content', encoding='utf-8')
		(d / '.claude' / 'rules').mkdir(parents=True)
		needs_extract = (
			not (d / 'CLAUDE.md').exists()
			and not (d / 'ENVOY.md').exists()
		) or not (d / '.claude' / 'rules').exists()
		self.assertFalse(needs_extract)

	def test_E03_upgrade_needed_when_rules_missing(self):
		"""Upgrade needed when .claude/rules/ missing even with CLAUDE.md."""
		d = self._temp_dir
		(d / 'CLAUDE.md').write_text('content', encoding='utf-8')
		needs_extract = (
			not (d / 'CLAUDE.md').exists()
			and not (d / 'ENVOY.md').exists()
		) or not (d / '.claude' / 'rules').exists()
		self.assertTrue(needs_extract)

	def test_E04_upgrade_not_needed_with_envoy_md(self):
		"""Upgrade not needed when ENVOY.md and .claude/rules/ both exist."""
		d = self._temp_dir
		(d / 'ENVOY.md').write_text('content', encoding='utf-8')
		(d / '.claude' / 'rules').mkdir(parents=True)
		needs_extract = (
			not (d / 'CLAUDE.md').exists()
			and not (d / 'ENVOY.md').exists()
		) or not (d / '.claude' / 'rules').exists()
		self.assertFalse(needs_extract)

	# ------------------------------------------------------------------
	# Group F: _findProjectRoot()
	# ------------------------------------------------------------------

	def test_F01_returns_path_object(self):
		"""_findProjectRoot should return a Path object."""
		result = self.embody_ext._findProjectRoot()
		self.assertIsInstance(result, Path)

	def test_F02_returned_path_exists(self):
		"""_findProjectRoot should return an existing directory."""
		result = self.embody_ext._findProjectRoot()
		self.assertTrue(result.exists())
		self.assertTrue(result.is_dir())

	def test_F03_returned_path_contains_git(self):
		"""_findProjectRoot should find the .git directory."""
		result = self.embody_ext._findProjectRoot()
		self.assertTrue((result / '.git').exists(),
			f'No .git found at {result}')

	# ------------------------------------------------------------------
	# Group G: Template drift detection
	# ------------------------------------------------------------------

	# Templates that intentionally differ from repo .claude/ files.
	# mcp-safety: repo has detailed dev version, template has short user version.
	_DRIFT_EXCLUSIONS = {'text_rule_mcp_safety'}

	def test_G01_template_content_matches_repo(self):
		"""Template DAT content should match corresponding .claude/ repo files."""
		project_root = self.embody_ext._findProjectRoot()
		templates_comp = self.embody_ext.my.op('templates')
		drifted = []
		for dat_name, rel_path in self.embody_ext._TEMPLATE_MAP.items():
			if dat_name in self._DRIFT_EXCLUSIONS:
				continue
			dat = templates_comp.op(dat_name)
			if dat is None:
				continue
			template_content = dat.text.strip()
			repo_file = project_root / rel_path
			if not repo_file.exists():
				drifted.append(f'{dat_name}: repo file not found at {repo_file}')
				continue
			repo_content = repo_file.read_text(encoding='utf-8-sig').strip()
			if template_content != repo_content:
				drifted.append(f'{dat_name}: template DAT and repo file differ for {rel_path}')
		self.assertEqual(drifted, [],
			f'Template drift detected:\n' + '\n'.join(drifted))

	def test_G02_exclusions_are_valid(self):
		"""All drift exclusion names should exist in _TEMPLATE_MAP."""
		for name in self._DRIFT_EXCLUSIONS:
			self.assertIn(name, self.embody_ext._TEMPLATE_MAP,
				f'Drift exclusion {name!r} not in _TEMPLATE_MAP')
