"""
Test suite: AI template sync validation.

Guards the three hand-synchronized surfaces that ship .claude/ rules and
skills into user projects: EmbodyExt template maps, template DAT files on
disk, and the release-commits.md sync table.
"""

import re
from pathlib import Path


runner_mod = op.unit_tests.op('TestRunnerExt').module
EmbodyTestCase = runner_mod.EmbodyTestCase


GENERATED_MARKER = 'Generated by Embody/Envoy'

# Documented in release-commits.md as deliberate dev-only template files.
# New orphan templates must be added here consciously after the docs explain
# why they do not ship.
KNOWN_ORPHANS = {
    'text_rule_commit_push_checklist.md',
    'text_rule_github_release.md',
    'text_rule_refresh_after_commit.py',
}


class TestTemplateSync(EmbodyTestCase):

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _repo_root(self):
        return Path(project.folder).resolve().parent

    def _templates_dir(self):
        return Path(project.folder).resolve() / 'embody' / 'Embody' / 'templates'

    def _template_pairs(self):
        pairs = []
        for dat_name, slug in self.embody_ext._TEMPLATE_MAP_RULES.items():
            pairs.append((
                'rules/{}.md'.format(slug),
                'templates/{}.md'.format(dat_name),
                True,
            ))
        for dat_name, slug in self.embody_ext._TEMPLATE_MAP_SKILLS.items():
            pairs.append((
                'skills/{}/SKILL.md'.format(slug),
                'templates/{}.md'.format(dat_name),
                False,
            ))
        return pairs

    def _source_path(self, source_rel):
        return self._repo_root() / '.claude' / source_rel

    def _template_path(self, template_rel):
        return self._templates_dir() / template_rel.split('/', 1)[1]

    def _read_lines(self, path):
        data = path.read_bytes()
        if data.startswith(b'\xef\xbb\xbf'):
            data = data[3:]
        text = data.decode('utf-8')
        text = text.replace('\r\n', '\n').replace('\r', '\n')
        return text.split('\n')

    def _strip_frontmatter(self, lines):
        if lines and lines[0] == '---':
            for idx in range(1, len(lines)):
                if lines[idx] == '---':
                    return lines[idx + 1:]
        return lines

    def _normalized_lines(self, path, strip_frontmatter=False):
        lines = self._read_lines(path)
        if strip_frontmatter:
            lines = self._strip_frontmatter(lines)
        lines = [
            line.rstrip()
            for line in lines
            if GENERATED_MARKER not in line
        ]
        while lines and lines[0] == '':
            lines.pop(0)
        while lines and lines[-1] == '':
            lines.pop()
        return lines

    def _content_lines(self, path):
        return self._strip_frontmatter(self._read_lines(path))

    def _short(self, line):
        if line is None:
            return '<EOF>'
        if len(line) > 120:
            line = line[:117] + '...'
        return repr(line)

    def _first_diff_message(self, source_rel, template_rel,
                            source_lines, template_lines):
        limit = max(len(source_lines), len(template_lines))
        for idx in range(limit):
            source_line = source_lines[idx] if idx < len(source_lines) else None
            template_line = (
                template_lines[idx] if idx < len(template_lines) else None)
            if source_line != template_line:
                return (
                    '{} vs {} differ at normalized line {}:\n'
                    '  source: {}\n'
                    '  template: {}'
                ).format(
                    source_rel,
                    template_rel,
                    idx + 1,
                    self._short(source_line),
                    self._short(template_line),
                )
        return '{} vs {} differ'.format(source_rel, template_rel)

    def _mapped_table_rows(self):
        return set((source_rel, template_rel)
                   for source_rel, template_rel, _ in self._template_pairs())

    def _release_table_rows(self):
        release_path = self._repo_root() / '.claude' / 'rules' / 'release-commits.md'
        text = release_path.read_text(encoding='utf-8')
        start = text.find('## 4. Verify Template Sync')
        self.assertNotEqual(start, -1,
                            'release-commits.md missing section 4')
        end = text.find('\n## ', start + 1)
        if end == -1:
            end = len(text)
        section = text[start:end]
        rows = set()
        for line in section.splitlines():
            match = re.match(r'^\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|',
                             line.strip())
            if not match:
                continue
            source_rel, template_rel = match.groups()
            if source_rel == '.claude/ file':
                continue
            rows.add((source_rel, template_rel))
        return rows

    def _format_rows(self, rows):
        if not rows:
            return 'none'
        return ', '.join('{} -> {}'.format(a, b) for a, b in sorted(rows))

    # ==================================================================
    # A. Map entries resolve on disk
    # ==================================================================

    def test_A01_map_entries_resolve_on_disk(self):
        """Every mapped source and template file should exist on disk."""
        for source_rel, template_rel, _ in self._template_pairs():
            source_path = self._source_path(source_rel)
            template_path = self._template_path(template_rel)
            self.assertTrue(source_path.is_file(),
                            'Mapped source missing: {}'.format(source_rel))
            self.assertTrue(template_path.is_file(),
                            'Mapped template missing: {}'.format(template_rel))

    # ==================================================================
    # B. Source/template content parity
    # ==================================================================

    def test_B01_template_content_matches_source(self):
        """Templates should match their .claude/ sources after export noise."""
        for source_rel, template_rel, is_rule in self._template_pairs():
            source_path = self._source_path(source_rel)
            template_path = self._template_path(template_rel)
            self.assertTrue(source_path.is_file(),
                            'Mapped source missing: {}'.format(source_rel))
            self.assertTrue(template_path.is_file(),
                            'Mapped template missing: {}'.format(template_rel))

            # Rule templates carry Cursor frontmatter that rule sources do not.
            # Skill templates keep SKILL.md frontmatter, so compare it.
            source_lines = self._normalized_lines(
                source_path, strip_frontmatter=is_rule)
            template_lines = self._normalized_lines(
                template_path, strip_frontmatter=is_rule)
            self.assertEqual(
                source_lines,
                template_lines,
                self._first_diff_message(
                    source_rel, template_rel, source_lines, template_lines),
            )

    # ==================================================================
    # C. release-commits.md table matches maps
    # ==================================================================

    def test_C01_release_table_matches_template_maps(self):
        """The documented sync table should equal the live shipping maps."""
        mapped_rows = self._mapped_table_rows()
        table_rows = self._release_table_rows()
        missing = mapped_rows - table_rows
        unmapped = table_rows - mapped_rows
        self.assertEqual(
            table_rows,
            mapped_rows,
            'Missing table rows: {}\nUnmapped table rows: {}'.format(
                self._format_rows(missing),
                self._format_rows(unmapped),
            ),
        )

    # ==================================================================
    # D. No unknown orphan templates
    # ==================================================================

    def test_D01_no_unknown_orphan_templates(self):
        """Every rule/skill template file should be mapped or allowlisted."""
        mapped_templates = set(template_rel.split('/', 1)[1]
                               for _, template_rel, _ in self._template_pairs())
        template_files = set()
        for pattern in ('text_rule_*.*', 'text_skill_*.*'):
            template_files.update(p.name for p in self._templates_dir().glob(pattern))
        unknown = sorted(template_files - mapped_templates - KNOWN_ORPHANS)
        self.assertEqual(
            unknown,
            [],
            'Unknown orphan template files: {}'.format(', '.join(unknown)),
        )

    # ==================================================================
    # E. Generated marker is preserved where shipping depends on it
    # ==================================================================

    def test_E01_mapped_templates_and_skill_sources_have_marker(self):
        """Mapped templates and shipped skill sources should retain marker."""
        for source_rel, template_rel, _ in self._template_pairs():
            source_path = self._source_path(source_rel)
            if not source_path.is_file():
                continue
            template_path = self._template_path(template_rel)
            template_head = self._content_lines(template_path)[:3]
            self.assertTrue(
                any(GENERATED_MARKER in line for line in template_head),
                '{} missing generated marker near top'.format(template_rel),
            )

        # Mapped skill sources carry the marker by convention; rule sources do not.
        for dat_name, slug in self.embody_ext._TEMPLATE_MAP_SKILLS.items():
            source_rel = 'skills/{}/SKILL.md'.format(slug)
            source_path = self._source_path(source_rel)
            if not source_path.is_file():
                continue
            source_head = self._content_lines(source_path)[:3]
            self.assertTrue(
                any(GENERATED_MARKER in line for line in source_head),
                '{} missing generated marker near top'.format(source_rel),
            )
