"""
Test suite: the release smoke's `uninstall` leg (smoke_legs/uninstall.py).

Pure Python, TD-import-free: the leg is orchestrator-side code, loaded by
file path and driven against a scripted stand-in for the smoke TD -- a
fake clock, a fake Envoy port, and a REAL temp run directory holding the
files Uninstall touches. Inside TD every test skips.

What this pins, assertion by assertion, is that the PROOF is load-bearing.
For every claim the leg makes there is a fake uninstall that breaks it and
must turn the leg red:
- a user file deleted, or a user MCP server stripped out of .mcp.json;
- .embody/ or the .venv left behind; an externalized .tdxn removed;
- a 'review' item deleted; settings.local.json rewritten;
- a plan that omits a manifest-recorded path, or lists a user file;
- a plan rooted anywhere but the run dir (refused BEFORE anything runs);
- a summary that never appears, or says ran=False (the confirm cancelled);
- an Envoy that outlives its own uninstall;
- any change to a repo-checkout witness file.
Plus the contract: run() never raises, every seeded dialog title is a real
title in embody_admin.py, the uninstall is deferred through TD's own run()
(execute_python has no `run` in its namespace), and nothing quits TD.
"""

import hashlib
import importlib.util
import json
import os
import sys
import tempfile

runner_mod = op.unit_tests.op('TestRunnerExt').module
EmbodyTestCase = runner_mod.EmbodyTestCase

_IN_TD = 'td' in sys.modules

_DEV = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
_RT = os.path.join(_DEV, 'release_testing')
_ADMIN = os.path.join(_DEV, 'embody', 'Embody', 'embody_admin.py')

_MARKER = ('<!-- Generated by Embody/Envoy - Do not remove this comment - '
           'sha:%s -->\n')


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


if not _IN_TD:
    leg = _load('smoke_leg_uninstall_under_test',
                os.path.join(_RT, 'smoke_legs', 'uninstall.py'))


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def _read(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()


def _tree(root):
    """{relative posix path: sha256} for every file under root."""
    out = {}
    for base, _dirs, files in os.walk(root):
        for name in files:
            full = os.path.join(base, name)
            rel = os.path.relpath(full, root).replace('\\', '/')
            with open(full, 'rb') as f:
                out[rel] = hashlib.sha256(f.read()).hexdigest()
    return out


# ===========================================================================
# the scripted fake TouchDesigner
# ===========================================================================

class _FakeTD:
    """The smoke instance as the leg can observe it: a fake clock, a port
    that stops answering when Uninstall runs, the plan PreviewUninstall
    returns, and a fake executor that consumes that plan against the real
    temp run dir. Every recovery the leg checks is a switch a test flips."""

    # rel -> content. The install as the smoke leaves it.
    GENERATED = ('CLAUDE.md', 'AGENTS.md', '.claude/rules/embody-rule.md',
                 '.claude/skills/embody-skill/SKILL.md', '.embody/config.json')
    USER_KEPT = ('externalized/comp.tdxn', 'externalized/comp.tox',
                 'externalized/ext.py', 'externalizations.tsv',
                 'smoke_template.toe', 'logs/embody.log')
    VENV_FILES = ('.venv/pyvenv.cfg', '.venv/Scripts/python.exe')
    EMPTY_DIRS = ('.claude/skills/embody-skill', '.claude/skills',
                  '.claude/rules', '.claude')

    def __init__(self, run_dir, repo, port=9871, pid=4242):
        self.run_dir = run_dir
        self.repo = repo
        self.port = port
        self.pid = pid
        self.now = 1000.0
        self.budget_left = 3600.0
        self.project_folder = run_dir
        self.envoy_up = True
        self.scripts = []
        self.waits = []
        self.logs = []
        self.files = []          # every file this fake created
        # switches
        self.execute = True
        self.write_summary = True
        self.summary = {'ran': True, 'deleted': 9, 'stripped': 2,
                        'unset': 2, 'kept_review': 1, 'errors': 0}
        self.delete_user_file = False
        self.delete_user_rule = False
        self.tamper_user_file = False
        self.delete_tdxn = False
        self.keep_embody_dir = False
        self.keep_venv = False
        # Embody's own post-uninstall settings save, which mkdirs .embody/
        # again to write config.json. On by default: it is what really
        # happens, so the happy path has to tolerate it.
        self.reborn_config = True
        self.leave_state = ()
        self.reborn_manifest = False
        self.leave_planned = None
        self.strip_user_server = False
        self.remove_mcp_json = False
        self.delete_review = False
        self.mutate_settings = False
        self.append_settings = False
        self.touch_repo = False
        self.envoy_survives = False
        self.plan_omit = None
        self.plan_extra_delete = None
        self.plan_root = None
        self.wiring = {'style': 'Pulse', 'routers': ['parexec']}
        self._install()

    # --- the installed project ---------------------------------------

    def _put(self, rel, text):
        _write(os.path.join(self.run_dir, rel), text)
        if rel not in self.files:
            self.files.append(rel)

    def _install(self):
        for rel in self.GENERATED:
            self._put(rel, _MARKER % 'abc123' + 'generated %s\n' % rel)
        for rel in self.USER_KEPT:
            self._put(rel, 'user content for %s\n' % rel)
        for rel in self.VENV_FILES:
            self._put(rel, 'venv file\n')
        self._put('.gitignore', 'build/\n\n# Embody / Envoy (auto-managed)\n'
                                '.embody/\n')
        self._put('.mcp.json', json.dumps({'mcpServers': {'envoy': {
            'type': 'stdio', 'command': '.venv/python', 'args': []}}},
            indent=2) + '\n')
        self._put('.claude/settings.local.json', json.dumps(
            {'permissions': {'allow': ['mcp__envoy__query_network']}},
            indent=2) + '\n')
        self._put('.embody/config.json',
                  json.dumps({'version': 1, 'params': {}}, indent=2) + '\n')
        self._put('.embody/hashes.json', json.dumps({'CLAUDE.md': 'abc'}) + '\n')
        self._put('.embody/manifest.json', json.dumps({
            'version': 1,
            'files_created': list(self.GENERATED) + [
                '.mcp.json', '.claude/settings.local.json', 'gone.md'],
            'files_appended': [{'path': '.gitignore',
                                'marker': '# Embody / Envoy',
                                'kind': 'block'}],
            'git_config': ['diff.tdxn.textconv'],
            'venv': {'path': '.venv', 'created': True},
            'network_ops': []}, indent=2, sort_keys=True) + '\n')

    # --- the plan PreviewUninstall returns ----------------------------

    def plan(self):
        delete = [{'path': rel, 'kind': 'file', 'why': 'Embody-generated'}
                  for rel in self.GENERATED]
        delete.append({'path': '.venv', 'kind': 'dir', 'why': 'Embody venv'})
        delete.append({'path': '.embody', 'kind': 'dir',
                       'why': 'Embody runtime state'})
        delete += [{'path': rel, 'kind': 'emptydir', 'why': 'removed if empty'}
                   for rel in self.EMPTY_DIRS]
        if self.plan_extra_delete:
            delete.append({'path': self.plan_extra_delete, 'kind': 'file',
                           'why': 'injected by a test'})
        if self.plan_omit:
            delete = [e for e in delete if e['path'] != self.plan_omit]
        return {
            'root': self.plan_root or self.run_dir,
            'sources': ['manifest', 'fallback'],
            'delete': delete,
            'strip': [{'path': '.mcp.json', 'kind': 'mcp_config',
                       'marker': 'mcpServers.envoy', 'why': 'key only'},
                      {'path': '.gitignore', 'kind': 'block',
                       'marker': '# Embody / Envoy', 'why': 'block only'}],
            'unset': ['diff.tdxn.textconv', 'diff.tdxn.cachetextconv'],
            'review': [{'path': '.claude/settings.local.json',
                        'why': 'may hold your permission edits -- kept'}],
            'missing': ['gone.md'],
        }

    # --- the fake executor --------------------------------------------

    def _rm(self, rel):
        path = os.path.join(self.run_dir, rel)
        if os.path.isfile(path):
            os.remove(path)

    def _rm_dir(self, rel):
        """Remove the files this fake created under `rel`, then its
        directories deepest-first. Enumerated, never a recursive sweep."""
        prefix = rel.rstrip('/') + '/'
        dirs = set()
        for tracked in list(self.files):
            if tracked.startswith(prefix):
                self._rm(tracked)
                part = os.path.dirname(tracked)
                while part and part != rel:
                    dirs.add(part)
                    part = os.path.dirname(part)
        for part in sorted(dirs, key=lambda d: -d.count('/')) + [rel]:
            try:
                os.rmdir(os.path.join(self.run_dir, part))
            except OSError:
                pass

    def _rmdir_if_empty(self, rel):
        try:
            os.rmdir(os.path.join(self.run_dir, rel))
        except OSError:
            pass

    def uninstall(self):
        """What embody_admin.execute_uninstall_plan does, on this fixture."""
        plan = self.plan()
        for entry in plan['delete']:
            rel, kind = entry['path'], entry.get('kind')
            if rel == self.leave_planned or kind == 'emptydir':
                continue
            if rel == '.embody' and self.keep_embody_dir:
                continue
            if rel == '.venv' and self.keep_venv:
                continue
            if kind == 'dir':
                self._rm_dir(rel)
            else:
                self._rm(rel)
        if not self.keep_embody_dir:
            # the deferred _saveSettings landing one frame after the delete
            if self.reborn_config:
                _write(os.path.join(self.run_dir, '.embody/config.json'),
                       json.dumps({'version': 1, 'params': {
                           'Envoyenable': {'val': 0}}}, indent=2) + '\n')
            if self.reborn_manifest:
                _write(os.path.join(self.run_dir, '.embody/manifest.json'),
                       '{}\n')
            for rel in self.leave_state:
                _write(os.path.join(self.run_dir, rel), 'left behind\n')
        if self.remove_mcp_json:
            self._rm('.mcp.json')
        else:
            cfg = json.loads(_read(os.path.join(self.run_dir, '.mcp.json')))
            servers = cfg.get('mcpServers', {})
            servers.pop('envoy', None)
            if self.strip_user_server:
                servers.clear()
            _write(os.path.join(self.run_dir, '.mcp.json'),
                   json.dumps(cfg, indent=2) + '\n')
        _write(os.path.join(self.run_dir, '.gitignore'), 'build/\n')
        for rel in self.EMPTY_DIRS:
            self._rmdir_if_empty(rel)
        if self.delete_user_file:
            self._rm(leg.USER_FILE)
        if self.delete_user_rule:
            self._rm(leg.USER_RULE)
        if self.tamper_user_file:
            _write(os.path.join(self.run_dir, leg.USER_FILE),
                   leg.USER_NOTES_TEXT + 'appended by the uninstall\n')
        if self.delete_tdxn:
            self._rm('externalized/comp.tdxn')
        if self.delete_review:
            self._rm('.claude/settings.local.json')
        if self.mutate_settings or self.append_settings:
            path = os.path.join(self.run_dir, '.claude/settings.local.json')
            data = json.loads(_read(path))
            if self.mutate_settings:
                data.pop(leg.USER_SETTING, None)
            if self.append_settings:
                data['rewrittenByUninstall'] = True
            _write(path, json.dumps(data, indent=2) + '\n')
        if self.touch_repo:
            _write(os.path.join(self.repo, 'CLAUDE.md'),
                   'the smoke reached outside its run dir\n')
        if not self.envoy_survives:
            self.envoy_up = False
        if self.write_summary:
            _write(os.path.join(self.run_dir, leg.SUMMARY_FILE),
                   json.dumps(self.summary))

    # --- the ctx callables ---------------------------------------------

    def py(self, code, timeout=30):
        code = str(code)
        if 'result = project.folder' in code:
            return self.project_folder
        if 'PreviewUninstall' in code:
            return json.dumps(self.plan())
        if "_out['routers']" in code:
            return json.dumps(self.wiring)
        if 'from td import run as _run' in code:
            self.scripts.append(code)
            if self.execute:
                self.uninstall()
            return 'scheduled'
        if code.strip() == 'result = 1':
            if not self.envoy_up:
                raise RuntimeError('execute_python: connection refused')
            return '1'
        raise AssertionError('unscripted execute_python: %r' % code[:90])

    def call(self, name, arguments, timeout=30):
        raise AssertionError('the uninstall leg makes no tool calls: %s'
                             % name)

    def wait_for_flag(self, name, timeout, done):
        self.waits.append({'name': name, 'timeout': timeout})
        self.now += float(timeout)
        path = os.path.join(self.run_dir, name)
        if not os.path.isfile(path):
            return None, False
        text = _read(path)
        return text, bool(done(text))

    # --- the fake clock the leg's waits run on ------------------------

    def clock(self):
        return self.now

    def sleep(self, dt):
        self.now += max(float(dt), 0.001)

    def ctx(self):
        return {'run_dir': self.run_dir, 'repo': self.repo,
                'build': {'version': '6.2.57'},
                'installed': {'version': '6.2.57'}, 'upgrade_from': None,
                'port': self.port, 'set_port': lambda p: None,
                'pid': self.pid, 'td_exe': 'td.exe', 'platform': 'win32',
                'call': self.call, 'py': self.py,
                'log': self.logs.append,
                'budget': lambda: self.budget_left - (self.now - 1000.0),
                'wait_for_flag': self.wait_for_flag,
                '_seams': {'clock': self.clock, 'sleep': self.sleep}}


class _Case(EmbodyTestCase):

    def setUp(self):
        super().setUp()
        if _IN_TD:
            self.skipTest('pure-Python suite -- runs under pytest/CI only')
        self.root = tempfile.mkdtemp(prefix='embody_smoke_uninstall_')
        self.run_dir = os.path.join(self.root, 'run')
        self.repo = os.path.join(self.root, 'repo')
        os.makedirs(self.run_dir, exist_ok=True)
        for rel in ('CLAUDE.md', 'AGENTS.md', '.gitignore', '.gitattributes'):
            _write(os.path.join(self.repo, rel), 'checkout %s\n' % rel)
        self.td = _FakeTD(self.run_dir, self.repo)

    # helpers
    def go(self):
        self.result = leg.run(self.td.ctx())
        return self.result

    def step(self, name):
        for s in self.result['steps']:
            if s['step'] == name:
                return s
        return None

    def names(self):
        return [s['step'] for s in self.result['steps']]

    def assertStepOk(self, name):
        got = self.step(name)
        self.assertIsNotNone(got, '%s never ran: %s' % (name, self.names()))
        self.assertTrue(got['ok'], '%s failed: %s' % (name, got['detail']))

    def assertStepFailed(self, name):
        got = self.step(name)
        self.assertIsNotNone(got, '%s never ran: %s' % (name, self.names()))
        self.assertFalse(got['ok'], '%s unexpectedly passed: %s'
                         % (name, got['detail']))
        self.assertFalse(self.result['ok'], 'the leg reported ok anyway')

    def exists(self, rel):
        return os.path.exists(os.path.join(self.run_dir, rel))


# ===========================================================================
# the happy path
# ===========================================================================

class TestHappyPath(_Case):

    def test_a_faithful_uninstall_passes_every_step(self):
        res = self.go()
        self.assertTrue(res['ok'], 'leg failed: %s / %s'
                        % (res['error'], [s for s in res['steps']
                                          if not s['ok']]))
        self.assertEqual(res['error'], '')
        for name in ('leg.target', 'plant_user_content', 'repo_baseline',
                     'uninstall_button_wired', 'preview_plan',
                     'plan_root_is_run_dir', 'plan_covers_manifest',
                     'plan_removes_state_and_venv', 'plan_spares_user_files',
                     'leaves_td_running', 'uninstall_ran', 'envoy_stopped',
                     'generated_removed', 'user_files_intact',
                     'mcp_json_reversed', 'review_items_kept',
                     'settings_local_kept', 'venv_removed',
                     'embody_state_removed', 'untouched_paths_kept',
                     'outside_run_dir_untouched'):
            self.assertStepOk(name)

    def test_result_matches_the_leg_contract(self):
        res = self.go()
        self.assertEqual(sorted(res), ['error', 'ok', 'steps'])
        self.assertIsInstance(res['ok'], bool)
        for s in res['steps']:
            self.assertEqual(sorted(s), ['detail', 'ok', 'step'])
            self.assertIsInstance(s['ok'], bool)
            self.assertIsInstance(s['detail'], str)

    def test_the_planted_user_content_is_really_planted(self):
        self.go()
        self.assertTrue(self.exists(leg.USER_FILE))
        self.assertTrue(self.exists(leg.USER_RULE))
        self.assertEqual(_read(os.path.join(self.run_dir, leg.USER_RULE)),
                         leg.USER_RULE_TEXT)
        cfg = json.loads(_read(os.path.join(self.run_dir, '.mcp.json')))
        self.assertIn(leg.USER_SERVER, cfg['mcpServers'])

    def test_the_users_rules_directory_survives_its_emptydir_entry(self):
        """.claude/rules is PLANNED for removal and must stay, because the
        hand-written rule is still in it (a bare rmdir on a non-empty dir)."""
        self.go()
        self.assertTrue(self.exists('.claude/rules'))
        self.assertTrue(self.exists(leg.USER_RULE))
        self.assertStepOk('generated_removed')
        self.assertIn('kept dirs', self.step('generated_removed')['detail'])

    def test_the_skills_tree_that_empties_is_gone(self):
        self.go()
        self.assertFalse(self.exists('.claude/skills'))

    def test_externalized_files_and_the_toe_survive(self):
        self.go()
        for rel in ('externalized/comp.tdxn', 'externalized/comp.tox',
                    'externalized/ext.py', 'externalizations.tsv',
                    'smoke_template.toe'):
            self.assertTrue(self.exists(rel), '%s was removed' % rel)


# ===========================================================================
# the target gate and the plan's root -- nothing runs until both hold
# ===========================================================================

class TestSafetyFences(_Case):

    def test_a_port_serving_another_project_plants_nothing(self):
        self.td.project_folder = os.path.join(self.root, 'someone-else')
        os.makedirs(self.td.project_folder, exist_ok=True)
        res = self.go()
        self.assertStepFailed('leg.target')
        self.assertIn('refusing', res['error'])
        self.assertFalse(self.exists(leg.USER_FILE))
        self.assertEqual(self.td.scripts, [], 'it uninstalled anyway')
        self.assertEqual(self.names(), ['leg.target'])

    def test_an_unreadable_project_folder_fails_the_gate(self):
        def boom(code, timeout=30):
            raise RuntimeError('connection refused')
        self.td.py = boom
        self.go()
        self.assertStepFailed('leg.target')

    def test_a_plan_rooted_outside_the_run_dir_is_refused(self):
        before = _tree(self.repo)
        self.td.plan_root = self.repo
        res = self.go()
        self.assertStepFailed('plan_root_is_run_dir')
        self.assertIn('refusing to run Uninstall', res['error'])
        self.assertEqual(self.td.scripts, [], 'it uninstalled anyway')
        self.assertEqual(_tree(self.repo), before)

    def test_a_repo_witness_file_that_changes_fails_the_leg(self):
        self.td.touch_repo = True
        self.go()
        self.assertStepFailed('outside_run_dir_untouched')
        self.assertIn('CLAUDE.md', self.step(
            'outside_run_dir_untouched')['detail'])

    def test_missing_repo_witness_files_are_handled_not_crashed_on(self):
        """.mcp.json, .claude/settings.local.json and .embody/manifest.json
        are gitignored: absent on a fresh clone, and absent on both sides."""
        for rel in ('.mcp.json', '.claude/settings.local.json',
                    '.embody/manifest.json'):
            self.assertFalse(os.path.exists(os.path.join(self.repo, rel)))
        self.go()
        self.assertStepOk('repo_baseline')
        self.assertStepOk('outside_run_dir_untouched')

    def test_a_repo_with_no_witness_files_is_not_a_fence(self):
        self.td.repo = os.path.join(self.root, 'empty-repo')
        os.makedirs(self.td.repo, exist_ok=True)
        self.go()
        self.assertStepFailed('repo_baseline')

    def test_no_repo_in_ctx_skips_the_fence_without_failing(self):
        self.td.repo = ''
        self.go()
        self.assertStepOk('repo_baseline')
        self.assertIn('not available', self.step('repo_baseline')['detail'])

    def test_the_leg_writes_nothing_outside_the_run_dir(self):
        before = _tree(self.repo)
        self.td.execute = False
        self.go()
        self.assertEqual(_tree(self.repo), before)

    def test_the_leg_itself_creates_only_its_planted_files(self):
        self.td.execute = False       # nothing deleted: the delta is the leg's
        before = _tree(self.run_dir)
        self.go()
        after = _tree(self.run_dir)
        self.assertEqual(sorted(set(after) - set(before)),
                         [leg.USER_RULE, leg.USER_FILE])
        self.assertEqual(sorted(set(before) - set(after)), [])
        changed = sorted(k for k in before if before[k] != after.get(k))
        self.assertEqual(changed, ['.claude/settings.local.json',
                                   '.mcp.json'])


# ===========================================================================
# the plan is the manifest's, not a hand-list
# ===========================================================================

class TestPlanIsManifestDerived(_Case):

    def test_a_plan_that_omits_a_recorded_file_fails(self):
        self.td.plan_omit = 'CLAUDE.md'
        self.go()
        self.assertStepFailed('plan_covers_manifest')
        self.assertIn('claude.md', self.step(
            'plan_covers_manifest')['detail'].lower())

    def test_a_recorded_file_already_gone_counts_as_accounted_for(self):
        """'gone.md' is in files_created and in the plan's `missing`."""
        self.go()
        self.assertStepOk('plan_covers_manifest')

    def test_an_appended_shared_file_must_be_in_the_plan(self):
        self.td.plan_omit = None
        plan = self.td.plan()
        self.assertIn('.gitignore', [e['path'] for e in plan['strip']])
        self.go()
        self.assertStepOk('plan_covers_manifest')

    def test_a_plan_that_forgets_the_venv_fails(self):
        self.td.plan_omit = '.venv'
        self.go()
        self.assertStepFailed('plan_removes_state_and_venv')

    def test_a_plan_that_forgets_the_embody_state_fails(self):
        self.td.plan_omit = '.embody'
        self.go()
        self.assertStepFailed('plan_removes_state_and_venv')

    def test_a_plan_that_lists_a_user_file_fails(self):
        self.td.plan_extra_delete = leg.USER_FILE
        self.go()
        self.assertStepFailed('plan_spares_user_files')

    def test_a_plan_that_lists_the_hand_written_rule_fails(self):
        self.td.plan_extra_delete = leg.USER_RULE
        self.go()
        self.assertStepFailed('plan_spares_user_files')

    def test_an_empty_plan_fails_the_preview(self):
        self.td.plan = lambda: {'root': self.run_dir, 'sources': [],
                                'delete': [], 'strip': [], 'unset': [],
                                'review': [], 'missing': []}
        self.go()
        self.assertStepFailed('preview_plan')

    def test_a_missing_manifest_is_reported_not_raised(self):
        os.remove(os.path.join(self.run_dir, '.embody', 'manifest.json'))
        res = self.go()
        self.assertFalse(res['ok'])
        self.assertIn('manifest.json', res['error'])
        self.assertEqual(res['steps'], [])
        self.assertFalse(self.exists(leg.USER_FILE))


# ===========================================================================
# what Uninstall must NOT touch
# ===========================================================================

class TestUserContentSurvives(_Case):

    def test_a_deleted_user_file_fails_the_leg(self):
        self.td.delete_user_file = True
        self.go()
        self.assertStepFailed('user_files_intact')
        self.assertIn(leg.USER_FILE, self.step('user_files_intact')['detail'])

    def test_a_deleted_hand_written_rule_fails_the_leg(self):
        self.td.delete_user_rule = True
        self.go()
        self.assertStepFailed('user_files_intact')

    def test_a_user_file_rewritten_in_place_fails_the_leg(self):
        """Not removed, appended to -- the hash is taken before Uninstall
        precisely so an in-place edit cannot read as untouched."""
        self.td.tamper_user_file = True
        self.go()
        self.assertStepFailed('user_files_intact')
        self.assertTrue(self.exists(leg.USER_FILE))

    def test_a_removed_externalized_tdxn_fails_the_leg(self):
        self.td.delete_tdxn = True
        self.go()
        self.assertStepFailed('untouched_paths_kept')
        self.assertIn('comp.tdxn',
                      self.step('untouched_paths_kept')['detail'])

    def test_a_deleted_review_item_fails_the_leg(self):
        self.td.delete_review = True
        self.go()
        self.assertStepFailed('review_items_kept')

    def test_a_settings_file_stripped_of_the_user_key_fails_the_leg(self):
        self.td.mutate_settings = True
        self.go()
        self.assertStepFailed('settings_local_kept')

    def test_a_settings_file_rewritten_around_the_user_key_fails_the_leg(self):
        """'review' means untouched, not "your key is still in there": a
        rewrite that keeps the key but changes the file is still a change."""
        self.td.append_settings = True
        self.go()
        self.assertStepFailed('settings_local_kept')
        self.assertIn('byte-identical=False',
                      self.step('settings_local_kept')['detail'])

    def test_a_missing_settings_file_is_reported_and_its_check_skipped(self):
        os.remove(os.path.join(self.run_dir,
                               '.claude/settings.local.json'))
        self.td.plan_omit = None
        self.go()
        self.assertStepFailed('plant_user_content')
        self.assertIn('settings.local.json',
                      self.step('plant_user_content')['detail'])
        self.assertIsNone(self.step('settings_local_kept'),
                          'it asserted on a file it never planted')


# ===========================================================================
# what Uninstall must reverse
# ===========================================================================

class TestFootprintIsReversed(_Case):

    def test_a_user_mcp_server_stripped_with_envoy_fails_the_leg(self):
        self.td.strip_user_server = True
        self.go()
        self.assertStepFailed('mcp_json_reversed')

    def test_a_deleted_mcp_json_fails_the_leg(self):
        self.td.remove_mcp_json = True
        self.go()
        self.assertStepFailed('mcp_json_reversed')
        self.assertIn('gone', self.step('mcp_json_reversed')['detail'])

    def test_an_envoy_entry_left_behind_fails_the_leg(self):
        def keep_envoy():
            _FakeTD.uninstall(self.td)
            path = os.path.join(self.run_dir, '.mcp.json')
            cfg = json.loads(_read(path))
            cfg['mcpServers']['envoy'] = {'command': 'still here'}
            _write(path, json.dumps(cfg, indent=2) + '\n')
        self.td.uninstall = keep_envoy
        self.go()
        self.assertStepFailed('mcp_json_reversed')

    def test_an_embody_state_directory_left_behind_fails_the_leg(self):
        """The state step owns this: .embody/ is allowed to come BACK (the
        settings save), so only its surviving contents can condemn it."""
        self.td.keep_embody_dir = True
        self.go()
        self.assertStepFailed('embody_state_removed')
        self.assertIn('manifest.json',
                      self.step('embody_state_removed')['detail'])

    def test_a_venv_left_behind_fails_the_leg(self):
        self.td.keep_venv = True
        self.go()
        self.assertStepFailed('venv_removed')

    def test_embodys_own_post_uninstall_settings_save_is_not_a_failure(self):
        """Envoyenable=0 fires parexec -> _deferSaveSettings, which lands
        one frame AFTER the delete and mkdirs .embody/ for config.json.
        Reported in the detail, not counted as a removal that failed."""
        self.go()
        self.assertTrue(self.exists('.embody/config.json'))
        self.assertStepOk('embody_state_removed')
        self.assertStepOk('generated_removed')
        self.assertIn('re-created',
                      self.step('embody_state_removed')['detail'])

    def test_a_surviving_install_record_fails_the_leg(self):
        self.td.reborn_manifest = True
        self.go()
        self.assertStepFailed('embody_state_removed')

    def test_any_other_surviving_state_file_fails_the_leg(self):
        self.td.leave_state = ('.embody/hashes.json',)
        self.go()
        self.assertStepFailed('embody_state_removed')
        self.assertIn('hashes.json',
                      self.step('embody_state_removed')['detail'])

    def test_a_generated_file_left_behind_fails_the_leg(self):
        self.td.leave_planned = 'AGENTS.md'
        self.go()
        self.assertStepFailed('generated_removed')
        self.assertIn('AGENTS.md', self.step('generated_removed')['detail'])

    def test_an_envoy_that_outlives_its_own_uninstall_fails_the_leg(self):
        self.td.envoy_survives = True
        self.go()
        self.assertStepFailed('envoy_stopped')

    def test_the_envoy_probe_is_bounded_by_the_budget(self):
        """A live Envoy plus a spent budget must not eat the teardown
        window: the probe gives up at the reserve, not at its own ceiling."""
        self.td.envoy_survives = True
        self.td.budget_left = leg.TEARDOWN_RESERVE_S
        down = leg.envoy_is_down(self.td.ctx(), timeout=10000.0,
                                 clock=self.td.clock, sleep=self.td.sleep)
        self.assertFalse(down)
        self.assertEqual(self.td.now, 1000.0, 'it slept past the reserve')

    def test_the_envoy_probe_stops_at_its_own_ceiling(self):
        self.td.envoy_survives = True
        down = leg.envoy_is_down(self.td.ctx(), timeout=20.0,
                                 clock=self.td.clock, sleep=self.td.sleep)
        self.assertFalse(down)
        self.assertLessEqual(self.td.now, 1000.0 + 22.0)


# ===========================================================================
# the summary hand-off -- Envoy dies mid-uninstall
# ===========================================================================

class TestSummaryHandoff(_Case):

    def test_a_summary_that_never_appears_fails_with_a_named_error(self):
        self.td.write_summary = False
        self.go()
        self.assertStepFailed('uninstall_ran')
        detail = self.step('uninstall_ran')['detail']
        self.assertIn(leg.SUMMARY_FILE, detail)
        self.assertIn(self.run_dir, detail)

    def test_a_cancelled_uninstall_fails_the_leg(self):
        """The confirm dialog answered -1/Cancel: ran=False, nothing done."""
        self.td.summary = {'ran': False, 'reason': 'cancelled'}
        self.td.execute = True
        self.td.uninstall = lambda: _write(
            os.path.join(self.run_dir, leg.SUMMARY_FILE),
            json.dumps(self.td.summary))
        self.go()
        self.assertStepFailed('uninstall_ran')
        self.assertIn('cancelled', self.step('uninstall_ran')['detail'])

    def test_a_handler_that_raised_fails_the_leg(self):
        self.td.summary = {'error': 'RuntimeError: boom'}
        self.go()
        self.assertStepFailed('uninstall_ran')
        self.assertIn('boom', self.step('uninstall_ran')['detail'])

    def test_an_unparsable_summary_fails_the_leg(self):
        self.td.execute = True

        def junk():
            _FakeTD.uninstall(self.td)
            _write(os.path.join(self.run_dir, leg.SUMMARY_FILE),
                   'not json at all }')
        self.td.uninstall = junk
        self.go()
        self.assertStepFailed('uninstall_ran')

    def test_the_summary_wait_leaves_room_for_teardown(self):
        self.td.budget_left = 90.0
        self.go()
        wait = [w for w in self.td.waits if w['name'] == leg.SUMMARY_FILE][0]
        self.assertLessEqual(wait['timeout'],
                             90.0 - leg.TEARDOWN_RESERVE_S + 0.01)
        self.assertGreaterEqual(wait['timeout'], 5.0)

    def test_the_summary_wait_is_capped_even_with_a_huge_budget(self):
        self.td.budget_left = 100000.0
        self.go()
        wait = [w for w in self.td.waits if w['name'] == leg.SUMMARY_FILE][0]
        self.assertEqual(wait['timeout'], float(leg.SUMMARY_TIMEOUT_S))

    def test_an_exhausted_budget_still_waits_a_little(self):
        self.td.budget_left = 1.0
        self.go()
        wait = [w for w in self.td.waits if w['name'] == leg.SUMMARY_FILE][0]
        self.assertEqual(wait['timeout'], 5.0)


# ===========================================================================
# how the leg drives the product
# ===========================================================================

class TestDriversAndContract(_Case):

    def test_the_uninstall_is_deferred_through_tds_own_run(self):
        """`run` is not in execute_python's namespace (EnvoyExt.
        _execNamespace), and the reply would die with the server anyway."""
        self.go()
        sent = self.td.scripts[-1]
        self.assertIn('from td import run as _run', sent)
        self.assertIn('delayMilliSeconds=', sent)

    def test_it_calls_the_handler_the_uninstall_button_calls(self):
        script = leg.uninstall_script()
        self.assertIn('uninstallHandler', script)
        self.assertNotIn('_executeUninstallPlan', script)
        self.assertNotIn('remove_tree_within', script)

    def test_the_script_never_quits_touchdesigner(self):
        self.assertNotIn('quit', leg.uninstall_script())
        self.go()
        self.assertStepOk('leaves_td_running')
        self.assertIn('close/force', self.step('leaves_td_running')['detail'])

    def test_a_script_that_quits_td_fails_the_leg(self):
        """The orchestrator's teardown runs after this leg and reports on
        the pid: a leg that takes TD down leaves it nothing to end."""
        original = leg.uninstall_script
        self.addCleanup(setattr, leg, 'uninstall_script', original)
        leg.uninstall_script = lambda *a, **k: (
            original(*a, **k) + "project.quit(force=True)\n")
        self.go()
        self.assertStepFailed('leaves_td_running')

    def test_the_summary_is_written_atomically_into_the_project_folder(self):
        script = leg.uninstall_script()
        self.assertIn('os.path.join(project.folder', script)
        self.assertIn("os.replace(_dest + '.tmp', _dest)", script)

    def test_every_seeded_dialog_title_is_a_real_title_in_the_product(self):
        source = _read(_ADMIN)
        for title in leg.DIALOG_RESPONSES:
            if title == leg.SMOKE_SENTINEL:
                continue
            self.assertIn("'%s'" % title, source,
                          '%r is not a ui.messageBox title in '
                          'embody_admin.py' % title)

    def test_every_uninstall_dialog_in_the_product_is_seeded(self):
        """The titles embody_admin.uninstall_handler can raise. An unseeded
        one returns -1 (a cancel), which is a silent red."""
        source = _read(_ADMIN)
        start = source.index('def uninstall_handler')
        body = source[start:start + 3000]
        titles = {"'Embody -- Uninstall'", "'Embody -- Uninstall Complete'"}
        for title in titles:
            self.assertIn(title, body)
            self.assertIn(title.strip("'"), leg.DIALOG_RESPONSES)

    def test_the_seed_merges_and_keeps_the_bootstrap_sentinel(self):
        script = leg.uninstall_script()
        self.assertIn('_seed.update(', script)
        self.assertIn('_smoke_test_responses', script)
        self.assertIn(leg.SMOKE_SENTINEL, script)
        self.assertIn("'Embody -- Uninstall': 1", script)

    def test_an_unwired_uninstall_button_fails_the_leg(self):
        self.td.wiring = {'style': 'Pulse', 'routers': []}
        self.go()
        self.assertStepFailed('uninstall_button_wired')
        self.assertIn('NOTHING',
                      self.step('uninstall_button_wired')['detail'])

    def test_a_non_pulse_uninstall_parameter_fails_the_leg(self):
        self.td.wiring = {'style': 'Toggle', 'routers': ['parexec']}
        self.go()
        self.assertStepFailed('uninstall_button_wired')

    def test_run_never_raises_when_the_transport_dies(self):
        calls = {'n': 0}
        real = self.td.py

        def flaky(code, timeout=30):
            calls['n'] += 1
            if 'PreviewUninstall' in code:
                raise RuntimeError('connection reset by peer')
            return real(code, timeout)
        self.td.py = flaky
        res = self.go()
        self.assertFalse(res['ok'])
        self.assertIn('connection reset', res['error'])
        self.assertTrue(res['steps'], 'the partial evidence was dropped')

    def test_run_never_raises_when_the_plan_is_not_json(self):
        real = self.td.py

        def junk(code, timeout=30):
            if 'PreviewUninstall' in code:
                return 'not json'
            return real(code, timeout)
        self.td.py = junk
        res = self.go()
        self.assertFalse(res['ok'])
        self.assertIn('JSONDecodeError', res['error'])

    def test_run_never_raises_when_the_run_dir_disappears(self):
        real_listdir = os.listdir

        def boom(path):
            raise OSError('vanished')
        os.listdir = boom
        try:
            res = self.go()
        finally:
            os.listdir = real_listdir
        self.assertFalse(res['ok'])
        self.assertIn('vanished', res['error'])

    def test_the_leg_makes_no_mcp_tool_calls_after_the_uninstall(self):
        """ctx['call'] raises in this fixture: the only traffic after
        Uninstall is the liveness probe, which is expected to fail."""
        res = self.go()
        self.assertTrue(res['ok'], res['error'])
