#!/usr/bin/env python3
"""
Envoy Bridge — STDIO-to-HTTP proxy and TD launcher for the Envoy MCP server.

Bridges Claude Code's STDIO MCP transport to Envoy's Streamable HTTP
endpoint inside TouchDesigner, providing automatic retry, reconnection,
crash detection, and TD launch/restart via bridge meta-tools.

Usage:
    python3 -u envoy_bridge.py [--port PORT] [--config PATH]

Generated by Embody. Regenerated on each Envoy start — do not hand-edit.
"""

import json
import os
import signal
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request

DEFAULT_PORT = 9870
RETRY_INTERVALS = [0.5, 0.5, 1, 1, 2, 2, 3, 3, 5, 5, 8, 8]
CONNECT_TIMEOUT_S = 60  # Max seconds to wait for Envoy on first connect
ORPHAN_CHECK_INTERVAL_S = 30  # How often to check if parent process is alive
CRASH_LOOP_WINDOW_S = 300  # 5 minutes
CRASH_LOOP_MAX = 3  # Max launches within the window

# ---------------------------------------------------------------------------
# Bridge meta-tools — handled locally, work even when TD is down
# ---------------------------------------------------------------------------

BRIDGE_TOOLS = [
    {
        "name": "get_td_status",
        "description": (
            "Check if TouchDesigner is running and Envoy is reachable. "
            "Returns connection state, crash detection, process liveness, "
            "and project config. Works even when TD is down."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": [],
        },
    },
    {
        "name": "launch_td",
        "description": (
            "Launch TouchDesigner with the project's .toe file. "
            "Use to start TD for the first time or restart after a crash. "
            "Waits for Envoy to become reachable before returning."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeout": {
                    "type": "integer",
                    "description": (
                        "Max seconds to wait for Envoy to become reachable "
                        "after launch (default: 120)"
                    ),
                    "default": 120,
                },
            },
            "required": [],
        },
    },
    {
        "name": "restart_td",
        "description": (
            "Quit TouchDesigner gracefully and relaunch with the project's "
            ".toe file. Waits for the process to exit before relaunching. "
            "Use when TD is running but needs a fresh start."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "timeout": {
                    "type": "integer",
                    "description": (
                        "Max seconds to wait for Envoy to become reachable "
                        "after relaunch (default: 120)"
                    ),
                    "default": 120,
                },
            },
            "required": [],
        },
    },
    {
        "name": "switch_instance",
        "description": (
            "Switch the active TouchDesigner instance or list all registered "
            "instances. Omit the instance parameter to list available "
            "instances with their status. Provide an instance name (toe "
            "basename) to switch the bridge to that instance."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "instance": {
                    "type": "string",
                    "description": (
                        "Instance name to switch to (toe basename without "
                        ".toe extension). Omit to list all instances."
                    ),
                },
            },
            "required": [],
        },
    },
]

BRIDGE_TOOL_NAMES = {t["name"] for t in BRIDGE_TOOLS}


_log_file = None


def _init_file_logging(config_path):
    """Open a log file next to the config (e.g. dev/logs/envoy-bridge.log)."""
    global _log_file
    if _log_file is not None:
        return
    try:
        if config_path:
            log_dir = os.path.join(os.path.dirname(config_path), "dev", "logs")
        else:
            log_dir = os.path.join(os.getcwd(), "dev", "logs")
        if os.path.isdir(log_dir):
            path = os.path.join(log_dir, "envoy-bridge.log")
            _log_file = open(path, "a", encoding="utf-8")
    except OSError:
        pass  # File logging is best-effort


def log(msg):
    """Log to stderr (visible in Claude Code's MCP output) and to file."""
    ts = time.strftime("%H:%M:%S")
    line = f"[envoy-bridge] {ts} {msg}"
    sys.stderr.write(line + "\n")
    sys.stderr.flush()
    if _log_file is not None:
        try:
            _log_file.write(line + "\n")
            _log_file.flush()
        except OSError:
            pass


def parse_args():
    port = DEFAULT_PORT
    config_path = None
    args = sys.argv[1:]
    for i, arg in enumerate(args):
        if arg == "--port" and i + 1 < len(args):
            port = int(args[i + 1])
        elif arg == "--config" and i + 1 < len(args):
            config_path = args[i + 1]
    return port, config_path


def load_config(config_path):
    """Load .envoy.json config. Returns dict (possibly empty)."""
    if not config_path or not os.path.exists(config_path):
        return {}
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        log(f"Warning: could not read config {config_path}: {e}")
        return {}


def resolve_toe_path(config, config_path):
    """Resolve the .toe path from config (relative to git root)."""
    toe = config.get("toe_path")
    if not toe:
        return None
    if os.path.isabs(toe):
        return toe
    # Config sits at git root — resolve relative to its directory
    if config_path:
        git_root = os.path.dirname(os.path.abspath(config_path))
        return os.path.join(git_root, toe)
    return toe


# ---------------------------------------------------------------------------
# Process management
# ---------------------------------------------------------------------------

def find_td_pid():
    """Find the PID of a running TouchDesigner process. Returns int or None."""
    if sys.platform == "win32":
        try:
            result = subprocess.run(
                ["tasklist", "/FI", "IMAGENAME eq TouchDesigner*",
                 "/FO", "CSV", "/NH"],
                capture_output=True, text=True, timeout=5,
            )
            for line in result.stdout.strip().split("\n"):
                if "TouchDesigner" in line:
                    parts = line.strip('"').split('","')
                    if len(parts) >= 2:
                        return int(parts[1])
        except (subprocess.TimeoutExpired, FileNotFoundError, ValueError):
            pass
        return None

    # macOS / Linux
    try:
        result = subprocess.run(
            ["pgrep", "-f", "TouchDesigner"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            for line in result.stdout.strip().split("\n"):
                pid = int(line.strip())
                # Verify it's actually TD, not this bridge script
                if pid != os.getpid():
                    return pid
    except (subprocess.TimeoutExpired, FileNotFoundError, ValueError):
        pass
    return None


def is_process_alive(pid):
    """Check if a process is still running."""
    if not pid or pid <= 0:
        return False
    if sys.platform == "win32":
        # os.kill(pid, 0) on Windows calls TerminateProcess() — it KILLS the
        # process instead of checking liveness.  Use OpenProcess(SYNCHRONIZE)
        # which only requires the right to wait on the object.
        try:
            import ctypes
            kernel32 = ctypes.windll.kernel32
            SYNCHRONIZE = 0x00100000
            handle = kernel32.OpenProcess(SYNCHRONIZE, False, pid)
            if handle:
                kernel32.CloseHandle(handle)
                return True
            return False
        except Exception:
            return False
    # Unix: signal 0 is a no-op liveness check
    try:
        os.kill(pid, 0)
        return True
    except (ProcessLookupError, PermissionError):
        return False
    except OSError:
        return False


def ping_envoy_port(port):
    """Check if an Envoy server is listening on the given port.
    Returns True if something responds, False otherwise."""
    if port is None:
        return False
    import socket
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1)
            return s.connect_ex(('127.0.0.1', int(port))) == 0
    except (OSError, ValueError):
        return False


def get_instance_status(config):
    """Read the instance registry from config and check reachability.
    Returns (instances_with_status: dict, active_name: str|None)."""
    instances = config.get("instances", {})
    active = config.get("active")
    result = {}
    for name, info in instances.items():
        pid = info.get("td_pid")
        pid_alive = is_process_alive(pid)
        port_open = ping_envoy_port(info.get("port"))
        # An instance is only reachable if its own PID is alive AND its port
        # responds.  A dead PID with an open port means a different instance
        # owns that port — this entry is stale.
        reachable = pid_alive and port_open
        result[name] = {
            "toe_path": info.get("toe_path", ""),
            "port": info.get("port"),
            "td_pid": pid,
            "reachable": reachable,
            "active": name == active,
        }
    return result, active


def atomic_write_json(path, data):
    """Write JSON atomically via temp file + os.replace().
    Retries on PermissionError (Windows file-in-use)."""
    tmp = path + ".tmp"
    content = json.dumps(data, indent=2) + "\n"
    for attempt in range(3):
        try:
            with open(tmp, "w", encoding="utf-8") as f:
                f.write(content)
            os.replace(tmp, path)
            return
        except PermissionError:
            if attempt < 2:
                time.sleep(0.1)
            else:
                raise


def quit_td(pid, graceful_timeout=15):
    """Quit a running TouchDesigner process.

    Sends a graceful termination first, then force-kills if needed.
    Returns (success: bool, message: str).
    """
    if pid is None:
        return False, "No TouchDesigner PID to quit"
    if not is_process_alive(pid):
        return True, "TouchDesigner already exited"

    # Graceful quit
    try:
        if sys.platform == "darwin":
            subprocess.run(
                ["osascript", "-e", 'quit app "TouchDesigner"'],
                capture_output=True, timeout=10,
            )
        elif sys.platform == "win32":
            subprocess.run(
                ["taskkill", "/PID", str(pid)],
                capture_output=True, timeout=10,
            )
        else:
            os.kill(pid, signal.SIGTERM)
    except (subprocess.TimeoutExpired, OSError) as e:
        log(f"Graceful quit failed: {e}")

    # Wait for exit
    deadline = time.monotonic() + graceful_timeout
    while time.monotonic() < deadline:
        if not is_process_alive(pid):
            return True, f"TouchDesigner (PID {pid}) exited gracefully"
        time.sleep(0.5)

    # Force kill
    log(f"TouchDesigner (PID {pid}) did not exit gracefully, force killing")
    try:
        if sys.platform == "win32":
            subprocess.run(
                ["taskkill", "/F", "/PID", str(pid)],
                capture_output=True, timeout=10,
            )
        else:
            os.kill(pid, signal.SIGKILL)
    except (subprocess.TimeoutExpired, OSError) as e:
        return False, f"Failed to kill TouchDesigner (PID {pid}): {e}"

    # Brief wait after force kill
    time.sleep(1)
    if is_process_alive(pid):
        return False, f"TouchDesigner (PID {pid}) could not be terminated"

    return True, f"TouchDesigner (PID {pid}) was force-killed"


def launch_td(config, config_path):
    """Launch TouchDesigner with the configured .toe file.

    Returns (success: bool, message: str, pid: int|None).
    """
    td_exe = config.get("td_executable")
    if not td_exe:
        return False, "No td_executable configured in .envoy.json", None

    toe_path = resolve_toe_path(config, config_path)
    if not toe_path:
        return False, "No toe_path configured in .envoy.json", None

    # Validate paths
    if sys.platform == "darwin":
        # On macOS, td_executable is the .app bundle path
        if not os.path.exists(td_exe):
            return (False,
                    f"TouchDesigner not found at {td_exe}. "
                    "Install this version or update td_executable in .envoy.json",
                    None)
    else:
        if not os.path.isfile(td_exe):
            return (False,
                    f"TouchDesigner executable not found at {td_exe}. "
                    "Install this version or update td_executable in .envoy.json",
                    None)

    if not os.path.isfile(toe_path):
        return (False,
                f"Project file not found: {toe_path}",
                None)

    # Launch TD
    log(f"Launching TouchDesigner: {td_exe} with {toe_path}")
    try:
        if sys.platform == "darwin":
            proc = subprocess.Popen(
                ["open", "-a", td_exe, toe_path],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            # 'open' returns immediately; TD process is spawned by LaunchServices.
            # Wait briefly for open to finish, then find TD's actual PID.
            proc.wait(timeout=10)
            time.sleep(2)  # Give TD a moment to start
            pid = find_td_pid()
        elif sys.platform == "win32":
            proc = subprocess.Popen(
                [td_exe, toe_path],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            pid = proc.pid
        else:
            proc = subprocess.Popen(
                [td_exe, toe_path],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            pid = proc.pid

        return True, f"TouchDesigner launched (PID {pid})", pid

    except Exception as e:
        return False, f"Failed to launch TouchDesigner: {e}", None


# ---------------------------------------------------------------------------
# Meta-tool handlers
# ---------------------------------------------------------------------------

def handle_get_td_status(state):
    """Handle the get_td_status meta-tool."""
    # Refresh process liveness
    alive = is_process_alive(state["td_pid"])
    if state["td_pid"] and not alive:
        state["crash_detected"] = True

    last_ts = None
    if state["last_connected_time"] is not None:
        last_ts = time.strftime(
            "%Y-%m-%dT%H:%M:%SZ", time.gmtime(state["last_connected_time"]))

    remaining = CRASH_LOOP_MAX - len([
        t for t in state["launch_timestamps"]
        if t > time.monotonic() - CRASH_LOOP_WINDOW_S
    ])

    # Include instance registry with reachability
    config = load_config(state["config_path"])
    instance_status, active_name = get_instance_status(config)

    return {
        "connected": state["connected"],
        "td_process_alive": alive,
        "crash_detected": state["crash_detected"],
        "last_connected": last_ts,
        "td_executable": config.get("td_executable", ""),
        "restart_attempts_remaining": max(0, remaining),
        "active_instance": active_name,
        "instances": instance_status,
    }


def handle_switch_instance(params, state):
    """Handle the switch_instance meta-tool."""
    config = load_config(state["config_path"])
    instance_status, active_name = get_instance_status(config)

    target = params.get("instance")

    # List mode: no target specified
    if not target:
        return {
            "status": "list",
            "active_instance": active_name,
            "instances": instance_status,
        }

    # Switch mode: target specified
    if target not in config.get("instances", {}):
        return {
            "status": "error",
            "message": f'Instance "{target}" not found in registry.',
            "available": list(instance_status.keys()),
        }

    info = config["instances"][target]
    target_port = info.get("port")

    # Verify the target instance is reachable
    if not ping_envoy_port(target_port):
        return {
            "status": "error",
            "message": (
                f'Instance "{target}" (port {target_port}) is not reachable. '
                "Is TouchDesigner running with Envoy enabled?"
            ),
        }

    # Switch the bridge's in-memory state
    old_active = active_name
    state["url"] = f"http://localhost:{target_port}/mcp"
    state["connected"] = False  # Force reconnect + initialize handshake
    config_pid = info.get("td_pid")
    if config_pid and is_process_alive(config_pid):
        state["td_pid"] = config_pid
    else:
        state["td_pid"] = find_td_pid()
    state["crash_detected"] = False
    state["config"] = config

    # Update active in registry
    config["active"] = target
    if state["config_path"]:
        try:
            atomic_write_json(state["config_path"], config)
        except Exception as e:
            log(f"Warning: could not update .envoy.json: {e}")

    log(f"Switched from '{old_active}' to '{target}' (port {target_port})")

    return {
        "status": "success",
        "message": f'Switched to instance "{target}" on port {target_port}.',
        "instance": target,
        "port": target_port,
        "toe_path": info.get("toe_path", ""),
    }


def handle_launch_td(params, state):
    """Handle the launch_td meta-tool."""
    timeout = params.get("timeout", 120)

    # Safety: check if TD is already running
    existing_pid = find_td_pid()
    if existing_pid and is_process_alive(existing_pid):
        return {
            "status": "error",
            "message": (
                f"TouchDesigner is already running (PID {existing_pid}). "
                "Close it first or use get_td_status to check its state."
            ),
        }

    # Crash-loop guard
    now = time.monotonic()
    recent = [t for t in state["launch_timestamps"]
              if t > now - CRASH_LOOP_WINDOW_S]
    if len(recent) >= CRASH_LOOP_MAX:
        return {
            "status": "error",
            "message": (
                f"TouchDesigner has crashed {CRASH_LOOP_MAX} times in the "
                f"last {CRASH_LOOP_WINDOW_S // 60} minutes. Something may be "
                "wrong with the project. Ask the user to investigate."
            ),
        }

    # Launch
    success, message, pid = launch_td(state["config"], state["config_path"])
    if not success:
        return {"status": "error", "message": message}

    state["td_pid"] = pid
    state["crash_detected"] = False
    state["launch_timestamps"].append(time.monotonic())
    log(message)

    # Wait for Envoy to become reachable
    url = state["url"]
    deadline = time.monotonic() + timeout
    if wait_for_envoy(url, deadline):
        state["connected"] = True
        state["last_connected_time"] = time.time()
        log("Envoy is reachable after TD launch")
        return {
            "status": "success",
            "message": f"TouchDesigner launched and Envoy is ready. PID: {pid}",
        }
    else:
        return {
            "status": "partial",
            "message": (
                f"TouchDesigner launched (PID {pid}) but Envoy not reachable "
                f"after {timeout}s. TD may still be loading — Embody needs "
                "~75 frames to complete restoration."
            ),
        }


def handle_restart_td(params, state):
    """Handle the restart_td meta-tool."""
    timeout = params.get("timeout", 120)

    # Find and quit the running TD process
    pid = find_td_pid()
    if not pid or not is_process_alive(pid):
        return {
            "status": "error",
            "message": (
                "TouchDesigner is not running. Use launch_td to start it."
            ),
        }

    log(f"Restarting TouchDesigner (PID {pid})")
    success, quit_msg = quit_td(pid)
    log(quit_msg)
    if not success:
        return {"status": "error", "message": quit_msg}

    # Clear connection state
    state["connected"] = False
    state["td_pid"] = None
    state["crash_detected"] = False

    # Launch fresh
    success, launch_msg, new_pid = launch_td(state["config"],
                                              state["config_path"])
    if not success:
        return {"status": "error", "message": launch_msg}

    state["td_pid"] = new_pid
    state["launch_timestamps"].append(time.monotonic())
    log(launch_msg)

    # Wait for Envoy to become reachable
    url = state["url"]
    deadline = time.monotonic() + timeout
    if wait_for_envoy(url, deadline):
        state["connected"] = True
        state["last_connected_time"] = time.time()
        log("Envoy is reachable after TD restart")
        return {
            "status": "success",
            "message": (
                f"TouchDesigner restarted and Envoy is ready. "
                f"Old PID: {pid}, New PID: {new_pid}"
            ),
        }
    else:
        return {
            "status": "partial",
            "message": (
                f"TouchDesigner relaunched (PID {new_pid}) but Envoy not "
                f"reachable after {timeout}s. TD may still be loading — "
                "Embody needs ~75 frames to complete restoration."
            ),
        }


def handle_bridge_tool(name, params, state):
    """Dispatch a bridge meta-tool call. Returns the tool result content."""
    if name == "get_td_status":
        result = handle_get_td_status(state)
    elif name == "launch_td":
        result = handle_launch_td(params, state)
    elif name == "restart_td":
        result = handle_restart_td(params, state)
    elif name == "switch_instance":
        result = handle_switch_instance(params, state)
    else:
        result = {"error": f"Unknown bridge tool: {name}"}

    return [{"type": "text", "text": json.dumps(result, indent=2)}]


# ---------------------------------------------------------------------------
# Tool list augmentation
# ---------------------------------------------------------------------------

def augment_tools_list(response):
    """Append bridge meta-tools to a tools/list response from TD."""
    if (response
            and "result" in response
            and "tools" in response["result"]):
        response["result"]["tools"].extend(BRIDGE_TOOLS)
    return response


def bridge_only_tools_list(request_id):
    """Generate a tools/list response with only bridge meta-tools."""
    return {
        "jsonrpc": "2.0",
        "id": request_id,
        "result": {"tools": list(BRIDGE_TOOLS)},
    }


# ---------------------------------------------------------------------------
# HTTP forwarding and connection management
# ---------------------------------------------------------------------------

def forward_to_http(url, message, timeout=300):
    """Forward a JSON-RPC message to the Envoy HTTP endpoint.

    Returns the parsed JSON-RPC response, or None for notifications
    that return no data.
    """
    data = json.dumps(message).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        },
    )
    resp = urllib.request.urlopen(req, timeout=timeout)
    body = resp.read().decode("utf-8")

    # Streamable HTTP returns SSE format: "event: message\ndata: {...}\n\n"
    for line in body.split("\n"):
        stripped = line.strip()
        if stripped.startswith("data: "):
            try:
                return json.loads(stripped[6:])
            except json.JSONDecodeError:
                continue  # Truncated SSE line — try next

    # Fallback: plain JSON response
    if body.strip():
        try:
            return json.loads(body)
        except json.JSONDecodeError:
            pass

    return None


def send_response(response):
    """Write a JSON-RPC response to stdout (STDIO MCP transport)."""
    sys.stdout.write(json.dumps(response) + "\n")
    sys.stdout.flush()


def send_error(request_id, code, message):
    """Send a JSON-RPC error response."""
    send_response({
        "jsonrpc": "2.0",
        "id": request_id,
        "error": {"code": code, "message": message},
    })


def kill_stale_bridges(port):
    """Find and terminate other envoy-bridge processes targeting the same port.

    Claude Code spawns a new bridge process for each session but doesn't
    always clean up old ones when sessions end.  This prevents dozens of
    zombie bridges from accumulating and fighting over the port.
    """
    my_pid = os.getpid()
    if sys.platform == "win32":
        # Windows: use tasklist/wmic — not worth the complexity for now
        return
    try:
        # Find all envoy-bridge processes via pgrep
        result = subprocess.run(
            ["pgrep", "-f", "envoy-bridge.py"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode != 0:
            return
        for line in result.stdout.strip().split("\n"):
            pid = int(line.strip())
            if pid == my_pid:
                continue
            # Verify this process is actually targeting our port by reading
            # its command line.  This avoids killing bridges for other ports.
            try:
                cmdline_path = f"/proc/{pid}/cmdline"
                if os.path.exists(cmdline_path):
                    # Linux
                    with open(cmdline_path, "r") as f:
                        cmdline = f.read()
                else:
                    # macOS: use ps
                    ps = subprocess.run(
                        ["ps", "-p", str(pid), "-o", "args="],
                        capture_output=True, text=True, timeout=5,
                    )
                    cmdline = ps.stdout.strip()
                if f"--port" in cmdline and str(port) in cmdline:
                    os.kill(pid, signal.SIGTERM)
                    log(f"Terminated stale bridge process (PID {pid})")
            except (ProcessLookupError, PermissionError, OSError):
                pass  # Already gone or not ours
    except (subprocess.TimeoutExpired, FileNotFoundError, ValueError):
        pass  # pgrep not available or other issue — not critical


def start_orphan_watchdog():
    """Start a daemon thread that exits the process if our parent dies.

    When Claude Code exits without cleanly closing stdin, the bridge
    becomes an orphan process.  On Unix, orphaned processes get reparented
    to PID 1 (init/launchd).  We detect this and self-terminate.
    """
    if sys.platform == "win32":
        return  # ppid semantics differ on Windows
    parent_pid = os.getppid()

    def watchdog():
        while True:
            time.sleep(ORPHAN_CHECK_INTERVAL_S)
            current_ppid = os.getppid()
            if current_ppid != parent_pid:
                # Parent changed (reparented to init/launchd) — we're orphaned
                log(f"Parent process died (was {parent_pid}, now {current_ppid}). Exiting.")
                os._exit(0)

    t = threading.Thread(target=watchdog, daemon=True)
    t.start()


def wait_for_envoy(url, deadline):
    """Block until Envoy is reachable or deadline expires. Returns True on success."""
    attempt = 0
    while time.monotonic() < deadline:
        try:
            # Probe with an empty POST — any HTTP response (even 4xx/5xx)
            # means the server is up.  Only connection errors (refused,
            # timeout, DNS) indicate it's not running yet.
            urllib.request.urlopen(
                urllib.request.Request(
                    url, data=b"{}",
                    headers={
                        "Content-Type": "application/json",
                        "Accept": "application/json, text/event-stream",
                    },
                ),
                timeout=3,
            )
            return True
        except urllib.error.HTTPError:
            # Server responded (maybe 400/405) — it's reachable
            return True
        except (urllib.error.URLError, ConnectionError, OSError):
            # Connection refused / timeout — server not up yet
            pass
        idx = min(attempt, len(RETRY_INTERVALS) - 1)
        wait = RETRY_INTERVALS[idx]
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break
        actual_wait = min(wait, remaining)
        elapsed = CONNECT_TIMEOUT_S - remaining
        log(f"Waiting for Envoy ({elapsed:.0f}s elapsed, retry in {actual_wait:.1f}s). "
            f"Ensure TouchDesigner is running with Envoy enabled.")
        time.sleep(actual_wait)
        attempt += 1
    return False


# ---------------------------------------------------------------------------
# Connection loss error messages
# ---------------------------------------------------------------------------

def connection_lost_message(state):
    """Generate an actionable error message when the connection to Envoy is lost."""
    pid = state["td_pid"]
    if pid and not is_process_alive(pid):
        state["crash_detected"] = True
        return (
            "TouchDesigner has crashed. "
            "Use the launch_td tool to restart it."
        )
    elif pid and is_process_alive(pid):
        return (
            f"TouchDesigner is not responding but the process is still "
            f"running (PID {pid}). It may be frozen or handling a long operation."
        )
    else:
        return (
            "Envoy connection lost. "
            "Use get_td_status to check and launch_td to restart."
        )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _resolve_from_registry(config, fallback_port):
    """Resolve port and PID from the instance registry.
    Returns (port, td_pid, active_name)."""
    instances = config.get("instances", {})
    active_name = config.get("active")

    if active_name and active_name in instances:
        active = instances[active_name]
        port = active.get("port", fallback_port)
        config_pid = active.get("td_pid")
        if config_pid and is_process_alive(config_pid):
            return port, config_pid, active_name
        return port, find_td_pid(), active_name

    # Old-format config or empty registry — use fallback
    # Check for old-format flat config with 'port' at top level
    if "port" in config and "instances" not in config:
        port = config.get("port", fallback_port)
        config_pid = config.get("td_pid")
        if config_pid and is_process_alive(config_pid):
            return port, config_pid, None
        return port, find_td_pid(), None

    return fallback_port, find_td_pid(), None


def _install_signal_diagnostics():
    """Install signal handlers that log before exiting, to diagnose what kills the bridge."""
    my_pid = os.getpid()
    ppid = os.getppid()

    def _handle_sigterm(signum, frame):
        log(f"Received SIGTERM (PID {my_pid}, parent {os.getppid()}, "
            f"original parent {ppid})")
        sys.exit(0)

    def _handle_sigint(signum, frame):
        log(f"Received SIGINT (PID {my_pid}, parent {os.getppid()}, "
            f"original parent {ppid})")
        raise KeyboardInterrupt

    signal.signal(signal.SIGTERM, _handle_sigterm)
    signal.signal(signal.SIGINT, _handle_sigint)


def main():
    cli_port, config_path = parse_args()
    _init_file_logging(config_path)

    config = load_config(config_path)
    port, td_pid, active_name = _resolve_from_registry(config, cli_port)
    url = f"http://localhost:{port}/mcp"

    # Bridge state — shared with meta-tool handlers
    state = {
        "connected": False,
        "td_pid": td_pid,
        "last_connected_time": None,
        "crash_detected": False,
        "launch_timestamps": [],
        "config": config,
        "config_path": config_path,
        "url": url,
    }

    my_pid = os.getpid()
    ppid = os.getppid()
    if active_name:
        log(f"Starting (instance: {active_name}, port: {port}) "
            f"[PID {my_pid}, parent {ppid}]")
    else:
        log(f"Starting (target: localhost:{port}) "
            f"[PID {my_pid}, parent {ppid}]")
    if config_path:
        log(f"Config: {config_path}")
        td_exe = config.get("td_executable", "")
        if td_exe and not os.path.exists(td_exe):
            log(f"WARNING: TouchDesigner not found at {td_exe}")

    # Install signal handlers AFTER logging init so we can see what kills us
    _install_signal_diagnostics()

    # Clean up stale bridge processes from previous Claude Code sessions
    kill_stale_bridges(port)

    # Self-terminate if our parent process (Claude Code) dies
    start_orphan_watchdog()

    if state["td_pid"]:
        log(f"Found TouchDesigner process (PID {state['td_pid']})")

    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue

        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            log(f"Ignoring malformed JSON: {line[:100]}")
            continue

        is_notification = "id" not in message
        request_id = message.get("id")
        method = message.get("method", "")
        params = message.get("params", {})

        # --- Intercept bridge meta-tool calls ---
        if method == "tools/call" and params.get("name") in BRIDGE_TOOL_NAMES:
            tool_name = params["name"]
            tool_args = params.get("arguments", {})
            log(f"Handling bridge tool: {tool_name}")
            content = handle_bridge_tool(tool_name, tool_args, state)
            if not is_notification:
                send_response({
                    "jsonrpc": "2.0",
                    "id": request_id,
                    "result": {"content": content},
                })
            continue

        # --- MCP protocol messages handled locally when Envoy is down ---
        # initialize, notifications/initialized, and tools/list must work
        # without Envoy so that bridge meta-tools (launch_td, get_td_status)
        # are available even when TD isn't running.
        if not state["connected"]:
            if method == "initialize":
                if not is_notification:
                    send_response({
                        "jsonrpc": "2.0",
                        "id": request_id,
                        "result": {
                            "protocolVersion": "2024-11-05",
                            "capabilities": {"tools": {"listChanged": True}},
                            "serverInfo": {
                                "name": "envoy-bridge",
                                "version": "1.0.0",
                            },
                        },
                    })
                continue

            if method == "notifications/initialized":
                continue  # Notification — no response needed

            if method == "tools/list":
                # Try connecting to Envoy so we can return the full tool
                # list (TD-proxied + bridge meta-tools).  If Envoy is not
                # reachable, fall back to bridge-only meta-tools.
                deadline = time.monotonic() + CONNECT_TIMEOUT_S
                if wait_for_envoy(url, deadline):
                    state["connected"] = True
                    state["last_connected_time"] = time.time()
                    state["crash_detected"] = False
                    if not state["td_pid"]:
                        state["td_pid"] = find_td_pid()
                    log("Connected to Envoy (during tools/list)")
                    # Fall through to the forwarding path below —
                    # no list_changed notification needed here since the
                    # client will receive the full tool list in this response
                else:
                    if not is_notification:
                        send_response(bridge_only_tools_list(request_id))
                    continue

        # --- Connection management ---
        if not state["connected"]:
            # Re-read config in case the user switched TD instances
            fresh_config = load_config(state["config_path"])
            new_port, new_pid, new_active = _resolve_from_registry(
                fresh_config, cli_port)
            if new_port != port:
                port = new_port
                url = f"http://localhost:{port}/mcp"
                state["url"] = url
                state["config"] = fresh_config
                log(f"Config changed — now targeting port {port}"
                    + (f" (instance: {new_active})" if new_active else ""))
            if new_pid:
                state["td_pid"] = new_pid

            log("Connecting to Envoy...")
            deadline = time.monotonic() + CONNECT_TIMEOUT_S
            if wait_for_envoy(url, deadline):
                state["connected"] = True
                state["last_connected_time"] = time.time()
                state["crash_detected"] = False
                if not state["td_pid"]:
                    state["td_pid"] = find_td_pid()
                log("Connected to Envoy")
                # Notify client that the tool list has changed —
                # full TD tools are now available alongside bridge meta-tools
                send_response({
                    "jsonrpc": "2.0",
                    "method": "notifications/tools/list_changed",
                })
            else:
                log(f"Envoy not reachable after {CONNECT_TIMEOUT_S}s")
                if not is_notification:
                    msg = connection_lost_message(state)
                    send_error(request_id, -32000, msg)
                continue

        # --- Forward to TD with retry ---
        response = None
        max_retries = 3
        try:
            for attempt in range(max_retries + 1):
                try:
                    response = forward_to_http(url, message)
                    state["last_connected_time"] = time.time()
                    break
                except (urllib.error.URLError, ConnectionError, OSError) as e:
                    if attempt < max_retries:
                        time.sleep(0.5 * (attempt + 1))
                        continue

                    # Envoy went away — mark disconnected for next request
                    state["connected"] = False
                    msg = connection_lost_message(state)
                    log(f"Lost connection to Envoy: {e}")
                    if not is_notification:
                        send_error(request_id, -32000, msg)
                    break
                except (json.JSONDecodeError, ValueError) as e:
                    # Malformed response (TD crashed mid-reply) — don't retry,
                    # mark disconnected so next request triggers reconnect
                    state["connected"] = False
                    msg = connection_lost_message(state)
                    log(f"Malformed response from Envoy: {e}")
                    if not is_notification:
                        send_error(request_id, -32000, msg)
                    break
        except Exception as e:
            # Catch-all: NEVER let the bridge die from a transient error
            state["connected"] = False
            log(f"Unexpected error (bridge staying alive): {type(e).__name__}: {e}")
            if not is_notification:
                send_error(
                    request_id, -32000,
                    f"Unexpected error ({type(e).__name__}: {e}). Will reconnect on next request.",
                )

        # Augment tools/list responses with bridge meta-tools
        if response is not None and method == "tools/list":
            augment_tools_list(response)

        # Send response for requests (not for notifications)
        if response is not None and not is_notification:
            send_response(response)

    log("stdin closed, exiting")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        log("Interrupted, exiting")
    except BrokenPipeError:
        pass  # Client closed stdout
