"""EmbodyExt AI-config generation + git status/init (module DAT).

Module DAT (mod.embody_git) called by EmbodyExt -- almost entirely on the MAIN
THREAD (the ext-diet WP9 clusters C6 + C15 + C7). Holds:

  - C6  AI-config / templates / install-manifest: extract_ai_config and the
        per-client writers (AGENTS.md, CLAUDE.md, .claude/, .cursor/, .github/,
        .windsurf/, GEMINI.md), the generated-file hash manifest + marker-gated
        write_template, and the install manifest (footprint records so Uninstall
        can reverse Embody's additions precisely).
  - C15 git status: the pure/tested parse_git_porcelain / map_changed_to_ops /
        row_has_changes, find_git_root_sync, and update_git_status (async scan).
  - C7  init_envoy / init_git / reset (promoted API).

EmbodyExt keeps a thin delegating stub for every function here (identical
signatures; promoted names stay UpperCamelCase). No module-level TD access --
each function takes the ext instance (`ext`) and reaches TD through it (ext.Log,
ext.my, ext._findProjectRoot, ...) or through the TD globals (op, project, run,
parent) available inside the bodies at main-thread call time. The former
@staticmethods (parse_git_porcelain / map_changed_to_ops / row_has_changes) stay
pure -- no ext arg.

THREAD NOTE (the WP4/_get_docs trap): update_git_status runs on the main thread,
but it hands a WORKER-thread closure a reference to parse_git_porcelain. It
captures the module-level function DIRECTLY (`parse = parse_git_porcelain`,
resolved on the main thread) so the worker calls a plain pure function and NEVER
touches `mod` (a TD object) off-main. The facade's _parseGitPorcelain stub is
for the unit tests (main thread) -- the worker must not, and does not, go
through it.

DISPATCH CONTRACT: intra-module calls are module-local EXCEPT the patchable
seams the unit tests monkeypatch on the instance -- _manifestRecordCreatedFile /
_manifestRecordAppendedFile (test_tool_permissions) and _extractAIConfig /
_upgradeEnvoy (test_setup_wizard / test_envoy_lifecycle_hardening) -- which route
via ext.* so the patches take effect. Calls to spine methods that stay on the
facade (_findProjectRoot, _guardFileWrite, createExternalizationsTable, the
Envoy sub-config methods, InitEnvoy) and to facade class attributes
(_TEMPLATE_MAP_RULES/_SKILLS, _AI_CONFIG_FILES, _HASH_MANIFEST, _INSTALL_MANIFEST,
_EMBODY_MARKER, _consent_bulk, _startup_config_pass) also go through ext.* -- the
constants stay class attrs on EmbodyExt (the release-commits.md sync contract and
the unit tests both read them off the ext).
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path


# ==========================================================================
# AI CLIENT CONFIG GENERATION (C6)
# ==========================================================================

def extract_ai_config(ext):
    """Extract AI coding assistant config files based on par.Aiclient."""
    target_dir = ext._findProjectRoot()
    client = ext.my.par.Aiclient.eval()

    def _write():
        # Always: AGENTS.md (universal standard, read by all major AI tools)
        write_agents_md(ext, target_dir)
        if client == 'claudecode':
            write_claude_code_config(ext, target_dir)
        elif client == 'opencode':
            write_opencode_files(ext, target_dir)
        elif client == 'cursor':
            write_cursor_rules(ext, target_dir)
        elif client == 'copilot':
            write_copilot_instructions(ext, target_dir)
        elif client == 'windsurf':
            write_windsurf_rules(ext, target_dir)
        elif client == 'gemini':
            write_gemini_config(ext, target_dir)
        # 'codex', 'none': AGENTS.md only (Codex reads AGENTS.md;
        # Copilot config is its own token).

    # Advanced mode: confirm before (re)writing AI assistant config files.
    details = [f'{target_dir}/AGENTS.md'] + [
        f'{target_dir}/{f}' for f in ext._AI_CONFIG_FILES.get(client, [])]
    ext._guardFileWrite(
        'AI config',
        f'write AI assistant config for {ai_client_label(ext)} in '
        f'{target_dir}',
        details, _write)


def write_agents_md(ext, target_dir):
    """Write AGENTS.md -- universal AI instructions read by all major AI tools."""
    templates_comp = ext.my.op('templates')
    agents_md_dat = templates_comp.op('text_agents_md') if templates_comp else None

    if agents_md_dat and agents_md_dat.text:
        content = agents_md_dat.text
    else:
        # Assemble from the 3 rule templates as a fallback
        ext.Log('text_agents_md DAT not found -- assembling AGENTS.md from rules', 'DEBUG')
        parts = ['<!-- Generated by Embody/Envoy -- do not edit manually -->\n']
        parts.append('# Embody + Envoy -- AI Instructions\n\n')
        parts.append(
            'This project uses [Embody](https://github.com/dylanroscover/Embody) '
            '(TouchDesigner externalization) and Envoy (MCP server for AI coding tools).\n\n'
            '---\n\n'
        )
        if templates_comp:
            for dat_name in ext._TEMPLATE_MAP_RULES:
                dat = templates_comp.op(dat_name)
                if dat and dat.text:
                    # Strip frontmatter from each rule before embedding
                    parts.append(strip_frontmatter(ext, dat.text).strip())
                    parts.append('\n\n---\n\n')
        content = ''.join(parts)

    write_template(ext, target_dir, 'AGENTS.md', content)


def write_claude_code_config(ext, target_dir):
    """Write Claude Code config: CLAUDE.md + .claude/rules/ + .claude/skills/"""
    # 1. CLAUDE.md (with ENVOY.md fallback if user already has one)
    write_claude_md(ext, target_dir)

    # 2. .claude/rules/ and .claude/skills/ from template DATs
    write_claude_rules_and_skills(ext, target_dir)


def write_claude_rules_and_skills(ext, target_dir):
    """Write .claude/rules/*.md + .claude/skills/*/SKILL.md from template
    DATs. Shared by the Claude Code and OpenCode clients: OpenCode's
    Claude-compat layer discovers .claude/skills/ natively, and the
    generated opencode.json loads .claude/rules/ via an instructions
    glob -- one copy on disk serves both clients, no drift."""
    templates_comp = ext.my.op('templates')
    if not templates_comp:
        ext.Log('Templates COMP not found -- skipping .claude/ generation', 'DEBUG')
        return

    written = 0
    for dat_name, slug in ext._TEMPLATE_MAP_RULES.items():
        template_dat = templates_comp.op(dat_name)
        if not template_dat or not template_dat.text:
            continue
        # Claude Code doesn't use YAML frontmatter -- strip it.
        # Keep the generated-by marker for overwrite protection.
        content = strip_frontmatter(ext, template_dat.text)
        if write_template(ext, target_dir, f'.claude/rules/{slug}.md', content):
            written += 1

    for dat_name, slug in ext._TEMPLATE_MAP_SKILLS.items():
        template_dat = templates_comp.op(dat_name)
        if not template_dat or not template_dat.text:
            continue
        # Frontmatter KEPT: skills need name/description -- both Claude
        # Code and OpenCode validate it (OpenCode also requires the name
        # to match the directory slug).
        if write_template(ext, target_dir, f'.claude/skills/{slug}/SKILL.md', template_dat.text):
            written += 1

    if written > 0:
        ext.Log(f'Generated {written} .claude/ files at {target_dir}', 'SUCCESS')


def write_opencode_files(ext, target_dir):
    """Write OpenCode client config: shared .claude/ rules + skills, plus
    the Envoy entry in opencode.json.

    No CLAUDE.md is written for this client: OpenCode reads CLAUDE.md
    only as a fallback when AGENTS.md is absent, and AGENTS.md is always
    written -- the full rule set reaches OpenCode through the
    instructions glob (.claude/rules/*.md) in opencode.json instead.
    """
    write_claude_rules_and_skills(ext, target_dir)
    try:
        mod.envoy_setup.ensure_opencode_config(
            op.Embody.ext.Envoy, target_dir)
    except Exception as e:
        ext.Log(f'Could not write opencode.json: {e}', 'WARNING')


def strip_frontmatter(ext, content):
    """Strip leading YAML frontmatter (---...---) from content if present.

    Returns the content after the closing --- block, with leading whitespace
    trimmed. Handles BOM-prefixed content.
    """
    # Strip BOM that TD may add to externalized files
    content = content.lstrip('\ufeff')
    if not content.startswith('---\n'):
        return content
    close_idx = content.find('\n---\n', 4)
    if close_idx == -1:
        return content
    return content[close_idx + 5:].lstrip('\n')


def write_cursor_rules(ext, target_dir):
    """Write Cursor rules: .cursor/rules/{slug}.mdc with YAML frontmatter.

    Templates already embed a 'description:' field. This injects 'globs: []'
    and 'alwaysApply: true' into the existing frontmatter rather than
    prepending a duplicate block.
    """
    templates_comp = ext.my.op('templates')
    if not templates_comp:
        ext.Log('Templates COMP not found -- skipping .cursor/ generation', 'DEBUG')
        return

    written = 0
    for dat_name, slug in ext._TEMPLATE_MAP_RULES.items():
        template_dat = templates_comp.op(dat_name)
        if not template_dat or not template_dat.text:
            continue
        raw = template_dat.text.lstrip('\ufeff')
        # Inject globs/alwaysApply into existing frontmatter
        SEP = '\n---\n'
        if raw.startswith('---\n') and SEP in raw[4:]:
            close_idx = raw.find(SEP, 4)
            fm_lines = raw[4:close_idx]
            rest = raw[close_idx + len(SEP):]
            if 'alwaysApply:' not in fm_lines:
                fm_lines += '\nglobs: []\nalwaysApply: true'
            content = '---\n' + fm_lines + SEP + rest
        else:
            # No frontmatter -- build one from first H1
            description = slug.replace('-', ' ').title()
            for line in raw.splitlines():
                if line.startswith('# '):
                    description = line[2:].strip()
                    break
            content = (
                f'---\ndescription: "{description}"\n'
                f'globs: []\nalwaysApply: true\n---\n\n{raw}'
            )
        if write_template(ext, target_dir, f'.cursor/rules/{slug}.mdc', content):
            written += 1

    if written > 0:
        ext.Log(f'Generated {written} .cursor/rules/ files at {target_dir}', 'SUCCESS')


def write_copilot_instructions(ext, target_dir):
    """Write GitHub Copilot config: combined instructions + per-rule files."""
    templates_comp = ext.my.op('templates')
    if not templates_comp:
        ext.Log('Templates COMP not found -- skipping .github/ generation', 'DEBUG')
        return

    written = 0
    rule_parts = ['<!-- Generated by Embody/Envoy -- do not edit manually -->\n\n']
    individual_contents = {}

    for dat_name, slug in ext._TEMPLATE_MAP_RULES.items():
        template_dat = templates_comp.op(dat_name)
        if not template_dat or not template_dat.text:
            continue
        # Strip template frontmatter -- Copilot uses its own applyTo format
        rule_content = strip_frontmatter(ext, template_dat.text).strip()
        # Extract heading for section label
        heading = slug.replace('-', ' ').title()
        for line in rule_content.splitlines():
            if line.startswith('# '):
                heading = line[2:].strip()
                break
        rule_parts.append(f'## {heading}\n\n{rule_content}\n\n---\n\n')
        # Individual file with applyTo frontmatter + generated marker
        individual_contents[slug] = (
            f'---\n'
            f'applyTo: "**"\n'
            f'---\n\n'
            f'<!-- Generated by Embody/Envoy -- do not edit manually -->\n\n'
            f'{rule_content}'
        )

    # Combined file (.github/copilot-instructions.md)
    combined = ''.join(rule_parts)
    if write_template(ext, target_dir, '.github/copilot-instructions.md', combined):
        written += 1

    # Individual per-rule files (.github/instructions/{slug}.instructions.md)
    for slug, content in individual_contents.items():
        if write_template(ext, target_dir, f'.github/instructions/{slug}.instructions.md', content):
            written += 1

    if written > 0:
        ext.Log(f'Generated {written} .github/ files at {target_dir}', 'SUCCESS')


def write_windsurf_rules(ext, target_dir):
    """Write Windsurf rules: .windsurf/rules/{slug}.md (plain markdown)."""
    templates_comp = ext.my.op('templates')
    if not templates_comp:
        ext.Log('Templates COMP not found -- skipping .windsurf/ generation', 'DEBUG')
        return

    written = 0
    for dat_name, slug in ext._TEMPLATE_MAP_RULES.items():
        template_dat = templates_comp.op(dat_name)
        if not template_dat or not template_dat.text:
            continue
        if write_template(ext, target_dir, f'.windsurf/rules/{slug}.md', template_dat.text):
            written += 1

    if written > 0:
        ext.Log(f'Generated {written} .windsurf/rules/ files at {target_dir}', 'SUCCESS')


def write_gemini_config(ext, target_dir):
    """Write Gemini CLI config: a thin GEMINI.md that imports AGENTS.md.

    Gemini reads GEMINI.md (not AGENTS.md), so GEMINI.md pulls in the
    always-written AGENTS.md via Gemini's @import syntax -- no content
    duplication. See docs: gemini-cli/docs/cli/gemini-md.md (@file imports).
    """
    content = (
        '<!-- Generated by Embody/Envoy -- do not edit manually -->\n\n'
        '# Project Context for Gemini CLI\n\n'
        'This project uses Embody (TouchDesigner externalization) and Envoy\n'
        '(MCP server for AI coding tools). The full instructions live in\n'
        'AGENTS.md, imported below.\n\n'
        '@AGENTS.md\n'
    )
    if write_template(ext, target_dir, 'GEMINI.md', content):
        ext.Log(f'Generated GEMINI.md at {target_dir}', 'SUCCESS')


def write_claude_md(ext, target_dir):
    """Write CLAUDE.md from the text_claude template DAT."""
    templates_comp = ext.my.op('templates')
    template_dat = templates_comp.op('text_claude') if templates_comp else None
    if not template_dat:
        ext.Log('CLAUDE.md template DAT not found inside Embody/templates', 'WARNING')
        return None

    content = template_dat.text
    if not content:
        ext.Log('CLAUDE.md template DAT is empty', 'WARNING')
        return None

    claude_md_path = target_dir / 'CLAUDE.md'

    if claude_md_path.exists():
        existing = claude_md_path.read_text(encoding='utf-8')
        if '<!-- Generated by Embody/Envoy' in existing:
            claude_md_path.write_text(content, encoding='utf-8')
            ext.Log(f'Updated CLAUDE.md at {claude_md_path}', 'SUCCESS')
        else:
            fallback = target_dir / 'ENVOY.md'
            fallback.write_text(content, encoding='utf-8')
            ext.Log(
                f'CLAUDE.md already exists (not generated by Embody). '
                f'Wrote MCP reference to {fallback} instead.',
                'WARNING'
            )
            return fallback
    else:
        claude_md_path.write_text(content, encoding='utf-8')
        ext.Log(f'Created CLAUDE.md at {claude_md_path}', 'SUCCESS')

    return claude_md_path


# ==========================================================================
# GENERATED-FILE HASH MANIFEST + MARKER-GATED TEMPLATE WRITE (C6)
# ==========================================================================
# Sidecar manifest of {rel_path: sha256(generated content)} recorded under the
# project root. It lets write_template tell "untouched since we wrote it" (safe
# to regenerate) from "the user edited a generated file" (preserve), WITHOUT
# mutating the generated files themselves. _HASH_MANIFEST stays a class attr on
# EmbodyExt.

def content_hash(ext, content):
    """Stable 16-hex SHA-256 of a generated file's content."""
    return hashlib.sha256(content.encode('utf-8')).hexdigest()[:16]


def load_hash_manifest(ext, target_dir):
    path = Path(target_dir) / ext._HASH_MANIFEST
    if path.exists():
        try:
            return json.loads(path.read_text(encoding='utf-8'))
        except Exception:
            return {}
    return {}


def save_hash_manifest(ext, target_dir, manifest):
    path = Path(target_dir) / ext._HASH_MANIFEST
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True), encoding='utf-8')


# --- Install manifest -----------------------------------------------------
# Records Embody's project footprint so Uninstall/Deinit can reverse it
# PRECISELY and SAFELY -- above all, never delete a file that predated
# Embody. Additive + best-effort: a manifest write must never break the
# footprint action it records. See dev/embody/plan-init-deinit-wizard.md #6.
# _INSTALL_MANIFEST stays a class attr on EmbodyExt.

def install_manifest_skeleton(ext):
    return {'version': 1, 'files_created': [], 'files_appended': [],
            'git_config': [], 'venv': None, 'network_ops': []}


def load_install_manifest(ext, target_dir):
    path = Path(target_dir) / ext._INSTALL_MANIFEST
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding='utf-8'))
            skel = install_manifest_skeleton(ext)
            if isinstance(data, dict):
                skel.update(data)  # tolerate older/partial manifests
            return skel
        except Exception:
            pass
    return install_manifest_skeleton(ext)


def save_install_manifest(ext, target_dir, manifest):
    path = Path(target_dir) / ext._INSTALL_MANIFEST
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True), encoding='utf-8')


def manifest_rel_path(ext, target_dir, path):
    """Stored form for a footprint path: POSIX-relative to the manifest root
    when the path lives under it, else an absolute POSIX path (so files
    outside the project root -- e.g. a repo .gitignore when the project is a
    subdir -- still record cleanly). Accepts a path already relative to
    target_dir OR an absolute path."""
    try:
        base = Path(target_dir).resolve()
        p = Path(path)
        if not p.is_absolute():
            p = base / p
        p = p.resolve()
        try:
            return p.relative_to(base).as_posix()
        except ValueError:
            return p.as_posix()
    except Exception:
        return str(path).replace('\\', '/')


def manifest_record_created_file(ext, target_dir, path):
    """Record a file Embody CREATED (did not previously exist) so Uninstall
    can safely remove ONLY Embody's own additions. Best-effort; never raises."""
    try:
        rel = manifest_rel_path(ext, target_dir, path)
        m = load_install_manifest(ext, target_dir)
        if rel not in m['files_created']:
            m['files_created'].append(rel)
            save_install_manifest(ext, target_dir, m)
    except Exception as e:
        ext.Log(f'Install-manifest record failed for {path}: {e}', 'DEBUG')


def manifest_record_appended_file(ext, target_dir, path, marker, kind='block'):
    """Record a SHARED file Embody modified in place -- a git file it
    appended a marked BLOCK to (kind='block', marker = block header), or a
    JSON file it added a KEY to (kind='json_key', marker = the dotted key,
    e.g. 'mcpServers.envoy'). Uninstall reverses ONLY that unit; it NEVER
    deletes the user's file. Best-effort; never raises."""
    try:
        rel = manifest_rel_path(ext, target_dir, path)
        m = load_install_manifest(ext, target_dir)
        if not any(e.get('path') == rel for e in m['files_appended']):
            m['files_appended'].append(
                {'path': rel, 'marker': marker, 'kind': kind})
            save_install_manifest(ext, target_dir, m)
    except Exception as e:
        ext.Log(f'Install-manifest append record failed for {path}: {e}',
                'DEBUG')


def manifest_record_venv(ext, target_dir, venv_path):
    """Record that Embody CREATED the venv (safe to remove on uninstall)."""
    try:
        rel = manifest_rel_path(ext, target_dir, venv_path)
        m = load_install_manifest(ext, target_dir)
        if not m.get('venv'):
            m['venv'] = {'path': rel, 'created': True}
            save_install_manifest(ext, target_dir, m)
    except Exception as e:
        ext.Log(f'Install-manifest venv record failed: {e}', 'DEBUG')


def manifest_record_git_config(ext, target_dir, keys):
    """Record git config keys Embody set (un-set on uninstall)."""
    try:
        if isinstance(keys, str):
            keys = [keys]
        m = load_install_manifest(ext, target_dir)
        changed = False
        for k in keys:
            if k not in m['git_config']:
                m['git_config'].append(k)
                changed = True
        if changed:
            save_install_manifest(ext, target_dir, m)
    except Exception as e:
        ext.Log(f'Install-manifest git-config record failed: {e}', 'DEBUG')


def write_template(ext, target_dir, rel_path, content):
    """Write a single template file, respecting the Embody/Envoy marker.

    Overwrite policy, in order:
      - no marker             -> user-authored, never touched (skip).
      - marker + edited since
        we wrote it           -> the user changed a generated file; their
                                 edits win (skip + log; delete it to refresh).
      - marker + untouched    -> regenerate (live hash matches what we stored).
      - legacy marker (no
        tracked hash)         -> regenerate once, then it is tracked and
                                 edit-protected from here on.

    Edit-detection uses a sidecar hash manifest (_HASH_MANIFEST) so generated
    files stay byte-identical to their templates.

    Returns True if the file was written, False if skipped.
    """
    target_path = Path(target_dir) / rel_path
    was_new = not target_path.exists()  # pre-existence -> install-manifest safe-delete record
    manifest = load_hash_manifest(ext, target_dir)
    if target_path.exists():
        existing = target_path.read_text(encoding='utf-8')
        if ext._EMBODY_MARKER not in existing:
            return False
        stored = manifest.get(rel_path)
        if stored is not None and content_hash(ext, existing) != stored:
            ext.Log(
                f'Kept your edits to {rel_path} '
                f'(delete the file to regenerate it from the template).',
                'INFO')
            return False
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(content, encoding='utf-8')
    manifest[rel_path] = content_hash(ext, content)
    save_hash_manifest(ext, target_dir, manifest)
    if was_new:
        ext._manifestRecordCreatedFile(target_dir, rel_path)
    return True


def upgrade_envoy(ext):
    """Restore AI config on open if Envoy is enabled but files are missing.

    Auto restores silently (the managed default). Advanced defers with a
    breadcrumb: _extractAIConfig runs under _startup_config_pass so its guard
    DEFERS instead of popping a modal that would block the restore chain."""
    if not ext.my.par.Envoyenable.eval():
        return
    target_dir = ext._findProjectRoot()
    client = ext.my.par.Aiclient.eval()
    agents_md_missing = not (target_dir / 'AGENTS.md').exists()
    if not (agents_md_missing or client_files_missing(ext, target_dir, client)):
        return
    prior = ext._startup_config_pass
    ext._startup_config_pass = True
    try:
        ext._extractAIConfig()
    finally:
        ext._startup_config_pass = prior


def client_files_missing(ext, target_dir, client):
    """Return True if the primary config files for the selected client are absent."""
    checks = {
        'claudecode': lambda d: (
            not (d / 'CLAUDE.md').exists() and not (d / 'ENVOY.md').exists()
        ) or not (d / '.claude' / 'rules').exists(),
        'opencode':   lambda d: (
            not (d / 'opencode.json').exists()
            or not (d / '.claude' / 'rules').exists()),
        'cursor':     lambda d: not (d / '.cursor' / 'rules').exists(),
        'copilot':    lambda d: not (d / '.github' / 'copilot-instructions.md').exists(),
        'windsurf':   lambda d: not (d / '.windsurf' / 'rules').exists(),
        'gemini':     lambda d: not (d / 'GEMINI.md').exists(),
        'none':       lambda d: False,
    }
    return checks.get(client, lambda d: False)(target_dir)


def ai_client_label(ext):
    """Human label of the SELECTED Aiclient option (e.g. 'Claude Code') --
    NOT the parameter's own label ('AI Client')."""
    p = ext.my.par.Aiclient
    try:
        return p.menuLabels[p.menuIndex]
    except Exception:
        return p.eval()


# ==========================================================================
# INIT / RESET (C7)
# ==========================================================================

def init_envoy(ext) -> None:
    """(Re)generate all Envoy and AI client config files.

    Writes MCP config (.mcp.json, .embody/envoy.json, bridge script,
    settings.local.json) and AI client files (CLAUDE.md, AGENTS.md,
    .claude/rules/, .claude/skills/, or equivalent for Cursor/Copilot/
    Windsurf) to the git root or project folder.

    Safe to call at any time -- idempotent. Use this after initializing
    a git repo, changing the AI client setting, or updating Embody to
    refresh generated files.

    Requires Envoy to be enabled (par.Envoyenable = True).
    """
    if not ext.my.par.Envoyenable.eval():
        ext.Log('Envoy is not enabled. Set Envoyenable = True first.', 'WARNING')
        return

    target_dir = ext._findProjectRoot()

    # MCP config (port comes from the running server, or the parameter)
    envoy = ext.my.ext.Envoy
    if ext.my.fetch('envoy_running', False):
        # Extract port from current status string
        status = str(ext.my.par.Envoystatus.eval())
        import re
        match = re.search(r'port\s+(\d+)', status)
        port = int(match.group(1)) if match else ext.my.par.Envoyport.eval()
    else:
        port = ext.my.par.Envoyport.eval()

    # ONE combined Advanced-mode confirm for the whole config regen (MCP +
    # AI); the sub-calls apply silently under _consent_bulk so this never
    # fragments into a dialog per file.
    client_label = ai_client_label(ext)

    def _apply():
        prior = ext._consent_bulk
        ext._consent_bulk = True
        try:
            envoy._configureMCPClient(port, target_dir=target_dir)
            ext._extractAIConfig()  # AI client config
        finally:
            ext._consent_bulk = prior
        ext.Log(
            f'Envoy config regenerated for {client_label} at {target_dir}',
            'SUCCESS')

    ext._guardFileWrite(
        'AI & MCP config',
        f'(re)write MCP + AI client config for {client_label} in {target_dir}',
        [f'{target_dir}/.mcp.json', f'{target_dir}/AGENTS.md',
         f'{target_dir}/ (rules/instructions for {client_label})'],
        _apply)


def init_git(ext) -> None:
    """Initialize or reconnect to a git repository, then generate
    git-related config files (.gitignore, .gitattributes).

    If no git repo exists, prompts the user to initialize one.
    After git is available, also regenerates MCP and AI client config
    so paths point to the git root.

    Safe to call at any time. Use this after creating a git repo
    manually, or to refresh .gitignore/.gitattributes entries.

    Requires Envoy to be enabled (par.Envoyenable = True).
    """
    if not ext.my.par.Envoyenable.eval():
        ext.Log('Envoy is not enabled. Set Envoyenable = True first.', 'WARNING')
        return

    envoy = ext.my.ext.Envoy
    git_root = envoy._checkOrInitGitRepo()

    if git_root is None:
        return  # User cancelled

    if git_root == 'no-git':
        ext.Log('No git repo -- .gitignore/.gitattributes skipped.', 'INFO')
        return

    # Store git root so Envoy can find it later (e.g. for deregistration)
    ext.my.store('_git_root', git_root)

    # Git-specific config -- ONE combined Advanced-mode confirm (sub-calls
    # apply silently under _consent_bulk so this doesn't fragment per file).
    def _apply():
        prior = ext._consent_bulk
        ext._consent_bulk = True
        try:
            envoy._configureGitignore(git_root)
            envoy._configureGitattributes(git_root)
        finally:
            ext._consent_bulk = prior
        ext.Log(f'Git config generated at {git_root}', 'SUCCESS')

    ext._guardFileWrite(
        'Git config', f'update git config in {git_root}',
        [f'{git_root}/.gitignore', f'{git_root}/.gitattributes'],
        _apply)

    # Regenerate MCP + AI config so paths point to git root (own confirm)
    ext.InitEnvoy()


def reset(ext, removeTags: bool = False) -> None:
    """Reset Embody to initial state."""
    parent.Embody.Disable(False, removeTags)
    run(f"op('{ext.my}').UpdateHandler()", delayFrames=10)
    ext.createExternalizationsTable()
    ext.my.par.externaltox = ''


# ==========================================================================
# GIT STATUS (uncommitted detection for the manager UI) (C15)
# ==========================================================================
# A SECOND status axis, distinct from "unsaved" (live-vs-disk). Externalized
# DAT scripts use TD's bidirectional syncfile, so they are always in sync with
# disk -- their only meaningful "changed" state is git-relative (on disk but
# not committed). Computed once per refresh sweep and stored at runtime (never
# written to externalizations.tsv, which would churn). Powers the orange badge
# for TOX/TDN/DAT alike. Self-disables outside a git repo.

def find_git_root_sync(ext):
    """Walk up from project.folder for a .git dir. Returns Path or 'no-git'.

    No subprocess and no prompt -- safe to call on the main-thread refresh
    sweep. Mirrors EnvoyExt._findGitRoot so the two never disagree.
    """
    project_dir = Path(project.folder).resolve()
    try:
        home_dir = Path.home().resolve()
    except Exception:
        home_dir = None
    home_is_ancestor = bool(
        home_dir and (home_dir == project_dir or home_dir in project_dir.parents))
    for parent in [project_dir] + list(project_dir.parents):
        if home_is_ancestor and parent == home_dir:
            break
        if (parent / '.git').exists():
            return parent
    return 'no-git'


def parse_git_porcelain(output: str) -> dict:
    """Parse `git status --porcelain -z` output into {repo_rel_posix: code}.

    `-z` means NUL-separated records and NO path quoting, so paths with
    spaces/unicode are handled cleanly. A rename/copy record (X or Y in
    R/C) is followed by an extra NUL-separated origin path; both the new and
    origin paths are recorded (membership tests only ever hit the one that
    currently exists on disk). Untracked entries (`??`) count as changed.
    """
    result = {}
    tokens = output.split('\0')
    i, n = 0, len(tokens)
    while i < n:
        tok = tokens[i]
        if not tok or len(tok) < 3 or tok[2] != ' ':
            i += 1
            continue
        code, path = tok[:2], tok[3:]
        if path:
            result[path] = code
        if code[0] in ('R', 'C'):
            i += 1
            if i < n and tokens[i]:
                result[tokens[i]] = code
        i += 1
    return result


def map_changed_to_ops(changed, project_prefix, rows):
    """Map a git {repo_rel_posix: code} set to {op_path: code} for externalized
    rows.

    `project_prefix` is project.folder relative to the git root as a posix
    prefix ('' or e.g. 'dev/'); `rows` is an iterable of
    (op_path, rel_file_path). Pure string math -- no filesystem and no TD
    access -- so it is both fast (no per-row Path.resolve) and unit-testable.
    """
    out = {}
    if not changed:
        return out
    for path, rel in rows:
        if not path or not rel or path == '/':
            continue
        code = changed.get(project_prefix + rel.replace('\\', '/'))
        if code:
            out[path] = code
    return out


def row_is_unsaved(dirty_val) -> bool:
    """Whether a manager row has unsaved in-TD changes (`dirty` or `Par`).
    Single source of truth for the manager's "dirty" filter keyword (used
    by inject_parents)."""
    return str(dirty_val) in ('True', 'true', '1', 'Par')


def row_has_changes(dirty_val, uncommitted) -> bool:
    """Whether a manager row has pending changes on EITHER axis: unsaved
    (`dirty`/`Par`) or git-uncommitted. Single source of truth for the
    manager's "changed" filter keyword (used by inject_parents)."""
    return row_is_unsaved(dirty_val) or bool(uncommitted)


def update_git_status(ext) -> None:
    """Kick off an ASYNC git-uncommitted scan on a worker thread; never blocks
    the refresh frame.

    The `git status` subprocess (tens of ms) and parsing run off the main
    thread; the cheap, string-based mapping + store happen back on the main
    thread in the SuccessHook closure, which then refreshes the manager
    badges. Runtime-only via store('git_status', ...) (never touches
    externalizations.tsv). No git repo, thread-pool exhaustion, or any failure
    -> empty/unchanged map; the orange indicator simply does not show.

    Each scan carries a generation id captured in its hooks, and its result
    state is task-local (closure, not a shared attribute). Only the LATEST
    generation publishes or clears the in-flight flag -- so a stale task that
    finally fires after a re-arm is a no-op and cannot clobber a newer scan.
    """
    import time
    now = time.monotonic()
    # Coalesce: one scan in flight at a time. Re-arm only if a prior scan has
    # been "running" implausibly long (worker died without a hook firing).
    if getattr(ext, '_git_check_running', False) and \
            (now - getattr(ext, '_git_check_started', 0)) < 10:
        return
    # Bump the generation: this supersedes any still-pending stale task.
    gen = getattr(ext, '_git_gen', 0) + 1
    ext._git_gen = gen
    git_root = find_git_root_sync(ext)
    if git_root == 'no-git':
        ext._git_check_running = False
        ext.my.store('git_status', {})
        return
    proj = str(Path(project.folder).resolve())
    git_root_s = str(git_root)
    clean_env = {
        k: v for k, v in os.environ.items()
        if k not in ('GIT_DIR', 'GIT_WORK_TREE',
                     'GIT_INDEX_FILE', 'GIT_CEILING_DIRECTORIES')}
    # Never take the optional index lock -- a background status must not
    # contend with the user's (or an agent's) concurrent git add/commit.
    clean_env['GIT_OPTIONAL_LOCKS'] = '0'
    state = {'changed': None}
    ext._git_check_running = True
    ext._git_check_started = now

    # Worker runs on a pool thread -- captures only locals + a pure module
    # function (resolved here on the main thread), so it touches NO TD objects
    # and never `mod` off-main (the one sanctioned main->worker handoff).
    parse = parse_git_porcelain

    def worker():
        try:
            # --no-optional-locks: never write .git/index (no lock contention).
            # --untracked-files=all: enumerate files inside new dirs (not `?? dir/`).
            r = subprocess.run(
                ['git', '--no-optional-locks', 'status', '--porcelain', '-z',
                 '--untracked-files=all', '--', proj],
                cwd=git_root_s, capture_output=True, text=True,
                env=clean_env, stdin=subprocess.DEVNULL, timeout=5, check=False)
            state['changed'] = parse(r.stdout or '') if r.returncode == 0 else {}
        except Exception:
            state['changed'] = {}

    def done():
        # Only the latest generation publishes / clears the flag.
        if gen != getattr(ext, '_git_gen', None):
            return
        ext._git_check_running = False
        try:
            prefix = Path(proj).relative_to(Path(git_root_s)).as_posix()
            prefix = (prefix + '/') if prefix and prefix != '.' else ''
        except Exception:
            prefix = ''
        rows = []
        table = ext.Externalizations
        if table is not None:
            for r in range(1, table.numRows):
                rows.append((ext._cellVal(r, 'path'),
                             ext._cellVal(r, 'rel_file_path')))
        ext.my.store('git_status',
                     map_changed_to_ops(state['changed'] or {}, prefix, rows))
        # Refresh the manager so the orange badges reflect the new git state.
        try:
            ext.my.op('list/inject_parents').cook(force=True)
            ext.lister.reset()
        except Exception:
            pass

    def failed(e):
        if gen != getattr(ext, '_git_gen', None):
            return
        ext._git_check_running = False
        ext.Log(f"Git status worker failed: {e}", "DEBUG")

    tm = op.TDResources.ThreadManager
    task = tm.TDTask(target=worker, SuccessHook=done, ExceptHook=failed)
    if tm.EnqueueTask(task, standalone=True) is None:
        # Thread pool at capacity -- abandon; the next refresh retries.
        ext._git_check_running = False
