#!/usr/bin/env python3
"""
Envoy Bridge — STDIO-to-HTTP proxy for the Envoy MCP server.

Bridges Claude Code's STDIO MCP transport to Envoy's Streamable HTTP
endpoint inside TouchDesigner, providing automatic retry and reconnection
when TD isn't running yet.

Usage:
    python3 -u envoy_bridge.py [--port PORT]

Generated by Embody. Regenerated on each Envoy start — do not hand-edit.
"""

import json
import sys
import time
import urllib.error
import urllib.request

DEFAULT_PORT = 9870
RETRY_INTERVALS = [0.5, 0.5, 1, 1, 2, 2, 3, 3, 5, 5, 8, 8]
CONNECT_TIMEOUT_S = 60  # Max seconds to wait for Envoy on first connect


def log(msg):
    """Log to stderr (visible in Claude Code's MCP server output)."""
    sys.stderr.write(f"[envoy-bridge] {msg}\n")
    sys.stderr.flush()


def parse_args():
    port = DEFAULT_PORT
    args = sys.argv[1:]
    for i, arg in enumerate(args):
        if arg == "--port" and i + 1 < len(args):
            port = int(args[i + 1])
    return port


def forward_to_http(url, message, timeout=60):
    """Forward a JSON-RPC message to the Envoy HTTP endpoint.

    Returns the parsed JSON-RPC response, or None for notifications
    that return no data.
    """
    data = json.dumps(message).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        },
    )
    resp = urllib.request.urlopen(req, timeout=timeout)
    body = resp.read().decode("utf-8")

    # Streamable HTTP returns SSE format: "event: message\ndata: {...}\n\n"
    for line in body.split("\n"):
        stripped = line.strip()
        if stripped.startswith("data: "):
            return json.loads(stripped[6:])

    # Fallback: plain JSON response
    if body.strip():
        try:
            return json.loads(body)
        except json.JSONDecodeError:
            pass

    return None


def send_response(response):
    """Write a JSON-RPC response to stdout (STDIO MCP transport)."""
    sys.stdout.write(json.dumps(response) + "\n")
    sys.stdout.flush()


def send_error(request_id, code, message):
    """Send a JSON-RPC error response."""
    send_response({
        "jsonrpc": "2.0",
        "id": request_id,
        "error": {"code": code, "message": message},
    })


def wait_for_envoy(url, deadline):
    """Block until Envoy is reachable or deadline expires. Returns True on success."""
    attempt = 0
    while time.monotonic() < deadline:
        try:
            # Probe with an empty POST — any HTTP response (even 4xx/5xx)
            # means the server is up.  Only connection errors (refused,
            # timeout, DNS) indicate it's not running yet.
            urllib.request.urlopen(
                urllib.request.Request(
                    url, data=b"{}",
                    headers={
                        "Content-Type": "application/json",
                        "Accept": "application/json, text/event-stream",
                    },
                ),
                timeout=3,
            )
            return True
        except urllib.error.HTTPError:
            # Server responded (maybe 400/405) — it's reachable
            return True
        except (urllib.error.URLError, ConnectionError, OSError):
            # Connection refused / timeout — server not up yet
            pass
        idx = min(attempt, len(RETRY_INTERVALS) - 1)
        wait = RETRY_INTERVALS[idx]
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break
        actual_wait = min(wait, remaining)
        elapsed = CONNECT_TIMEOUT_S - remaining
        log(f"Waiting for Envoy ({elapsed:.0f}s elapsed, retry in {actual_wait:.1f}s). "
            f"Ensure TouchDesigner is running with Envoy enabled.")
        time.sleep(actual_wait)
        attempt += 1
    return False


def main():
    port = parse_args()
    url = f"http://localhost:{port}/mcp"
    connected = False

    log(f"Starting (target: localhost:{port})")

    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue

        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            log(f"Ignoring malformed JSON: {line[:100]}")
            continue

        is_notification = "id" not in message
        request_id = message.get("id")

        # On first message (initialize), allow a longer wait for Envoy to start
        if not connected:
            log("Connecting to Envoy...")
            deadline = time.monotonic() + CONNECT_TIMEOUT_S
            if wait_for_envoy(url, deadline):
                connected = True
                log("Connected to Envoy")
            else:
                log(f"Envoy not reachable after {CONNECT_TIMEOUT_S}s")
                if not is_notification:
                    send_error(
                        request_id, -32000,
                        f"Envoy MCP server not reachable on port {port}. "
                        "Ensure TouchDesigner is running with Envoy enabled.",
                    )
                continue

        # Forward the message with retry on transient failures
        response = None
        max_retries = 3
        for attempt in range(max_retries + 1):
            try:
                response = forward_to_http(url, message)
                break
            except (urllib.error.URLError, ConnectionError, OSError) as e:
                if attempt < max_retries:
                    time.sleep(0.5 * (attempt + 1))
                    continue

                # Envoy went away — mark disconnected for next request
                connected = False
                log(f"Lost connection to Envoy: {e}")
                if not is_notification:
                    send_error(
                        request_id, -32000,
                        f"Envoy connection lost ({e}). Will reconnect on next request.",
                    )
                break

        # Send response for requests (not for notifications)
        if response is not None and not is_notification:
            send_response(response)

    log("stdin closed, exiting")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        log("Interrupted, exiting")
    except BrokenPipeError:
        pass  # Client closed stdout
