// Generates src/components/Wordmark.astro: the "embody" wordmark with the
// enclosing loop, as static SVG paths derived from the shipped Inter SemiBold
// outlines (public/fonts/inter-latin-600-normal.woff2). Static paths, not live
// text, so the loop's join with the y's tail and the b's stem is exact in every
// browser and needs no font to be loaded.
//
// The loop is the y's own tail continued: Inter's y hooks left and ends in a
// short slanted cut about 15 units below the baseline; the stroke leaves that
// cut heading left at the hook's depth and width, runs under the word, rounds
// the e with tight corners, comes back along the ascender line, and turns down
// into the b's stem, matching the stem's width so the two merge.
//
// Run:  node scripts/wordmark.mjs        (needs fontkit resolvable: either
//       `npm i --no-save fontkit` here, or FONTKIT_DIR=<dir with node_modules>)
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(process.env.FONTKIT_DIR ? join(process.env.FONTKIT_DIR, "package.json") : import.meta.url);
const fontkit = require("fontkit");

const FONT = join(here, "..", "public", "fonts", "inter-latin-600-normal.woff2");
const OUT = join(here, "..", "src", "components", "Wordmark.astro");
const WORD = "embody";
const TRACK = 2.5; // extra units between letters (~0.025em), a touch of tracking at small sizes
const BASE = 100; // SVG y of the baseline; 1em = 100 units

const font = fontkit.openSync(FONT);
const S = 100 / font.unitsPerEm;
const run = font.layout(WORD);
const f1 = (n) => (Math.round(n * 10) / 10).toString();

// --- letters as one path (font y up -> SVG y down) ---
let x = 0;
const glyphs = [];
for (const [i, g] of run.glyphs.entries()) {
  glyphs.push({ ch: WORD[i], g, x });
  x += run.positions[i].xAdvance * S + TRACK;
}
const letters = glyphs.map(({ g, x }) => g.path.transform(S, 0, 0, -S, x, BASE).toSVG()).join(" ");

// --- geometry (font units scaled, y up, local to each glyph) ---
const pts = (g) => g.path.commands.filter((c) => c.command !== "closePath").map((c) => ({ x: c.args[c.args.length - 2] * S, y: c.args[c.args.length - 1] * S }));
const gy = glyphs[5], gb = glyphs[2], ge = glyphs[0];

// The y's terminal cut: its two lowest-left vertices (outer edge end, inner edge start).
const yp = pts(gy.g).filter((p) => p.y < -8);
const cutA = yp.reduce((a, p) => (p.x < a.x ? p : a)); // (6.2, -19.5) outer end
const cutB = yp.filter((p) => p.x < 12 && p.y > -12).reduce((a, p) => (p.x < a.x ? p : a)); // (9.2, -9.6) inner end
const tailW = Math.hypot(cutA.x - cutB.x, cutA.y - cutB.y) * 0.97; // the cut is nearly perpendicular to the stroke
const tailMid = { x: (cutA.x + cutB.x) / 2 + gy.x, y: (cutA.y + cutB.y) / 2 };
const runY = tailMid.y; // the under-run keeps the hook's depth

// The b's stem: vertices on its top edge.
const bp = pts(gb.g);
const bTop = Math.max(...bp.map((p) => p.y));
const stemXs = bp.filter((p) => p.y > bTop - 0.5).map((p) => p.x);
const stemL = Math.min(...stemXs) + gb.x, stemR = Math.max(...stemXs) + gb.x;
const stemW = stemR - stemL;
const stemC = (stemL + stemR) / 2;
const W = tailW; // the stroke is the tail's width; it ends flush inside the wider stem top
const topY = bTop - W / 2; // over-run centreline: its top edge is the stem's top

// The e's left ink edge.
const eLeft = ge.g.bbox.minX * S + ge.x;
const R = 15; // corner radius of the enclosure
const L = eLeft - 9 - W / 2; // the enclosure's left side, clear of the e

const Y = (fy) => BASE - fy; // font y -> SVG y
const d = [
  // start inside the hook, pass through its terminal, ease level
  `M${f1(tailMid.x + 4.5)} ${f1(Y(runY - 0.6))}`,
  `L${f1(tailMid.x)} ${f1(Y(runY))}`,
  `C${f1(tailMid.x - 8)} ${f1(Y(runY + 1.4))} ${f1(tailMid.x - 14)} ${f1(Y(runY))} ${f1(tailMid.x - 20)} ${f1(Y(runY))}`,
  // under the word to the e, round its left with two tight corners
  `L${f1(L + R)} ${f1(Y(runY))}`,
  `A${R} ${R} 0 0 1 ${f1(L)} ${f1(Y(runY + R))}`,
  `L${f1(L)} ${f1(Y(topY - R))}`,
  `A${R} ${R} 0 0 1 ${f1(L + R)} ${f1(Y(topY))}`,
  // along the ascender line into the top of the b's stem: a square corner,
  // like the stem's own top, so the stem reads as turning left into the loop
  `L${f1(stemR + 0.4)} ${f1(Y(topY))}`
].join(" ");

// viewBox centred on the x-height band (so a flex parent centres the letters'
// visual mass), wide enough for the enclosure and the y.
const xhMid = Y(font.xHeight * S / 2);
const top = Y(bTop) - 6;
const half = xhMid - top;
const right = gy.x + gy.g.bbox.maxX * S + 3;
const left = L - W / 2 - 3;
const vb = `${f1(left)} ${f1(top)} ${f1(right - left)} ${f1(half * 2)}`;

const astro = `---
// GENERATED by scripts/wordmark.mjs from public/fonts/inter-latin-600-normal.woff2
// -- do not hand-edit; re-run the script. The "embody" wordmark with the loop
// that encloses it: the y's tail continued under the word, round the e, and
// back along the ascender line into the b's stem. Static paths (not live
// text) so the joins are exact in every browser. Colour is currentColor.
interface Props {
  class?: string;
}
const { class: className = "" } = Astro.props;
---

<svg class={\`wordmark \${className}\`.trim()} viewBox="${vb}" role="img" aria-label="embody">
  <path class="wordmark__letters" fill="currentColor" d="${letters}"></path>
  <path class="wordmark__loop" fill="none" stroke="currentColor" stroke-width="${f1(W)}" stroke-linejoin="round" stroke-linecap="butt" d="${d}"></path>
</svg>
`;
writeFileSync(OUT, astro, "utf8");
console.log(JSON.stringify({ tailMid, tailW: f1(tailW), stemL: f1(stemL), stemR: f1(stemR), stemW: f1(stemW), W: f1(W), topY: f1(topY), eLeft: f1(eLeft), L: f1(L), viewBox: vb, height_em: f1(half * 2 / 100) }));
