-- First-party Specimen sync. GENERATED by scripts/build-specimen-data.py from
-- REPO/specimens/. Do not edit by hand. ASCII only.
-- Production-safe: touches only the six first-party specimens (slug + author
-- 'envoy'), never deletes a specimen, never changes ids, created_at,
-- likes/views/copies, reactions, video, visibility or tier, and every
-- statement is gated on a difference, so a second run writes 0 rows. The
-- cover thumbnail_key IS synced (thumbnails/<sha256> of the repo image), so
-- the repo cover always wins; it points at a blob the uploader put in R2 first.
-- Production runs it ONLY via Platform CI (job sync-specimens), after the blobs
-- are in R2 and a D1 Time Travel bookmark is recorded. Local:
--   npx wrangler d1 execute embody --local --file=src/server/first-party-sync.sql

-- 1. FTS mirror rows, FIRST: the gate reads the pre-update row. Only on the
--    contentless_delete=1 table (migration 0005); on a plain content='' table
--    INSERT OR REPLACE keeps the old tokens, so it is skipped there.
INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT s.rowid, s.slug, 'Murmuration', 'A dense GPU particle swarm that flocks like a starling murmuration at dusk - cohering, separating, aligning, and flowing around a slow invisible attractor with curl-noise wander. True per-neighbor Reynolds flocking computed on the GPU (a Neighbor POP index list iterated in a GLSL POP), rendered as luminous additive point sprites.', 'simulation glsl pop flocking particles generative', u.handle, 'particlePOP neighborPOP glslPOP pointspriteMAT'
FROM specimens AS s JOIN users_profile AS u ON u.id = s.author_id
WHERE s.slug = 'murmuration' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'specimens_fts' AND instr(replace(lower(sql), ' ', ''), 'contentless_delete=1') > 0)
  AND (
      s.title IS NOT 'Murmuration'
   OR s.description IS NOT 'A dense GPU particle swarm that flocks like a starling murmuration at dusk - cohering, separating, aligning, and flowing around a slow invisible attractor with curl-noise wander. True per-neighbor Reynolds flocking computed on the GPU (a Neighbor POP index list iterated in a GLSL POP), rendered as luminous additive point sprites.'
   OR s.category IS NOT 'simulation'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 18
   OR s.family_summary IS NOT 'POP,MAT'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/94892459a2ac5c681bbff67068122bd49317f11c9dde6cdc711fd614a4551d59'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 6
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('simulation', 'glsl', 'pop', 'flocking', 'particles', 'generative')) <> 6
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'simulation')
  );

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT s.rowid, s.slug, 'Reaction-Diffusion (Gray-Scott)', 'A living Gray-Scott reaction-diffusion field. Two chemicals diffuse and react in a GPU feedback loop, growing organic maze and coral patterns that evolve continuously. Usable as a texture, displacement, or mask source.', 'feedback glsl generative simulation texture', u.handle, 'feedbackTOP glslTOP'
FROM specimens AS s JOIN users_profile AS u ON u.id = s.author_id
WHERE s.slug = 'reaction-diffusion' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'specimens_fts' AND instr(replace(lower(sql), ' ', ''), 'contentless_delete=1') > 0)
  AND (
      s.title IS NOT 'Reaction-Diffusion (Gray-Scott)'
   OR s.description IS NOT 'A living Gray-Scott reaction-diffusion field. Two chemicals diffuse and react in a GPU feedback loop, growing organic maze and coral patterns that evolve continuously. Usable as a texture, displacement, or mask source.'
   OR s.category IS NOT 'generative'
   OR s.level IS NOT 'intermediate'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 14
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/3850a364c8753fa5cbf8f9a9ec1c8b1dc9dfacfd04539a0b7a386c759185ec04'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 5
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('feedback', 'glsl', 'generative', 'simulation', 'texture')) <> 5
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'generative')
  );

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT s.rowid, s.slug, 'Kaleidoscope', 'A reusable kaleidoscope compositor. Folds any TOP (or its built-in animated source) into an N-fold mirrored mandala that rotates, twists, breathes, and tumbles. Drop it onto any visual via the External source mode.', 'compositing glsl mirror symmetry effect', u.handle, 'glslTOP switchTOP inTOP'
FROM specimens AS s JOIN users_profile AS u ON u.id = s.author_id
WHERE s.slug = 'kaleidoscope' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'specimens_fts' AND instr(replace(lower(sql), ' ', ''), 'contentless_delete=1') > 0)
  AND (
      s.title IS NOT 'Kaleidoscope'
   OR s.description IS NOT 'A reusable kaleidoscope compositor. Folds any TOP (or its built-in animated source) into an N-fold mirrored mandala that rotates, twists, breathes, and tumbles. Drop it onto any visual via the External source mode.'
   OR s.category IS NOT 'compositing'
   OR s.level IS NOT 'intermediate'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 11
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/b66ef37eb04a61f55c5ebb61f76ec0987f242f03dc85f449fe0d658c2f2b193d'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 5
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('compositing', 'glsl', 'mirror', 'symmetry', 'effect')) <> 5
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'compositing')
  );

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT s.rowid, s.slug, 'Ridged Mountain Terrain', 'A procedural snow-mountain scene. A GLSL POP compute shader displaces a grid into ridged-multifractal peaks that morph in place, shaded by a snow/rock GLSL MAT with elevation-based snow, sun/sky lighting, and atmospheric haze, composited under a procedural sky.', '3d glsl terrain geometry procedural', u.handle, 'glslPOP glslMAT gridPOP renderTOP'
FROM specimens AS s JOIN users_profile AS u ON u.id = s.author_id
WHERE s.slug = 'noise-terrain' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'specimens_fts' AND instr(replace(lower(sql), ' ', ''), 'contentless_delete=1') > 0)
  AND (
      s.title IS NOT 'Ridged Mountain Terrain'
   OR s.description IS NOT 'A procedural snow-mountain scene. A GLSL POP compute shader displaces a grid into ridged-multifractal peaks that morph in place, shaded by a snow/rock GLSL MAT with elevation-based snow, sun/sky lighting, and atmospheric haze, composited under a procedural sky.'
   OR s.category IS NOT '3d'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 20
   OR s.family_summary IS NOT 'POP,MAT,TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/83d35b87e363c9d7ae5e8c2a6c5b42c7f7f89268cdfbcfa7e48756a8bd1d7e75'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 5
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('3d', 'glsl', 'terrain', 'geometry', 'procedural')) <> 5
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = '3d')
  );

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT s.rowid, s.slug, 'Plasma (Sine Interference)', 'A flowing GPU plasma. Two sine-wave fields at slightly detuned scales beat against each other into shimmering moire fringes, a slow rotating domain warp bends the coordinates into liquid motion, and the result is mapped through a cyclic cosine palette. Self-contained and stateless - one GLSL TOP, no input, no feedback - so it drops in anywhere as a VJ loop, texture, or displacement source.', 'generative glsl plasma palette vj texture', u.handle, 'glslTOP'
FROM specimens AS s JOIN users_profile AS u ON u.id = s.author_id
WHERE s.slug = 'plasma-interference' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'specimens_fts' AND instr(replace(lower(sql), ' ', ''), 'contentless_delete=1') > 0)
  AND (
      s.title IS NOT 'Plasma (Sine Interference)'
   OR s.description IS NOT 'A flowing GPU plasma. Two sine-wave fields at slightly detuned scales beat against each other into shimmering moire fringes, a slow rotating domain warp bends the coordinates into liquid motion, and the result is mapped through a cyclic cosine palette. Self-contained and stateless - one GLSL TOP, no input, no feedback - so it drops in anywhere as a VJ loop, texture, or displacement source.'
   OR s.category IS NOT 'generative'
   OR s.level IS NOT 'intermediate'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 5
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/fe6ba80ec1e9bdc80a1e97fc30e971e7da205ae678b5116802da015e9cd9716e'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 6
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('generative', 'glsl', 'plasma', 'palette', 'vj', 'texture')) <> 6
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'generative')
  );

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT s.rowid, s.slug, 'Mandelbulb March', 'A raymarched 3D Mandelbulb fractal rendered entirely in one GLSL TOP. The classic distance estimator is marched per pixel against a slowly orbiting camera; orbit-trap values captured during iteration tint the surface, and soft shadows, a fresnel rim, and a proximity glow give it depth. No input, no feedback - a drop-in hero render, a looping VJ source, or a reference for distance-estimated raymarching.', 'raymarching sdf glsl fractal 3d mandelbulb', u.handle, 'glslTOP'
FROM specimens AS s JOIN users_profile AS u ON u.id = s.author_id
WHERE s.slug = 'mandelbulb-march' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'specimens_fts' AND instr(replace(lower(sql), ' ', ''), 'contentless_delete=1') > 0)
  AND (
      s.title IS NOT 'Mandelbulb March'
   OR s.description IS NOT 'A raymarched 3D Mandelbulb fractal rendered entirely in one GLSL TOP. The classic distance estimator is marched per pixel against a slowly orbiting camera; orbit-trap values captured during iteration tint the surface, and soft shadows, a fresnel rim, and a proximity glow give it depth. No input, no feedback - a drop-in hero render, a looping VJ source, or a reference for distance-estimated raymarching.'
   OR s.category IS NOT 'raymarching-sdf'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 5
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/ea8c356215365ad392ed202c1cf816304f89e390bfc6c9ddf1f2823de51b68c4'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 6
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('raymarching', 'sdf', 'glsl', 'fractal', '3d', 'mandelbulb')) <> 6
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'raymarching-sdf')
  );

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT s.rowid, s.slug, 'Prismatic Strata', 'Stacked jagged strata lit from above and wrapped in iridescent fog, a soft pulse of light rolling down through them once per loop, split into orange and azure fringes by a per-channel displacement, with light streaks that rise along the curved layers and bloom. The classic animated-ramp-displaced-by-animated-noise look rebuilt on the GPU: a Ramp TOP, three GLSL TOPs (one writing three color buffers), two Render Select TOPs and a Bloom TOP, looping seamlessly.', 'generative glsl strata displace chromatic streaks loop vj', u.handle, 'glslTOP rampTOP renderselectTOP bloomTOP'
FROM specimens AS s JOIN users_profile AS u ON u.id = s.author_id
WHERE s.slug = 'prismatic-strata' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'specimens_fts' AND instr(replace(lower(sql), ' ', ''), 'contentless_delete=1') > 0)
  AND (
      s.title IS NOT 'Prismatic Strata'
   OR s.description IS NOT 'Stacked jagged strata lit from above and wrapped in iridescent fog, a soft pulse of light rolling down through them once per loop, split into orange and azure fringes by a per-channel displacement, with light streaks that rise along the curved layers and bloom. The classic animated-ramp-displaced-by-animated-noise look rebuilt on the GPU: a Ramp TOP, three GLSL TOPs (one writing three color buffers), two Render Select TOPs and a Bloom TOP, looping seamlessly.'
   OR s.category IS NOT 'generative'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 18
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/394150ea06ef4684c215cecaa389956bdac50cc3d6c36dac975a655e112d020a'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 8
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('generative', 'glsl', 'strata', 'displace', 'chromatic', 'streaks', 'loop', 'vj')) <> 8
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'generative')
  );

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT s.rowid, s.slug, 'Thangka Mandala', 'A Tibetan-thangka mandala drawn from POP geometry: 29 parameterised layers (rippling field lines, petal rings, gold rings, beads, lace, vase treasures, the palace square behind a heavy ink wall with gold corner brackets, gates and medallions, lotus rings, a rosette and star at the centre) that breathe, tumble, spin and cross-fade colour in travelling waves, aged by a patchy worn-cloth finish. Every layer is a static copy chain; two GLSL POPs read all layer parameters from a texture buffer and do the whole drawing per frame. Loop mode snaps every rate for seamless renders.', 'generative pop glsl mandala geometry line loop vj', u.handle, 'glslPOP copyPOP circlePOP mergePOP shuffleCHOP lineMAT constantMAT glslTOP'
FROM specimens AS s JOIN users_profile AS u ON u.id = s.author_id
WHERE s.slug = 'mandala' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'specimens_fts' AND instr(replace(lower(sql), ' ', ''), 'contentless_delete=1') > 0)
  AND (
      s.title IS NOT 'Thangka Mandala'
   OR s.description IS NOT 'A Tibetan-thangka mandala drawn from POP geometry: 29 parameterised layers (rippling field lines, petal rings, gold rings, beads, lace, vase treasures, the palace square behind a heavy ink wall with gold corner brackets, gates and medallions, lotus rings, a rosette and star at the centre) that breathe, tumble, spin and cross-fade colour in travelling waves, aged by a patchy worn-cloth finish. Every layer is a static copy chain; two GLSL POPs read all layer parameters from a texture buffer and do the whole drawing per frame. Loop mode snaps every rate for seamless renders.'
   OR s.category IS NOT 'generative'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 414
   OR s.family_summary IS NOT 'POP,CHOP,MAT,TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/5e8463ab78b5239e95f8e13cb841de8d14b758506bd44aade97f760e8530ad86'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT 'c7e807322f5d94a31a27358ef4b94beb9229d9263aa672e6410310bbb187308e'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 8
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('generative', 'pop', 'glsl', 'mandala', 'geometry', 'line', 'loop', 'vj')) <> 8
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'generative')
  );

-- 2. Tags the six need (an existing tag row is never rewritten).
INSERT OR IGNORE INTO tags (id, name, slug) VALUES
  ('tag-simulation', 'simulation', 'simulation'),
  ('tag-glsl', 'glsl', 'glsl'),
  ('tag-pop', 'pop', 'pop'),
  ('tag-flocking', 'flocking', 'flocking'),
  ('tag-particles', 'particles', 'particles'),
  ('tag-generative', 'generative', 'generative'),
  ('tag-feedback', 'feedback', 'feedback'),
  ('tag-texture', 'texture', 'texture'),
  ('tag-compositing', 'compositing', 'compositing'),
  ('tag-mirror', 'mirror', 'mirror'),
  ('tag-symmetry', 'symmetry', 'symmetry'),
  ('tag-effect', 'effect', 'effect'),
  ('tag-3d', '3d', '3d'),
  ('tag-terrain', 'terrain', 'terrain'),
  ('tag-geometry', 'geometry', 'geometry'),
  ('tag-procedural', 'procedural', 'procedural'),
  ('tag-plasma', 'plasma', 'plasma'),
  ('tag-palette', 'palette', 'palette'),
  ('tag-vj', 'vj', 'vj'),
  ('tag-raymarching', 'raymarching', 'raymarching'),
  ('tag-sdf', 'sdf', 'sdf'),
  ('tag-fractal', 'fractal', 'fractal'),
  ('tag-mandelbulb', 'mandelbulb', 'mandelbulb'),
  ('tag-strata', 'strata', 'strata'),
  ('tag-displace', 'displace', 'displace'),
  ('tag-chromatic', 'chromatic', 'chromatic'),
  ('tag-streaks', 'streaks', 'streaks'),
  ('tag-loop', 'loop', 'loop'),
  ('tag-mandala', 'mandala', 'mandala'),
  ('tag-line', 'line', 'line');

-- murmuration: specimens/simulation/murmuration.tdxn sha256=5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d size=13697
-- Version row for the repo blob, unless this specimen already has one.
INSERT INTO specimen_versions (id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id, signature_ref, changelog)
SELECT 'ver-murmuration-5c956da2481bc86b', s.id, (SELECT COALESCE(MAX(v.version_num), 0) + 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id), '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d', '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d', 13697, 18, 'scan-murmuration-5c956da2481bc86b', NULL, 'First-party sync of specimens/simulation/murmuration.tdxn'
FROM specimens AS s
WHERE s.slug = 'murmuration' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND NOT EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d');
INSERT INTO scans (id, version_id, scanner_version, verdict, capability_json, findings_json)
SELECT 'scan-murmuration-5c956da2481bc86b', 'ver-murmuration-5c956da2481bc86b', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'
WHERE EXISTS (SELECT 1 FROM specimen_versions WHERE id = 'ver-murmuration-5c956da2481bc86b') AND NOT EXISTS (SELECT 1 FROM scans WHERE id = 'scan-murmuration-5c956da2481bc86b');
-- Metadata, cover + current version. Engagement, visibility, tier, video untouched.
UPDATE specimens AS s
SET title = 'Murmuration', description = 'A dense GPU particle swarm that flocks like a starling murmuration at dusk - cohering, separating, aligning, and flowing around a slow invisible attractor with curl-noise wander. True per-neighbor Reynolds flocking computed on the GPU (a Neighbor POP index list iterated in a GLSL POP), rendered as luminous additive point sprites.', category = 'simulation', level = 'advanced', requires = '[]', op_count = 18, family_summary = 'POP,MAT', license = 'CC-BY-4.0', scan_status = 'clean', capability_json = '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', thumbnail_key = 'thumbnails/94892459a2ac5c681bbff67068122bd49317f11c9dde6cdc711fd614a4551d59',
    current_version_id = (SELECT v.id FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d' ORDER BY v.version_num DESC LIMIT 1),
    updated_at = datetime('now')
WHERE s.slug = 'murmuration' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d')
  AND (
      s.title IS NOT 'Murmuration'
   OR s.description IS NOT 'A dense GPU particle swarm that flocks like a starling murmuration at dusk - cohering, separating, aligning, and flowing around a slow invisible attractor with curl-noise wander. True per-neighbor Reynolds flocking computed on the GPU (a Neighbor POP index list iterated in a GLSL POP), rendered as luminous additive point sprites.'
   OR s.category IS NOT 'simulation'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 18
   OR s.family_summary IS NOT 'POP,MAT'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/94892459a2ac5c681bbff67068122bd49317f11c9dde6cdc711fd614a4551d59'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 6
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('simulation', 'glsl', 'pop', 'flocking', 'particles', 'generative')) <> 6
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'simulation')
  );
-- Tag and category sets: drop links the repo no longer lists, add missing ones.
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'murmuration' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND tag_id NOT IN (SELECT t.id FROM tags AS t WHERE t.slug IN ('simulation', 'glsl', 'pop', 'flocking', 'particles', 'generative'));
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) SELECT s.id, t.id FROM specimens AS s JOIN tags AS t ON t.slug IN ('simulation', 'glsl', 'pop', 'flocking', 'particles', 'generative') WHERE s.slug = 'murmuration' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'murmuration' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND category NOT IN ('simulation');
INSERT OR IGNORE INTO specimen_categories (specimen_id, category) SELECT s.id, 'simulation' FROM specimens AS s WHERE s.slug = 'murmuration' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');

-- reaction-diffusion: specimens/generative/reaction-diffusion.tdxn sha256=bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76 size=6850
-- Version row for the repo blob, unless this specimen already has one.
INSERT INTO specimen_versions (id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id, signature_ref, changelog)
SELECT 'ver-reaction-diffusion-bfbbf6a07197e1a3', s.id, (SELECT COALESCE(MAX(v.version_num), 0) + 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id), 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76', 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76', 6850, 14, 'scan-reaction-diffusion-bfbbf6a07197e1a3', NULL, 'First-party sync of specimens/generative/reaction-diffusion.tdxn'
FROM specimens AS s
WHERE s.slug = 'reaction-diffusion' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND NOT EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76');
INSERT INTO scans (id, version_id, scanner_version, verdict, capability_json, findings_json)
SELECT 'scan-reaction-diffusion-bfbbf6a07197e1a3', 'ver-reaction-diffusion-bfbbf6a07197e1a3', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'
WHERE EXISTS (SELECT 1 FROM specimen_versions WHERE id = 'ver-reaction-diffusion-bfbbf6a07197e1a3') AND NOT EXISTS (SELECT 1 FROM scans WHERE id = 'scan-reaction-diffusion-bfbbf6a07197e1a3');
-- Metadata, cover + current version. Engagement, visibility, tier, video untouched.
UPDATE specimens AS s
SET title = 'Reaction-Diffusion (Gray-Scott)', description = 'A living Gray-Scott reaction-diffusion field. Two chemicals diffuse and react in a GPU feedback loop, growing organic maze and coral patterns that evolve continuously. Usable as a texture, displacement, or mask source.', category = 'generative', level = 'intermediate', requires = '[]', op_count = 14, family_summary = 'TOP', license = 'CC-BY-4.0', scan_status = 'clean', capability_json = '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', thumbnail_key = 'thumbnails/3850a364c8753fa5cbf8f9a9ec1c8b1dc9dfacfd04539a0b7a386c759185ec04',
    current_version_id = (SELECT v.id FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76' ORDER BY v.version_num DESC LIMIT 1),
    updated_at = datetime('now')
WHERE s.slug = 'reaction-diffusion' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76')
  AND (
      s.title IS NOT 'Reaction-Diffusion (Gray-Scott)'
   OR s.description IS NOT 'A living Gray-Scott reaction-diffusion field. Two chemicals diffuse and react in a GPU feedback loop, growing organic maze and coral patterns that evolve continuously. Usable as a texture, displacement, or mask source.'
   OR s.category IS NOT 'generative'
   OR s.level IS NOT 'intermediate'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 14
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/3850a364c8753fa5cbf8f9a9ec1c8b1dc9dfacfd04539a0b7a386c759185ec04'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 5
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('feedback', 'glsl', 'generative', 'simulation', 'texture')) <> 5
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'generative')
  );
-- Tag and category sets: drop links the repo no longer lists, add missing ones.
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'reaction-diffusion' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND tag_id NOT IN (SELECT t.id FROM tags AS t WHERE t.slug IN ('feedback', 'glsl', 'generative', 'simulation', 'texture'));
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) SELECT s.id, t.id FROM specimens AS s JOIN tags AS t ON t.slug IN ('feedback', 'glsl', 'generative', 'simulation', 'texture') WHERE s.slug = 'reaction-diffusion' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'reaction-diffusion' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND category NOT IN ('generative');
INSERT OR IGNORE INTO specimen_categories (specimen_id, category) SELECT s.id, 'generative' FROM specimens AS s WHERE s.slug = 'reaction-diffusion' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');

-- kaleidoscope: specimens/compositing/kaleidoscope.tdxn sha256=295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103 size=8005
-- Version row for the repo blob, unless this specimen already has one.
INSERT INTO specimen_versions (id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id, signature_ref, changelog)
SELECT 'ver-kaleidoscope-295f25faf270440a', s.id, (SELECT COALESCE(MAX(v.version_num), 0) + 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id), '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103', '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103', 8005, 11, 'scan-kaleidoscope-295f25faf270440a', NULL, 'First-party sync of specimens/compositing/kaleidoscope.tdxn'
FROM specimens AS s
WHERE s.slug = 'kaleidoscope' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND NOT EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103');
INSERT INTO scans (id, version_id, scanner_version, verdict, capability_json, findings_json)
SELECT 'scan-kaleidoscope-295f25faf270440a', 'ver-kaleidoscope-295f25faf270440a', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'
WHERE EXISTS (SELECT 1 FROM specimen_versions WHERE id = 'ver-kaleidoscope-295f25faf270440a') AND NOT EXISTS (SELECT 1 FROM scans WHERE id = 'scan-kaleidoscope-295f25faf270440a');
-- Metadata, cover + current version. Engagement, visibility, tier, video untouched.
UPDATE specimens AS s
SET title = 'Kaleidoscope', description = 'A reusable kaleidoscope compositor. Folds any TOP (or its built-in animated source) into an N-fold mirrored mandala that rotates, twists, breathes, and tumbles. Drop it onto any visual via the External source mode.', category = 'compositing', level = 'intermediate', requires = '[]', op_count = 11, family_summary = 'TOP', license = 'CC-BY-4.0', scan_status = 'clean', capability_json = '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', thumbnail_key = 'thumbnails/b66ef37eb04a61f55c5ebb61f76ec0987f242f03dc85f449fe0d658c2f2b193d',
    current_version_id = (SELECT v.id FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103' ORDER BY v.version_num DESC LIMIT 1),
    updated_at = datetime('now')
WHERE s.slug = 'kaleidoscope' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103')
  AND (
      s.title IS NOT 'Kaleidoscope'
   OR s.description IS NOT 'A reusable kaleidoscope compositor. Folds any TOP (or its built-in animated source) into an N-fold mirrored mandala that rotates, twists, breathes, and tumbles. Drop it onto any visual via the External source mode.'
   OR s.category IS NOT 'compositing'
   OR s.level IS NOT 'intermediate'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 11
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/b66ef37eb04a61f55c5ebb61f76ec0987f242f03dc85f449fe0d658c2f2b193d'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 5
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('compositing', 'glsl', 'mirror', 'symmetry', 'effect')) <> 5
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'compositing')
  );
-- Tag and category sets: drop links the repo no longer lists, add missing ones.
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'kaleidoscope' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND tag_id NOT IN (SELECT t.id FROM tags AS t WHERE t.slug IN ('compositing', 'glsl', 'mirror', 'symmetry', 'effect'));
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) SELECT s.id, t.id FROM specimens AS s JOIN tags AS t ON t.slug IN ('compositing', 'glsl', 'mirror', 'symmetry', 'effect') WHERE s.slug = 'kaleidoscope' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'kaleidoscope' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND category NOT IN ('compositing');
INSERT OR IGNORE INTO specimen_categories (specimen_id, category) SELECT s.id, 'compositing' FROM specimens AS s WHERE s.slug = 'kaleidoscope' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');

-- noise-terrain: specimens/3d/noise-terrain.tdxn sha256=12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5 size=23789
-- Version row for the repo blob, unless this specimen already has one.
INSERT INTO specimen_versions (id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id, signature_ref, changelog)
SELECT 'ver-noise-terrain-12d74dd5e88d6276', s.id, (SELECT COALESCE(MAX(v.version_num), 0) + 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id), '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5', '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5', 23789, 20, 'scan-noise-terrain-12d74dd5e88d6276', NULL, 'First-party sync of specimens/3d/noise-terrain.tdxn'
FROM specimens AS s
WHERE s.slug = 'noise-terrain' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND NOT EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5');
INSERT INTO scans (id, version_id, scanner_version, verdict, capability_json, findings_json)
SELECT 'scan-noise-terrain-12d74dd5e88d6276', 'ver-noise-terrain-12d74dd5e88d6276', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'
WHERE EXISTS (SELECT 1 FROM specimen_versions WHERE id = 'ver-noise-terrain-12d74dd5e88d6276') AND NOT EXISTS (SELECT 1 FROM scans WHERE id = 'scan-noise-terrain-12d74dd5e88d6276');
-- Metadata, cover + current version. Engagement, visibility, tier, video untouched.
UPDATE specimens AS s
SET title = 'Ridged Mountain Terrain', description = 'A procedural snow-mountain scene. A GLSL POP compute shader displaces a grid into ridged-multifractal peaks that morph in place, shaded by a snow/rock GLSL MAT with elevation-based snow, sun/sky lighting, and atmospheric haze, composited under a procedural sky.', category = '3d', level = 'advanced', requires = '[]', op_count = 20, family_summary = 'POP,MAT,TOP', license = 'CC-BY-4.0', scan_status = 'clean', capability_json = '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', thumbnail_key = 'thumbnails/83d35b87e363c9d7ae5e8c2a6c5b42c7f7f89268cdfbcfa7e48756a8bd1d7e75',
    current_version_id = (SELECT v.id FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5' ORDER BY v.version_num DESC LIMIT 1),
    updated_at = datetime('now')
WHERE s.slug = 'noise-terrain' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5')
  AND (
      s.title IS NOT 'Ridged Mountain Terrain'
   OR s.description IS NOT 'A procedural snow-mountain scene. A GLSL POP compute shader displaces a grid into ridged-multifractal peaks that morph in place, shaded by a snow/rock GLSL MAT with elevation-based snow, sun/sky lighting, and atmospheric haze, composited under a procedural sky.'
   OR s.category IS NOT '3d'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 20
   OR s.family_summary IS NOT 'POP,MAT,TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/83d35b87e363c9d7ae5e8c2a6c5b42c7f7f89268cdfbcfa7e48756a8bd1d7e75'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 5
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('3d', 'glsl', 'terrain', 'geometry', 'procedural')) <> 5
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = '3d')
  );
-- Tag and category sets: drop links the repo no longer lists, add missing ones.
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'noise-terrain' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND tag_id NOT IN (SELECT t.id FROM tags AS t WHERE t.slug IN ('3d', 'glsl', 'terrain', 'geometry', 'procedural'));
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) SELECT s.id, t.id FROM specimens AS s JOIN tags AS t ON t.slug IN ('3d', 'glsl', 'terrain', 'geometry', 'procedural') WHERE s.slug = 'noise-terrain' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'noise-terrain' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND category NOT IN ('3d');
INSERT OR IGNORE INTO specimen_categories (specimen_id, category) SELECT s.id, '3d' FROM specimens AS s WHERE s.slug = 'noise-terrain' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');

-- plasma-interference: specimens/generative/plasma-interference.tdxn sha256=532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63 size=6980
-- Version row for the repo blob, unless this specimen already has one.
INSERT INTO specimen_versions (id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id, signature_ref, changelog)
SELECT 'ver-plasma-interference-532989ed224f716a', s.id, (SELECT COALESCE(MAX(v.version_num), 0) + 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id), '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63', '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63', 6980, 5, 'scan-plasma-interference-532989ed224f716a', NULL, 'First-party sync of specimens/generative/plasma-interference.tdxn'
FROM specimens AS s
WHERE s.slug = 'plasma-interference' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND NOT EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63');
INSERT INTO scans (id, version_id, scanner_version, verdict, capability_json, findings_json)
SELECT 'scan-plasma-interference-532989ed224f716a', 'ver-plasma-interference-532989ed224f716a', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'
WHERE EXISTS (SELECT 1 FROM specimen_versions WHERE id = 'ver-plasma-interference-532989ed224f716a') AND NOT EXISTS (SELECT 1 FROM scans WHERE id = 'scan-plasma-interference-532989ed224f716a');
-- Metadata, cover + current version. Engagement, visibility, tier, video untouched.
UPDATE specimens AS s
SET title = 'Plasma (Sine Interference)', description = 'A flowing GPU plasma. Two sine-wave fields at slightly detuned scales beat against each other into shimmering moire fringes, a slow rotating domain warp bends the coordinates into liquid motion, and the result is mapped through a cyclic cosine palette. Self-contained and stateless - one GLSL TOP, no input, no feedback - so it drops in anywhere as a VJ loop, texture, or displacement source.', category = 'generative', level = 'intermediate', requires = '[]', op_count = 5, family_summary = 'TOP', license = 'CC-BY-4.0', scan_status = 'clean', capability_json = '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', thumbnail_key = 'thumbnails/fe6ba80ec1e9bdc80a1e97fc30e971e7da205ae678b5116802da015e9cd9716e',
    current_version_id = (SELECT v.id FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63' ORDER BY v.version_num DESC LIMIT 1),
    updated_at = datetime('now')
WHERE s.slug = 'plasma-interference' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63')
  AND (
      s.title IS NOT 'Plasma (Sine Interference)'
   OR s.description IS NOT 'A flowing GPU plasma. Two sine-wave fields at slightly detuned scales beat against each other into shimmering moire fringes, a slow rotating domain warp bends the coordinates into liquid motion, and the result is mapped through a cyclic cosine palette. Self-contained and stateless - one GLSL TOP, no input, no feedback - so it drops in anywhere as a VJ loop, texture, or displacement source.'
   OR s.category IS NOT 'generative'
   OR s.level IS NOT 'intermediate'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 5
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/fe6ba80ec1e9bdc80a1e97fc30e971e7da205ae678b5116802da015e9cd9716e'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 6
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('generative', 'glsl', 'plasma', 'palette', 'vj', 'texture')) <> 6
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'generative')
  );
-- Tag and category sets: drop links the repo no longer lists, add missing ones.
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'plasma-interference' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND tag_id NOT IN (SELECT t.id FROM tags AS t WHERE t.slug IN ('generative', 'glsl', 'plasma', 'palette', 'vj', 'texture'));
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) SELECT s.id, t.id FROM specimens AS s JOIN tags AS t ON t.slug IN ('generative', 'glsl', 'plasma', 'palette', 'vj', 'texture') WHERE s.slug = 'plasma-interference' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'plasma-interference' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND category NOT IN ('generative');
INSERT OR IGNORE INTO specimen_categories (specimen_id, category) SELECT s.id, 'generative' FROM specimens AS s WHERE s.slug = 'plasma-interference' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');

-- mandelbulb-march: specimens/raymarching-sdf/mandelbulb-march.tdxn sha256=9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d size=10257
-- Version row for the repo blob, unless this specimen already has one.
INSERT INTO specimen_versions (id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id, signature_ref, changelog)
SELECT 'ver-mandelbulb-march-9ef1afa22149ebc3', s.id, (SELECT COALESCE(MAX(v.version_num), 0) + 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id), '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d', '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d', 10257, 5, 'scan-mandelbulb-march-9ef1afa22149ebc3', NULL, 'First-party sync of specimens/raymarching-sdf/mandelbulb-march.tdxn'
FROM specimens AS s
WHERE s.slug = 'mandelbulb-march' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND NOT EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d');
INSERT INTO scans (id, version_id, scanner_version, verdict, capability_json, findings_json)
SELECT 'scan-mandelbulb-march-9ef1afa22149ebc3', 'ver-mandelbulb-march-9ef1afa22149ebc3', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'
WHERE EXISTS (SELECT 1 FROM specimen_versions WHERE id = 'ver-mandelbulb-march-9ef1afa22149ebc3') AND NOT EXISTS (SELECT 1 FROM scans WHERE id = 'scan-mandelbulb-march-9ef1afa22149ebc3');
-- Metadata, cover + current version. Engagement, visibility, tier, video untouched.
UPDATE specimens AS s
SET title = 'Mandelbulb March', description = 'A raymarched 3D Mandelbulb fractal rendered entirely in one GLSL TOP. The classic distance estimator is marched per pixel against a slowly orbiting camera; orbit-trap values captured during iteration tint the surface, and soft shadows, a fresnel rim, and a proximity glow give it depth. No input, no feedback - a drop-in hero render, a looping VJ source, or a reference for distance-estimated raymarching.', category = 'raymarching-sdf', level = 'advanced', requires = '[]', op_count = 5, family_summary = 'TOP', license = 'CC-BY-4.0', scan_status = 'clean', capability_json = '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', thumbnail_key = 'thumbnails/ea8c356215365ad392ed202c1cf816304f89e390bfc6c9ddf1f2823de51b68c4',
    current_version_id = (SELECT v.id FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d' ORDER BY v.version_num DESC LIMIT 1),
    updated_at = datetime('now')
WHERE s.slug = 'mandelbulb-march' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d')
  AND (
      s.title IS NOT 'Mandelbulb March'
   OR s.description IS NOT 'A raymarched 3D Mandelbulb fractal rendered entirely in one GLSL TOP. The classic distance estimator is marched per pixel against a slowly orbiting camera; orbit-trap values captured during iteration tint the surface, and soft shadows, a fresnel rim, and a proximity glow give it depth. No input, no feedback - a drop-in hero render, a looping VJ source, or a reference for distance-estimated raymarching.'
   OR s.category IS NOT 'raymarching-sdf'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 5
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/ea8c356215365ad392ed202c1cf816304f89e390bfc6c9ddf1f2823de51b68c4'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 6
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('raymarching', 'sdf', 'glsl', 'fractal', '3d', 'mandelbulb')) <> 6
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'raymarching-sdf')
  );
-- Tag and category sets: drop links the repo no longer lists, add missing ones.
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'mandelbulb-march' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND tag_id NOT IN (SELECT t.id FROM tags AS t WHERE t.slug IN ('raymarching', 'sdf', 'glsl', 'fractal', '3d', 'mandelbulb'));
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) SELECT s.id, t.id FROM specimens AS s JOIN tags AS t ON t.slug IN ('raymarching', 'sdf', 'glsl', 'fractal', '3d', 'mandelbulb') WHERE s.slug = 'mandelbulb-march' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'mandelbulb-march' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND category NOT IN ('raymarching-sdf');
INSERT OR IGNORE INTO specimen_categories (specimen_id, category) SELECT s.id, 'raymarching-sdf' FROM specimens AS s WHERE s.slug = 'mandelbulb-march' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');

-- prismatic-strata: specimens/generative/prismatic-strata.tdxn sha256=85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21 size=34394
-- Version row for the repo blob, unless this specimen already has one.
INSERT INTO specimen_versions (id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id, signature_ref, changelog)
SELECT 'ver-prismatic-strata-85dd9eb6e4ca3002', s.id, (SELECT COALESCE(MAX(v.version_num), 0) + 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id), '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21', '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21', 34394, 18, 'scan-prismatic-strata-85dd9eb6e4ca3002', NULL, 'First-party sync of specimens/generative/prismatic-strata.tdxn'
FROM specimens AS s
WHERE s.slug = 'prismatic-strata' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND NOT EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21');
INSERT INTO scans (id, version_id, scanner_version, verdict, capability_json, findings_json)
SELECT 'scan-prismatic-strata-85dd9eb6e4ca3002', 'ver-prismatic-strata-85dd9eb6e4ca3002', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'
WHERE EXISTS (SELECT 1 FROM specimen_versions WHERE id = 'ver-prismatic-strata-85dd9eb6e4ca3002') AND NOT EXISTS (SELECT 1 FROM scans WHERE id = 'scan-prismatic-strata-85dd9eb6e4ca3002');
-- Metadata, cover + current version. Engagement, visibility, tier, video untouched.
UPDATE specimens AS s
SET title = 'Prismatic Strata', description = 'Stacked jagged strata lit from above and wrapped in iridescent fog, a soft pulse of light rolling down through them once per loop, split into orange and azure fringes by a per-channel displacement, with light streaks that rise along the curved layers and bloom. The classic animated-ramp-displaced-by-animated-noise look rebuilt on the GPU: a Ramp TOP, three GLSL TOPs (one writing three color buffers), two Render Select TOPs and a Bloom TOP, looping seamlessly.', category = 'generative', level = 'advanced', requires = '[]', op_count = 18, family_summary = 'TOP', license = 'CC-BY-4.0', scan_status = 'clean', capability_json = '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', thumbnail_key = 'thumbnails/394150ea06ef4684c215cecaa389956bdac50cc3d6c36dac975a655e112d020a',
    current_version_id = (SELECT v.id FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21' ORDER BY v.version_num DESC LIMIT 1),
    updated_at = datetime('now')
WHERE s.slug = 'prismatic-strata' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21')
  AND (
      s.title IS NOT 'Prismatic Strata'
   OR s.description IS NOT 'Stacked jagged strata lit from above and wrapped in iridescent fog, a soft pulse of light rolling down through them once per loop, split into orange and azure fringes by a per-channel displacement, with light streaks that rise along the curved layers and bloom. The classic animated-ramp-displaced-by-animated-noise look rebuilt on the GPU: a Ramp TOP, three GLSL TOPs (one writing three color buffers), two Render Select TOPs and a Bloom TOP, looping seamlessly.'
   OR s.category IS NOT 'generative'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 18
   OR s.family_summary IS NOT 'TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/394150ea06ef4684c215cecaa389956bdac50cc3d6c36dac975a655e112d020a'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 8
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('generative', 'glsl', 'strata', 'displace', 'chromatic', 'streaks', 'loop', 'vj')) <> 8
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'generative')
  );
-- Tag and category sets: drop links the repo no longer lists, add missing ones.
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'prismatic-strata' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND tag_id NOT IN (SELECT t.id FROM tags AS t WHERE t.slug IN ('generative', 'glsl', 'strata', 'displace', 'chromatic', 'streaks', 'loop', 'vj'));
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) SELECT s.id, t.id FROM specimens AS s JOIN tags AS t ON t.slug IN ('generative', 'glsl', 'strata', 'displace', 'chromatic', 'streaks', 'loop', 'vj') WHERE s.slug = 'prismatic-strata' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'prismatic-strata' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND category NOT IN ('generative');
INSERT OR IGNORE INTO specimen_categories (specimen_id, category) SELECT s.id, 'generative' FROM specimens AS s WHERE s.slug = 'prismatic-strata' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');

-- mandala: specimens/generative/mandala.tdxn sha256=c7e807322f5d94a31a27358ef4b94beb9229d9263aa672e6410310bbb187308e size=280674
-- Version row for the repo blob, unless this specimen already has one.
INSERT INTO specimen_versions (id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id, signature_ref, changelog)
SELECT 'ver-mandala-c7e807322f5d94a3', s.id, (SELECT COALESCE(MAX(v.version_num), 0) + 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id), 'c7e807322f5d94a31a27358ef4b94beb9229d9263aa672e6410310bbb187308e', 'c7e807322f5d94a31a27358ef4b94beb9229d9263aa672e6410310bbb187308e', 280674, 414, 'scan-mandala-c7e807322f5d94a3', NULL, 'First-party sync of specimens/generative/mandala.tdxn'
FROM specimens AS s
WHERE s.slug = 'mandala' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND NOT EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = 'c7e807322f5d94a31a27358ef4b94beb9229d9263aa672e6410310bbb187308e');
INSERT INTO scans (id, version_id, scanner_version, verdict, capability_json, findings_json)
SELECT 'scan-mandala-c7e807322f5d94a3', 'ver-mandala-c7e807322f5d94a3', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'
WHERE EXISTS (SELECT 1 FROM specimen_versions WHERE id = 'ver-mandala-c7e807322f5d94a3') AND NOT EXISTS (SELECT 1 FROM scans WHERE id = 'scan-mandala-c7e807322f5d94a3');
-- Metadata, cover + current version. Engagement, visibility, tier, video untouched.
UPDATE specimens AS s
SET title = 'Thangka Mandala', description = 'A Tibetan-thangka mandala drawn from POP geometry: 29 parameterised layers (rippling field lines, petal rings, gold rings, beads, lace, vase treasures, the palace square behind a heavy ink wall with gold corner brackets, gates and medallions, lotus rings, a rosette and star at the centre) that breathe, tumble, spin and cross-fade colour in travelling waves, aged by a patchy worn-cloth finish. Every layer is a static copy chain; two GLSL POPs read all layer parameters from a texture buffer and do the whole drawing per frame. Loop mode snaps every rate for seamless renders.', category = 'generative', level = 'advanced', requires = '[]', op_count = 414, family_summary = 'POP,CHOP,MAT,TOP', license = 'CC-BY-4.0', scan_status = 'clean', capability_json = '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', thumbnail_key = 'thumbnails/5e8463ab78b5239e95f8e13cb841de8d14b758506bd44aade97f760e8530ad86',
    current_version_id = (SELECT v.id FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = 'c7e807322f5d94a31a27358ef4b94beb9229d9263aa672e6410310bbb187308e' ORDER BY v.version_num DESC LIMIT 1),
    updated_at = datetime('now')
WHERE s.slug = 'mandala' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')
  AND EXISTS (SELECT 1 FROM specimen_versions AS v WHERE v.specimen_id = s.id AND v.tdn_sha256 = 'c7e807322f5d94a31a27358ef4b94beb9229d9263aa672e6410310bbb187308e')
  AND (
      s.title IS NOT 'Thangka Mandala'
   OR s.description IS NOT 'A Tibetan-thangka mandala drawn from POP geometry: 29 parameterised layers (rippling field lines, petal rings, gold rings, beads, lace, vase treasures, the palace square behind a heavy ink wall with gold corner brackets, gates and medallions, lotus rings, a rosette and star at the centre) that breathe, tumble, spin and cross-fade colour in travelling waves, aged by a patchy worn-cloth finish. Every layer is a static copy chain; two GLSL POPs read all layer parameters from a texture buffer and do the whole drawing per frame. Loop mode snaps every rate for seamless renders.'
   OR s.category IS NOT 'generative'
   OR s.level IS NOT 'advanced'
   OR s.requires IS NOT '[]'
   OR s.op_count IS NOT 414
   OR s.family_summary IS NOT 'POP,CHOP,MAT,TOP'
   OR s.license IS NOT 'CC-BY-4.0'
   OR s.scan_status IS NOT 'clean'
   OR s.capability_json IS NOT '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}'
   OR s.thumbnail_key IS NOT 'thumbnails/5e8463ab78b5239e95f8e13cb841de8d14b758506bd44aade97f760e8530ad86'
   OR (SELECT v.tdn_sha256 FROM specimen_versions AS v WHERE v.id = s.current_version_id) IS NOT 'c7e807322f5d94a31a27358ef4b94beb9229d9263aa672e6410310bbb187308e'
   OR (SELECT COUNT(*) FROM specimen_tags AS st WHERE st.specimen_id = s.id) <> 8
   OR (SELECT COUNT(*) FROM specimen_tags AS st JOIN tags AS t ON t.id = st.tag_id WHERE st.specimen_id = s.id AND t.slug IN ('generative', 'pop', 'glsl', 'mandala', 'geometry', 'line', 'loop', 'vj')) <> 8
   OR (SELECT COUNT(*) FROM specimen_categories AS sc WHERE sc.specimen_id = s.id) <> 1
   OR NOT EXISTS (SELECT 1 FROM specimen_categories AS sc WHERE sc.specimen_id = s.id AND sc.category = 'generative')
  );
-- Tag and category sets: drop links the repo no longer lists, add missing ones.
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'mandala' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND tag_id NOT IN (SELECT t.id FROM tags AS t WHERE t.slug IN ('generative', 'pop', 'glsl', 'mandala', 'geometry', 'line', 'loop', 'vj'));
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) SELECT s.id, t.id FROM specimens AS s JOIN tags AS t ON t.slug IN ('generative', 'pop', 'glsl', 'mandala', 'geometry', 'line', 'loop', 'vj') WHERE s.slug = 'mandala' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT s.id FROM specimens AS s WHERE s.slug = 'mandala' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy')) AND category NOT IN ('generative');
INSERT OR IGNORE INTO specimen_categories (specimen_id, category) SELECT s.id, 'generative' FROM specimens AS s WHERE s.slug = 'mandala' AND s.author_id IN (SELECT id FROM users_profile WHERE handle = 'envoy');
