-- Local development seed for the first-party Specimen collection.
-- GENERATED by scripts/build-specimen-data.py from REPO/specimens/. Do not edit by hand.
-- Re-runnable: purges fictional/test rows, then INSERT OR REPLACE the six real specimens.
-- Apply to the local D1 (matching the astro-dev miniflare persist path):
--   npx wrangler d1 execute embody --local --file=src/server/seed.sql
-- ASCII only.

-- Dev auth-stub user (kept; specimens reference it as author_id).
-- Handle is 'envoy' so the public user page resolves at /u/envoy and
-- matches the fallback author_handle in src/lib/specimenFallback.ts.
INSERT OR REPLACE INTO users_profile (id, handle, avatar_url, bio, trust_level)
VALUES ('dev-user', 'envoy', '/embody-mark.svg', 'First-party Embody specimen author. Curating the transparent TDXN Collection.', 'curator');

-- Rebuild the FTS5 mirror (contentless_delete=1, matching migration 0005).
DROP TABLE IF EXISTS specimens_fts;
CREATE VIRTUAL TABLE specimens_fts USING fts5(
  slug UNINDEXED, title, description, tags, author_handle, dat_text,
  content='', contentless_delete=1
);

-- Purge fictional placeholders and stray test specimens by slug.
DELETE FROM scans WHERE version_id IN (SELECT v.id FROM specimen_versions v JOIN specimens s ON s.id = v.specimen_id WHERE s.slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil'));
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT id FROM specimens WHERE slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil'));
DELETE FROM specimen_versions WHERE specimen_id IN (SELECT id FROM specimens WHERE slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil'));
DELETE FROM specimens WHERE slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil');

-- Purge any prior copy of these real specimens (clean re-run).
DELETE FROM scans WHERE version_id IN (SELECT id FROM specimen_versions WHERE specimen_id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march'));
DELETE FROM specimen_tags WHERE specimen_id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march');
DELETE FROM specimen_versions WHERE specimen_id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march');
DELETE FROM specimens WHERE id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march');

-- Tags (deduped across all specimens).
INSERT OR REPLACE INTO tags (id, name, slug) VALUES
  ('tag-simulation', 'simulation', 'simulation'),
  ('tag-glsl', 'glsl', 'glsl'),
  ('tag-pop', 'pop', 'pop'),
  ('tag-flocking', 'flocking', 'flocking'),
  ('tag-particles', 'particles', 'particles'),
  ('tag-generative', 'generative', 'generative'),
  ('tag-feedback', 'feedback', 'feedback'),
  ('tag-texture', 'texture', 'texture'),
  ('tag-compositing', 'compositing', 'compositing'),
  ('tag-mirror', 'mirror', 'mirror'),
  ('tag-symmetry', 'symmetry', 'symmetry'),
  ('tag-effect', 'effect', 'effect'),
  ('tag-3d', '3d', '3d'),
  ('tag-terrain', 'terrain', 'terrain'),
  ('tag-geometry', 'geometry', 'geometry'),
  ('tag-procedural', 'procedural', 'procedural'),
  ('tag-plasma', 'plasma', 'plasma'),
  ('tag-palette', 'palette', 'palette'),
  ('tag-vj', 'vj', 'vj'),
  ('tag-raymarching', 'raymarching', 'raymarching'),
  ('tag-sdf', 'sdf', 'sdf'),
  ('tag-fractal', 'fractal', 'fractal'),
  ('tag-mandelbulb', 'mandelbulb', 'mandelbulb');

-- Specimens (real first-party metadata from specimens/manifest.json).
INSERT OR REPLACE INTO specimens (
  id, slug, author_id, title, description, category, difficulty, requires, op_count,
  family_summary, current_version_id, thumbnail_key, license, visibility, tier, scan_status,
  capability_json, likes_count, views_count, copies_count
) VALUES
  (
    'sp-murmuration',
    'murmuration',
    'dev-user',
    'Murmuration',
    'A dense GPU particle swarm that flocks like a starling murmuration at dusk - cohering, separating, aligning, and flowing around a slow invisible attractor with curl-noise wander. True per-neighbor Reynolds flocking computed on the GPU (a Neighbor POP index list iterated in a GLSL POP), rendered as luminous additive point sprites.',
    'simulation',
    'advanced',
    '[]',
    18,
    'POP,MAT',
    'ver-murmuration',
    '',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-reaction-diffusion',
    'reaction-diffusion',
    'dev-user',
    'Reaction-Diffusion (Gray-Scott)',
    'A living Gray-Scott reaction-diffusion field. Two chemicals diffuse and react in a GPU feedback loop, growing organic maze and coral patterns that evolve continuously. Usable as a texture, displacement, or mask source.',
    'generative',
    'intermediate',
    '[]',
    14,
    'TOP',
    'ver-reaction-diffusion',
    '',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-kaleidoscope',
    'kaleidoscope',
    'dev-user',
    'Kaleidoscope',
    'A reusable kaleidoscope compositor. Folds any TOP (or its built-in animated source) into an N-fold mirrored mandala that rotates, twists, breathes, and tumbles. Drop it onto any visual via the External source mode.',
    'compositing',
    'intermediate',
    '[]',
    11,
    'TOP',
    'ver-kaleidoscope',
    '',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-noise-terrain',
    'noise-terrain',
    'dev-user',
    'Ridged Mountain Terrain',
    'A procedural snow-mountain scene. A GLSL POP compute shader displaces a grid into ridged-multifractal peaks that morph in place, shaded by a snow/rock GLSL MAT with elevation-based snow, sun/sky lighting, and atmospheric haze, composited under a procedural sky.',
    '3d',
    'advanced',
    '[]',
    20,
    'POP,MAT,TOP',
    'ver-noise-terrain',
    '',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-plasma-interference',
    'plasma-interference',
    'dev-user',
    'Plasma (Sine Interference)',
    'A flowing GPU plasma. Two sine-wave fields at slightly detuned scales beat against each other into shimmering moire fringes, a slow rotating domain warp bends the coordinates into liquid motion, and the result is mapped through a cyclic cosine palette. Self-contained and stateless - one GLSL TOP, no input, no feedback - so it drops in anywhere as a VJ loop, texture, or displacement source.',
    'generative',
    'intermediate',
    '[]',
    5,
    'TOP',
    'ver-plasma-interference',
    '',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-mandelbulb-march',
    'mandelbulb-march',
    'dev-user',
    'Mandelbulb March',
    'A raymarched 3D Mandelbulb fractal rendered entirely in one GLSL TOP. The classic distance estimator is marched per pixel against a slowly orbiting camera; orbit-trap values captured during iteration tint the surface, and soft shadows, a fresnel rim, and a proximity glow give it depth. No input, no feedback - a drop-in hero render, a looping VJ source, or a reference for distance-estimated raymarching.',
    'raymarching-sdf',
    'advanced',
    '[]',
    5,
    'TOP',
    'ver-mandelbulb-march',
    '',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  );

-- Versions (content-addressed: tdn_r2_key = tdn_sha256 = sha256 of the .tdxn bytes).
INSERT OR REPLACE INTO specimen_versions (
  id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id,
  signature_ref, changelog
) VALUES
  ('ver-murmuration', 'sp-murmuration', 1, '079d5f43f6b73f925c75c81d25309a63bfef4f878eeda93171dffe337e21dd2c', '079d5f43f6b73f925c75c81d25309a63bfef4f878eeda93171dffe337e21dd2c', 13920, 18, 'scan-murmuration', NULL, 'First-party specimen.'),
  ('ver-reaction-diffusion', 'sp-reaction-diffusion', 1, 'b937b4edab5c91639e9b32eecf56cf9cdff8c9bcd2f391d308246affae61bcc7', 'b937b4edab5c91639e9b32eecf56cf9cdff8c9bcd2f391d308246affae61bcc7', 7165, 14, 'scan-reaction-diffusion', NULL, 'First-party specimen.'),
  ('ver-kaleidoscope', 'sp-kaleidoscope', 1, '203ff060bd24f8fd0b006129a12b32609e1fdb54ec6bcc76d873bb25d1534363', '203ff060bd24f8fd0b006129a12b32609e1fdb54ec6bcc76d873bb25d1534363', 8206, 11, 'scan-kaleidoscope', NULL, 'First-party specimen.'),
  ('ver-noise-terrain', 'sp-noise-terrain', 1, '471730e201682b0963577b852c7249f89006ed995c7bbdcb5c8f463f080603c2', '471730e201682b0963577b852c7249f89006ed995c7bbdcb5c8f463f080603c2', 24041, 20, 'scan-noise-terrain', NULL, 'First-party specimen.'),
  ('ver-plasma-interference', 'sp-plasma-interference', 1, 'fd179f050bb38be404605c54bc036c26a5aaab1f7b0e4db3b46a81b4d223a4cd', 'fd179f050bb38be404605c54bc036c26a5aaab1f7b0e4db3b46a81b4d223a4cd', 7115, 5, 'scan-plasma-interference', NULL, 'First-party specimen.'),
  ('ver-mandelbulb-march', 'sp-mandelbulb-march', 1, 'bc2bd1a53a6f3c632e9e06c473340f60be3c707170a8c7da6e58500c86f2ff66', 'bc2bd1a53a6f3c632e9e06c473340f60be3c707170a8c7da6e58500c86f2ff66', 10410, 5, 'scan-mandelbulb-march', NULL, 'First-party specimen.');

-- Scans (clean verdict, empty capability surface).
INSERT OR REPLACE INTO scans (
  id, version_id, scanner_version, verdict, capability_json, findings_json
) VALUES
  ('scan-murmuration', 'ver-murmuration', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-reaction-diffusion', 'ver-reaction-diffusion', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-kaleidoscope', 'ver-kaleidoscope', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-noise-terrain', 'ver-noise-terrain', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-plasma-interference', 'ver-plasma-interference', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-mandelbulb-march', 'ver-mandelbulb-march', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]');

-- Specimen <-> tag links.
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) VALUES
  ('sp-murmuration', 'tag-simulation'),
  ('sp-murmuration', 'tag-glsl'),
  ('sp-murmuration', 'tag-pop'),
  ('sp-murmuration', 'tag-flocking'),
  ('sp-murmuration', 'tag-particles'),
  ('sp-murmuration', 'tag-generative'),
  ('sp-reaction-diffusion', 'tag-feedback'),
  ('sp-reaction-diffusion', 'tag-glsl'),
  ('sp-reaction-diffusion', 'tag-generative'),
  ('sp-reaction-diffusion', 'tag-simulation'),
  ('sp-reaction-diffusion', 'tag-texture'),
  ('sp-kaleidoscope', 'tag-compositing'),
  ('sp-kaleidoscope', 'tag-glsl'),
  ('sp-kaleidoscope', 'tag-mirror'),
  ('sp-kaleidoscope', 'tag-symmetry'),
  ('sp-kaleidoscope', 'tag-effect'),
  ('sp-noise-terrain', 'tag-3d'),
  ('sp-noise-terrain', 'tag-glsl'),
  ('sp-noise-terrain', 'tag-terrain'),
  ('sp-noise-terrain', 'tag-geometry'),
  ('sp-noise-terrain', 'tag-procedural'),
  ('sp-plasma-interference', 'tag-generative'),
  ('sp-plasma-interference', 'tag-glsl'),
  ('sp-plasma-interference', 'tag-plasma'),
  ('sp-plasma-interference', 'tag-palette'),
  ('sp-plasma-interference', 'tag-vj'),
  ('sp-plasma-interference', 'tag-texture'),
  ('sp-mandelbulb-march', 'tag-raymarching'),
  ('sp-mandelbulb-march', 'tag-sdf'),
  ('sp-mandelbulb-march', 'tag-glsl'),
  ('sp-mandelbulb-march', 'tag-fractal'),
  ('sp-mandelbulb-march', 'tag-3d'),
  ('sp-mandelbulb-march', 'tag-mandelbulb');

-- FTS5 keyword mirror (rowid = specimen rowid; dat_text = key_ops).
INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'murmuration', 'Murmuration', 'A dense GPU particle swarm that flocks like a starling murmuration at dusk - cohering, separating, aligning, and flowing around a slow invisible attractor with curl-noise wander. True per-neighbor Reynolds flocking computed on the GPU (a Neighbor POP index list iterated in a GLSL POP), rendered as luminous additive point sprites.', 'simulation glsl pop flocking particles generative', 'envoy', 'particlePOP neighborPOP glslPOP pointspriteMAT'
FROM specimens WHERE id = 'sp-murmuration';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'reaction-diffusion', 'Reaction-Diffusion (Gray-Scott)', 'A living Gray-Scott reaction-diffusion field. Two chemicals diffuse and react in a GPU feedback loop, growing organic maze and coral patterns that evolve continuously. Usable as a texture, displacement, or mask source.', 'feedback glsl generative simulation texture', 'envoy', 'feedbackTOP glslTOP'
FROM specimens WHERE id = 'sp-reaction-diffusion';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'kaleidoscope', 'Kaleidoscope', 'A reusable kaleidoscope compositor. Folds any TOP (or its built-in animated source) into an N-fold mirrored mandala that rotates, twists, breathes, and tumbles. Drop it onto any visual via the External source mode.', 'compositing glsl mirror symmetry effect', 'envoy', 'glslTOP switchTOP inTOP'
FROM specimens WHERE id = 'sp-kaleidoscope';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'noise-terrain', 'Ridged Mountain Terrain', 'A procedural snow-mountain scene. A GLSL POP compute shader displaces a grid into ridged-multifractal peaks that morph in place, shaded by a snow/rock GLSL MAT with elevation-based snow, sun/sky lighting, and atmospheric haze, composited under a procedural sky.', '3d glsl terrain geometry procedural', 'envoy', 'glslPOP glslMAT gridPOP renderTOP'
FROM specimens WHERE id = 'sp-noise-terrain';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'plasma-interference', 'Plasma (Sine Interference)', 'A flowing GPU plasma. Two sine-wave fields at slightly detuned scales beat against each other into shimmering moire fringes, a slow rotating domain warp bends the coordinates into liquid motion, and the result is mapped through a cyclic cosine palette. Self-contained and stateless - one GLSL TOP, no input, no feedback - so it drops in anywhere as a VJ loop, texture, or displacement source.', 'generative glsl plasma palette vj texture', 'envoy', 'glslTOP'
FROM specimens WHERE id = 'sp-plasma-interference';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'mandelbulb-march', 'Mandelbulb March', 'A raymarched 3D Mandelbulb fractal rendered entirely in one GLSL TOP. The classic distance estimator is marched per pixel against a slowly orbiting camera; orbit-trap values captured during iteration tint the surface, and soft shadows, a fresnel rim, and a proximity glow give it depth. No input, no feedback - a drop-in hero render, a looping VJ source, or a reference for distance-estimated raymarching.', 'raymarching sdf glsl fractal 3d mandelbulb', 'envoy', 'glslTOP'
FROM specimens WHERE id = 'sp-mandelbulb-march';
