-- LOCAL-ONLY development seed for the first-party Specimen collection.
-- NEVER run this with --remote: it drops and rebuilds specimens_fts (every
-- community specimen falls out of search), purges slugs, and re-creates the
-- six specimens (new created_at, zeroed counters). Production is updated only
-- by first-party-sync.sql through Platform CI (job sync-specimens).
-- GENERATED by scripts/build-specimen-data.py from REPO/specimens/. Do not edit by hand.
-- Re-runnable: purges fictional/test rows, then INSERT OR REPLACE the six real specimens.
-- Apply to the local D1 (matching the astro-dev miniflare persist path):
--   npx wrangler d1 execute embody --local --file=src/server/seed.sql
-- ASCII only.

-- Dev auth-stub user (kept; specimens reference it as author_id).
-- Handle is 'envoy' so the public user page resolves at /u/envoy and
-- matches the fallback author_handle in src/lib/specimenFallback.ts.
INSERT OR REPLACE INTO users_profile (id, handle, avatar_url, bio, trust_level)
VALUES ('dev-user', 'envoy', '/embody-mark.svg', 'First-party Embody specimen author. Curating the transparent TDXN Collection.', 'curator');

-- Rebuild the FTS5 mirror (contentless_delete=1, matching migration 0005).
DROP TABLE IF EXISTS specimens_fts;
CREATE VIRTUAL TABLE specimens_fts USING fts5(
  slug UNINDEXED, title, description, tags, author_handle, dat_text,
  content='', contentless_delete=1
);

-- Purge fictional placeholders and stray test specimens by slug.
DELETE FROM scans WHERE version_id IN (SELECT v.id FROM specimen_versions v JOIN specimens s ON s.id = v.specimen_id WHERE s.slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil'));
DELETE FROM specimen_tags WHERE specimen_id IN (SELECT id FROM specimens WHERE slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil'));
DELETE FROM specimen_versions WHERE specimen_id IN (SELECT id FROM specimens WHERE slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil'));
DELETE FROM specimen_categories WHERE specimen_id IN (SELECT id FROM specimens WHERE slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil'));
DELETE FROM specimens WHERE slug IN ('layered-noise-field', 'infinite-zoom-tunnel', 'curl-noise-swarm', 'spectrum-reactor', 'signed-distance-lantern', 'bloom-grade-stack', 'ev', 'clean2', 'ff', 'clean-net', 'evil');

-- Purge any prior copy of these real specimens (clean re-run).
DELETE FROM scans WHERE version_id IN (SELECT id FROM specimen_versions WHERE specimen_id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march', 'sp-prismatic-strata', 'sp-mandala'));
DELETE FROM specimen_tags WHERE specimen_id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march', 'sp-prismatic-strata', 'sp-mandala');
DELETE FROM specimen_versions WHERE specimen_id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march', 'sp-prismatic-strata', 'sp-mandala');
DELETE FROM specimen_categories WHERE specimen_id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march', 'sp-prismatic-strata', 'sp-mandala');
DELETE FROM specimens WHERE id IN ('sp-murmuration', 'sp-reaction-diffusion', 'sp-kaleidoscope', 'sp-noise-terrain', 'sp-plasma-interference', 'sp-mandelbulb-march', 'sp-prismatic-strata', 'sp-mandala');

-- Tags (deduped across all specimens).
INSERT OR REPLACE INTO tags (id, name, slug) VALUES
  ('tag-simulation', 'simulation', 'simulation'),
  ('tag-glsl', 'glsl', 'glsl'),
  ('tag-pop', 'pop', 'pop'),
  ('tag-flocking', 'flocking', 'flocking'),
  ('tag-particles', 'particles', 'particles'),
  ('tag-generative', 'generative', 'generative'),
  ('tag-feedback', 'feedback', 'feedback'),
  ('tag-texture', 'texture', 'texture'),
  ('tag-compositing', 'compositing', 'compositing'),
  ('tag-mirror', 'mirror', 'mirror'),
  ('tag-symmetry', 'symmetry', 'symmetry'),
  ('tag-effect', 'effect', 'effect'),
  ('tag-3d', '3d', '3d'),
  ('tag-terrain', 'terrain', 'terrain'),
  ('tag-geometry', 'geometry', 'geometry'),
  ('tag-procedural', 'procedural', 'procedural'),
  ('tag-plasma', 'plasma', 'plasma'),
  ('tag-palette', 'palette', 'palette'),
  ('tag-vj', 'vj', 'vj'),
  ('tag-raymarching', 'raymarching', 'raymarching'),
  ('tag-sdf', 'sdf', 'sdf'),
  ('tag-fractal', 'fractal', 'fractal'),
  ('tag-mandelbulb', 'mandelbulb', 'mandelbulb'),
  ('tag-strata', 'strata', 'strata'),
  ('tag-displace', 'displace', 'displace'),
  ('tag-chromatic', 'chromatic', 'chromatic'),
  ('tag-streaks', 'streaks', 'streaks'),
  ('tag-loop', 'loop', 'loop'),
  ('tag-mandala', 'mandala', 'mandala'),
  ('tag-line', 'line', 'line');

-- Specimens (real first-party metadata from specimens/manifest.json).
INSERT OR REPLACE INTO specimens (
  id, slug, author_id, title, description, category, level, requires, op_count,
  family_summary, current_version_id, thumbnail_key, license, visibility, tier, scan_status,
  capability_json, likes_count, views_count, copies_count
) VALUES
  (
    'sp-murmuration',
    'murmuration',
    'dev-user',
    'Murmuration',
    'A dense GPU particle swarm that flocks like a starling murmuration at dusk - cohering, separating, aligning, and flowing around a slow invisible attractor with curl-noise wander. True per-neighbor Reynolds flocking computed on the GPU (a Neighbor POP index list iterated in a GLSL POP), rendered as luminous additive point sprites.',
    'simulation',
    'advanced',
    '[]',
    18,
    'POP,MAT',
    'ver-murmuration',
    'thumbnails/94892459a2ac5c681bbff67068122bd49317f11c9dde6cdc711fd614a4551d59',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-reaction-diffusion',
    'reaction-diffusion',
    'dev-user',
    'Reaction-Diffusion (Gray-Scott)',
    'A living Gray-Scott reaction-diffusion field. Two chemicals diffuse and react in a GPU feedback loop, growing organic maze and coral patterns that evolve continuously. Usable as a texture, displacement, or mask source.',
    'generative',
    'intermediate',
    '[]',
    14,
    'TOP',
    'ver-reaction-diffusion',
    'thumbnails/3850a364c8753fa5cbf8f9a9ec1c8b1dc9dfacfd04539a0b7a386c759185ec04',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-kaleidoscope',
    'kaleidoscope',
    'dev-user',
    'Kaleidoscope',
    'A reusable kaleidoscope compositor. Folds any TOP (or its built-in animated source) into an N-fold mirrored mandala that rotates, twists, breathes, and tumbles. Drop it onto any visual via the External source mode.',
    'compositing',
    'intermediate',
    '[]',
    11,
    'TOP',
    'ver-kaleidoscope',
    'thumbnails/b66ef37eb04a61f55c5ebb61f76ec0987f242f03dc85f449fe0d658c2f2b193d',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-noise-terrain',
    'noise-terrain',
    'dev-user',
    'Ridged Mountain Terrain',
    'A procedural snow-mountain scene. A GLSL POP compute shader displaces a grid into ridged-multifractal peaks that morph in place, shaded by a snow/rock GLSL MAT with elevation-based snow, sun/sky lighting, and atmospheric haze, composited under a procedural sky.',
    '3d',
    'advanced',
    '[]',
    20,
    'POP,MAT,TOP',
    'ver-noise-terrain',
    'thumbnails/83d35b87e363c9d7ae5e8c2a6c5b42c7f7f89268cdfbcfa7e48756a8bd1d7e75',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-plasma-interference',
    'plasma-interference',
    'dev-user',
    'Plasma (Sine Interference)',
    'A flowing GPU plasma. Two sine-wave fields at slightly detuned scales beat against each other into shimmering moire fringes, a slow rotating domain warp bends the coordinates into liquid motion, and the result is mapped through a cyclic cosine palette. Self-contained and stateless - one GLSL TOP, no input, no feedback - so it drops in anywhere as a VJ loop, texture, or displacement source.',
    'generative',
    'intermediate',
    '[]',
    5,
    'TOP',
    'ver-plasma-interference',
    'thumbnails/fe6ba80ec1e9bdc80a1e97fc30e971e7da205ae678b5116802da015e9cd9716e',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-mandelbulb-march',
    'mandelbulb-march',
    'dev-user',
    'Mandelbulb March',
    'A raymarched 3D Mandelbulb fractal rendered entirely in one GLSL TOP. The classic distance estimator is marched per pixel against a slowly orbiting camera; orbit-trap values captured during iteration tint the surface, and soft shadows, a fresnel rim, and a proximity glow give it depth. No input, no feedback - a drop-in hero render, a looping VJ source, or a reference for distance-estimated raymarching.',
    'raymarching-sdf',
    'advanced',
    '[]',
    5,
    'TOP',
    'ver-mandelbulb-march',
    'thumbnails/ea8c356215365ad392ed202c1cf816304f89e390bfc6c9ddf1f2823de51b68c4',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-prismatic-strata',
    'prismatic-strata',
    'dev-user',
    'Prismatic Strata',
    'Stacked jagged strata lit from above and wrapped in iridescent fog, a soft pulse of light rolling down through them once per loop, split into orange and azure fringes by a per-channel displacement, with light streaks that rise along the curved layers and bloom. The classic animated-ramp-displaced-by-animated-noise look rebuilt on the GPU: a Ramp TOP, three GLSL TOPs (one writing three color buffers), two Render Select TOPs and a Bloom TOP, looping seamlessly.',
    'generative',
    'advanced',
    '[]',
    18,
    'TOP',
    'ver-prismatic-strata',
    'thumbnails/394150ea06ef4684c215cecaa389956bdac50cc3d6c36dac975a655e112d020a',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  ),
  (
    'sp-mandala',
    'mandala',
    'dev-user',
    'Thangka Mandala',
    'A Tibetan-thangka mandala drawn from POP geometry: 24 parameterised layers (petal rings, gold rings, beads, lace, vase treasures, the red palace square with gates and medallions, lotus rings, a rosette and star at the centre) that breathe, tumble, spin and cross-fade colour in travelling waves, aged by a patchy worn-cloth finish. Every layer is a static copy chain; two GLSL POPs read all layer parameters from a texture buffer and do the whole drawing per frame. Loop mode snaps every rate for seamless renders.',
    'generative',
    'advanced',
    '[]',
    343,
    'POP,CHOP,MAT,TOP',
    'ver-mandala',
    'thumbnails/6bc2530e9d9841f078740906fed6753f5378ee54edb85fe3f295de9da9afd65f',
    'CC-BY-4.0',
    'public',
    'featured',
    'clean',
    '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}',
    0,
    0,
    0
  );

-- Versions (content-addressed: tdn_r2_key = tdn_sha256 = sha256 of the .tdxn bytes).
INSERT OR REPLACE INTO specimen_versions (
  id, specimen_id, version_num, tdn_r2_key, tdn_sha256, size_bytes, op_count, scan_id,
  signature_ref, changelog
) VALUES
  ('ver-murmuration', 'sp-murmuration', 1, '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d', '5c956da2481bc86bda301d7dd6fc3ec237790f30d33a2f2bb589a4ddc1547d3d', 13697, 18, 'scan-murmuration', NULL, 'First-party specimen.'),
  ('ver-reaction-diffusion', 'sp-reaction-diffusion', 1, 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76', 'bfbbf6a07197e1a3dbd712cbcf5524344c4f6b8f6b47b95bf89cae519c110b76', 6850, 14, 'scan-reaction-diffusion', NULL, 'First-party specimen.'),
  ('ver-kaleidoscope', 'sp-kaleidoscope', 1, '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103', '295f25faf270440a15c38067dc6f1c25906a1a18680870d0d5c516a65ccfb103', 8005, 11, 'scan-kaleidoscope', NULL, 'First-party specimen.'),
  ('ver-noise-terrain', 'sp-noise-terrain', 1, '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5', '12d74dd5e88d627653e2e973291b41a704cde968d0a8e61b6ef9ca19bb9025c5', 23789, 20, 'scan-noise-terrain', NULL, 'First-party specimen.'),
  ('ver-plasma-interference', 'sp-plasma-interference', 1, '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63', '532989ed224f716ac444048d76b037e38381e8ac172924bc4f1713d036151d63', 6980, 5, 'scan-plasma-interference', NULL, 'First-party specimen.'),
  ('ver-mandelbulb-march', 'sp-mandelbulb-march', 1, '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d', '9ef1afa22149ebc38e9a5611099c00d979f3f17e2ab8f2d253fa9b8b3947803d', 10257, 5, 'scan-mandelbulb-march', NULL, 'First-party specimen.'),
  ('ver-prismatic-strata', 'sp-prismatic-strata', 1, '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21', '85dd9eb6e4ca3002f81faf1bab51d1eb1540b3465b4cdca79a949a20b3e77e21', 34394, 18, 'scan-prismatic-strata', NULL, 'First-party specimen.'),
  ('ver-mandala', 'sp-mandala', 1, '8a0a6e1800392dd39ef2efebe4130c2c7581b6e579745c1839150f38071e5a13', '8a0a6e1800392dd39ef2efebe4130c2c7581b6e579745c1839150f38071e5a13', 224434, 343, 'scan-mandala', NULL, 'First-party specimen.');

-- Scans (clean verdict, empty capability surface).
INSERT OR REPLACE INTO scans (
  id, version_id, scanner_version, verdict, capability_json, findings_json
) VALUES
  ('scan-murmuration', 'ver-murmuration', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-reaction-diffusion', 'ver-reaction-diffusion', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-kaleidoscope', 'ver-kaleidoscope', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-noise-terrain', 'ver-noise-terrain', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-plasma-interference', 'ver-plasma-interference', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-mandelbulb-march', 'ver-mandelbulb-march', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-prismatic-strata', 'ver-prismatic-strata', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]'),
  ('scan-mandala', 'ver-mandala', 'seed', 'clean', '{"scanner_version":"seed","verdict":"clean","counts":{"execute_dats":0,"file_read_exprs":0,"web_ops":0,"extensions":0,"storage_payloads":0,"denylisted_types":0,"traversal_paths":0,"external_refs":0},"findings":[]}', '[]');

-- Specimen <-> tag links.
INSERT OR IGNORE INTO specimen_tags (specimen_id, tag_id) VALUES
  ('sp-murmuration', 'tag-simulation'),
  ('sp-murmuration', 'tag-glsl'),
  ('sp-murmuration', 'tag-pop'),
  ('sp-murmuration', 'tag-flocking'),
  ('sp-murmuration', 'tag-particles'),
  ('sp-murmuration', 'tag-generative'),
  ('sp-reaction-diffusion', 'tag-feedback'),
  ('sp-reaction-diffusion', 'tag-glsl'),
  ('sp-reaction-diffusion', 'tag-generative'),
  ('sp-reaction-diffusion', 'tag-simulation'),
  ('sp-reaction-diffusion', 'tag-texture'),
  ('sp-kaleidoscope', 'tag-compositing'),
  ('sp-kaleidoscope', 'tag-glsl'),
  ('sp-kaleidoscope', 'tag-mirror'),
  ('sp-kaleidoscope', 'tag-symmetry'),
  ('sp-kaleidoscope', 'tag-effect'),
  ('sp-noise-terrain', 'tag-3d'),
  ('sp-noise-terrain', 'tag-glsl'),
  ('sp-noise-terrain', 'tag-terrain'),
  ('sp-noise-terrain', 'tag-geometry'),
  ('sp-noise-terrain', 'tag-procedural'),
  ('sp-plasma-interference', 'tag-generative'),
  ('sp-plasma-interference', 'tag-glsl'),
  ('sp-plasma-interference', 'tag-plasma'),
  ('sp-plasma-interference', 'tag-palette'),
  ('sp-plasma-interference', 'tag-vj'),
  ('sp-plasma-interference', 'tag-texture'),
  ('sp-mandelbulb-march', 'tag-raymarching'),
  ('sp-mandelbulb-march', 'tag-sdf'),
  ('sp-mandelbulb-march', 'tag-glsl'),
  ('sp-mandelbulb-march', 'tag-fractal'),
  ('sp-mandelbulb-march', 'tag-3d'),
  ('sp-mandelbulb-march', 'tag-mandelbulb'),
  ('sp-prismatic-strata', 'tag-generative'),
  ('sp-prismatic-strata', 'tag-glsl'),
  ('sp-prismatic-strata', 'tag-strata'),
  ('sp-prismatic-strata', 'tag-displace'),
  ('sp-prismatic-strata', 'tag-chromatic'),
  ('sp-prismatic-strata', 'tag-streaks'),
  ('sp-prismatic-strata', 'tag-loop'),
  ('sp-prismatic-strata', 'tag-vj'),
  ('sp-mandala', 'tag-generative'),
  ('sp-mandala', 'tag-pop'),
  ('sp-mandala', 'tag-glsl'),
  ('sp-mandala', 'tag-mandala'),
  ('sp-mandala', 'tag-geometry'),
  ('sp-mandala', 'tag-line'),
  ('sp-mandala', 'tag-loop'),
  ('sp-mandala', 'tag-vj');

-- FTS5 keyword mirror (rowid = specimen rowid; dat_text = key_ops).
INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'murmuration', 'Murmuration', 'A dense GPU particle swarm that flocks like a starling murmuration at dusk - cohering, separating, aligning, and flowing around a slow invisible attractor with curl-noise wander. True per-neighbor Reynolds flocking computed on the GPU (a Neighbor POP index list iterated in a GLSL POP), rendered as luminous additive point sprites.', 'simulation glsl pop flocking particles generative', 'envoy', 'particlePOP neighborPOP glslPOP pointspriteMAT'
FROM specimens WHERE id = 'sp-murmuration';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'reaction-diffusion', 'Reaction-Diffusion (Gray-Scott)', 'A living Gray-Scott reaction-diffusion field. Two chemicals diffuse and react in a GPU feedback loop, growing organic maze and coral patterns that evolve continuously. Usable as a texture, displacement, or mask source.', 'feedback glsl generative simulation texture', 'envoy', 'feedbackTOP glslTOP'
FROM specimens WHERE id = 'sp-reaction-diffusion';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'kaleidoscope', 'Kaleidoscope', 'A reusable kaleidoscope compositor. Folds any TOP (or its built-in animated source) into an N-fold mirrored mandala that rotates, twists, breathes, and tumbles. Drop it onto any visual via the External source mode.', 'compositing glsl mirror symmetry effect', 'envoy', 'glslTOP switchTOP inTOP'
FROM specimens WHERE id = 'sp-kaleidoscope';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'noise-terrain', 'Ridged Mountain Terrain', 'A procedural snow-mountain scene. A GLSL POP compute shader displaces a grid into ridged-multifractal peaks that morph in place, shaded by a snow/rock GLSL MAT with elevation-based snow, sun/sky lighting, and atmospheric haze, composited under a procedural sky.', '3d glsl terrain geometry procedural', 'envoy', 'glslPOP glslMAT gridPOP renderTOP'
FROM specimens WHERE id = 'sp-noise-terrain';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'plasma-interference', 'Plasma (Sine Interference)', 'A flowing GPU plasma. Two sine-wave fields at slightly detuned scales beat against each other into shimmering moire fringes, a slow rotating domain warp bends the coordinates into liquid motion, and the result is mapped through a cyclic cosine palette. Self-contained and stateless - one GLSL TOP, no input, no feedback - so it drops in anywhere as a VJ loop, texture, or displacement source.', 'generative glsl plasma palette vj texture', 'envoy', 'glslTOP'
FROM specimens WHERE id = 'sp-plasma-interference';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'mandelbulb-march', 'Mandelbulb March', 'A raymarched 3D Mandelbulb fractal rendered entirely in one GLSL TOP. The classic distance estimator is marched per pixel against a slowly orbiting camera; orbit-trap values captured during iteration tint the surface, and soft shadows, a fresnel rim, and a proximity glow give it depth. No input, no feedback - a drop-in hero render, a looping VJ source, or a reference for distance-estimated raymarching.', 'raymarching sdf glsl fractal 3d mandelbulb', 'envoy', 'glslTOP'
FROM specimens WHERE id = 'sp-mandelbulb-march';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'prismatic-strata', 'Prismatic Strata', 'Stacked jagged strata lit from above and wrapped in iridescent fog, a soft pulse of light rolling down through them once per loop, split into orange and azure fringes by a per-channel displacement, with light streaks that rise along the curved layers and bloom. The classic animated-ramp-displaced-by-animated-noise look rebuilt on the GPU: a Ramp TOP, three GLSL TOPs (one writing three color buffers), two Render Select TOPs and a Bloom TOP, looping seamlessly.', 'generative glsl strata displace chromatic streaks loop vj', 'envoy', 'glslTOP rampTOP renderselectTOP bloomTOP'
FROM specimens WHERE id = 'sp-prismatic-strata';

INSERT OR REPLACE INTO specimens_fts (rowid, slug, title, description, tags, author_handle, dat_text)
SELECT rowid, 'mandala', 'Thangka Mandala', 'A Tibetan-thangka mandala drawn from POP geometry: 24 parameterised layers (petal rings, gold rings, beads, lace, vase treasures, the red palace square with gates and medallions, lotus rings, a rosette and star at the centre) that breathe, tumble, spin and cross-fade colour in travelling waves, aged by a patchy worn-cloth finish. Every layer is a static copy chain; two GLSL POPs read all layer parameters from a texture buffer and do the whole drawing per frame. Loop mode snaps every rate for seamless renders.', 'generative pop glsl mandala geometry line loop vj', 'envoy', 'glslPOP copyPOP circlePOP mergePOP shuffleCHOP lineMAT constantMAT glslTOP'
FROM specimens WHERE id = 'sp-mandala';

-- Category membership (multi). Seed the join table from each specimen's primary
-- category so the collection facet filter (which reads specimen_categories) and
-- the category facets list include the seeded rows. Mirrors migration 0010.
INSERT OR IGNORE INTO specimen_categories (specimen_id, category)
SELECT id, category FROM specimens WHERE category IS NOT NULL AND category <> '';
